{lib, callPackage, ...}:
let
    versions = (let
        _vFwj8Up3 = {
            "id" = "vFwj8Up3";
            "file" = "Less-Pumpkin-Blur.zip";
            "hash" = "sha512-NWRJGUtw57088TREHZaNl8vcSwaRtS5L9wN2HHrjylwWx+ECUL+StxJaponDYwzixLqrcKLjN+ZxTuWJ+2EHug==";
        };
        _WlMlf9Xw = {
            "id" = "WlMlf9Xw";
            "file" = "Less-Pumpkin-Blur.zip";
            "hash" = "sha512-ys8F9qEdYMRUxL5enti2DtMoq7YdA8ar2557B0hqbIDZXFxPufuwzoqZ9rDuFueumO4uVKkMKaOBxTO+JJQRnA==";
        };
    in {
        "vFwj8Up3" = _vFwj8Up3;
        "WlMlf9Xw" = _WlMlf9Xw;
        "minecraft-1.6.1" = _WlMlf9Xw;
        "minecraft-1.6.2" = _WlMlf9Xw;
        "minecraft-1.6.4" = _WlMlf9Xw;
        "minecraft-1.7.2" = _WlMlf9Xw;
        "minecraft-1.7.3" = _WlMlf9Xw;
        "minecraft-1.7.4" = _WlMlf9Xw;
        "minecraft-1.7.5" = _WlMlf9Xw;
        "minecraft-1.7.6" = _WlMlf9Xw;
        "minecraft-1.7.7" = _WlMlf9Xw;
        "minecraft-1.7.8" = _WlMlf9Xw;
        "minecraft-1.7.9" = _WlMlf9Xw;
        "minecraft-1.7.10" = _WlMlf9Xw;
        "minecraft-1.8" = _WlMlf9Xw;
        "minecraft-1.8.1" = _WlMlf9Xw;
        "minecraft-1.8.2" = _WlMlf9Xw;
        "minecraft-1.8.3" = _WlMlf9Xw;
        "minecraft-1.8.4" = _WlMlf9Xw;
        "minecraft-1.8.5" = _WlMlf9Xw;
        "minecraft-1.8.6" = _WlMlf9Xw;
        "minecraft-1.8.7" = _WlMlf9Xw;
        "minecraft-1.8.8" = _WlMlf9Xw;
        "minecraft-1.8.9" = _WlMlf9Xw;
        "minecraft-1.9" = _WlMlf9Xw;
        "minecraft-1.9.1" = _WlMlf9Xw;
        "minecraft-1.9.2" = _WlMlf9Xw;
        "minecraft-1.9.3" = _WlMlf9Xw;
        "minecraft-1.9.4" = _WlMlf9Xw;
        "minecraft-1.10" = _WlMlf9Xw;
        "minecraft-1.10.1" = _WlMlf9Xw;
        "minecraft-1.10.2" = _WlMlf9Xw;
        "minecraft-1.11" = _WlMlf9Xw;
        "minecraft-1.11.1" = _WlMlf9Xw;
        "minecraft-1.11.2" = _WlMlf9Xw;
        "minecraft-1.12" = _WlMlf9Xw;
        "minecraft-1.12.1" = _WlMlf9Xw;
        "minecraft-1.12.2" = _WlMlf9Xw;
        "minecraft-1.13" = _WlMlf9Xw;
        "minecraft-1.13.1" = _WlMlf9Xw;
        "minecraft-1.13.2" = _WlMlf9Xw;
        "minecraft-1.14" = _WlMlf9Xw;
        "minecraft-1.14.1" = _WlMlf9Xw;
        "minecraft-1.14.2" = _WlMlf9Xw;
        "minecraft-1.14.3" = _WlMlf9Xw;
        "minecraft-1.14.4" = _WlMlf9Xw;
        "minecraft-1.15" = _WlMlf9Xw;
        "minecraft-1.15.1" = _WlMlf9Xw;
        "minecraft-1.15.2" = _WlMlf9Xw;
        "minecraft-1.16" = _WlMlf9Xw;
        "minecraft-1.16.1" = _WlMlf9Xw;
        "minecraft-1.16.2" = _WlMlf9Xw;
        "minecraft-1.16.3" = _WlMlf9Xw;
        "minecraft-1.16.4" = _WlMlf9Xw;
        "minecraft-1.16.5" = _WlMlf9Xw;
        "minecraft-1.17" = _WlMlf9Xw;
        "minecraft-1.17.1" = _WlMlf9Xw;
        "minecraft-1.18" = _WlMlf9Xw;
        "minecraft-1.18.1" = _WlMlf9Xw;
        "minecraft-1.18.2" = _WlMlf9Xw;
        "minecraft-1.19" = _WlMlf9Xw;
        "minecraft-1.19.1" = _WlMlf9Xw;
        "minecraft-1.19.2" = _WlMlf9Xw;
        "minecraft-1.19.3" = _WlMlf9Xw;
        "minecraft-1.19.4" = _WlMlf9Xw;
        "minecraft-1.20" = _WlMlf9Xw;
        "minecraft-1.20.1" = _WlMlf9Xw;
        "minecraft-1.20.2" = _WlMlf9Xw;
        "minecraft-1.20.3" = _WlMlf9Xw;
        "minecraft-1.20.4" = _WlMlf9Xw;
        "minecraft-1.20.5" = _WlMlf9Xw;
        "minecraft-1.20.6" = _WlMlf9Xw;
        "minecraft-1.21" = _WlMlf9Xw;
        "minecraft-1.21.1" = _WlMlf9Xw;
        "minecraft-1.21.2" = _WlMlf9Xw;
        "minecraft-1.21.3" = _WlMlf9Xw;
        "minecraft-1.21.4" = _WlMlf9Xw;
        "minecraft-1.21.5" = _WlMlf9Xw;
        "minecraft-1.21.6" = _WlMlf9Xw;
        "minecraft-1.21.7" = _WlMlf9Xw;
        "minecraft-1.21.8" = _WlMlf9Xw;
        "minecraft-1.21.9" = _WlMlf9Xw;
        "minecraft-1.21.10" = _WlMlf9Xw;
        "minecraft-1.21.11" = _WlMlf9Xw;
        "minecraft-26.1" = _WlMlf9Xw;
        "minecraft-26.1.1" = _WlMlf9Xw;
        "minecraft-26.1.2" = _WlMlf9Xw;
        "minecraft-26.2" = _WlMlf9Xw;
    });
    fn = {stdenv, fetchurl, version, ...}:
        lib.prismnix.pkgs.mkVersionedModrinthPkg {
            inherit stdenv fetchurl;
            name = "less-pumpkin-blur";
            id = "35fDzmr1";
            type = "resourcepack";
            version = version;
            versions = versions;
            meta = {
                license = lib.getLicenseFromSpdxIdOr "Zlib" {
                    free = false;
                    deprecated = false;
                    redistributable = false;
                    fullName = "zlib License";
                    shortName = "Zlib";
                    url = null;
                };
            };
        };
in callPackage fn {version="WlMlf9Xw";}