{lib, callPackage, ...}:
let
    versions = (let
        _uhrJmgJY = {
            "id" = "uhrJmgJY";
            "file" = "PSX-Core v0.1.0.zip";
            "hash" = "sha512-kWz5vklJbYF9NxFL5WZnChjypcAjeJU8HA+UU9XCKGYHsbA/DleSoa0opB1gB4CBXzC5FeLHcafSaG3SAqEbYQ==";
        };
        _DU7DC7VU = {
            "id" = "DU7DC7VU";
            "file" = "PSX-Core v0.1.1.zip";
            "hash" = "sha512-BXhLWeghtXQFalexy+H9+1dyoytcYRJtYdSklXySngpn8l3o+he9dEg6sDSTIMXAWUYMqUX1POga+3Hx/PTSRQ==";
        };
        _tjkODnoV = {
            "id" = "tjkODnoV";
            "file" = "PSX-Core v0.1.2.zip";
            "hash" = "sha512-t61KeBPNWH5+H/gi0xpUerKDla8XKzAoqaTKJ+ANrJiai8yGYsZdG6JheKrQKsS00vFJaxU7bhlmfvrVnEqncw==";
        };
        _a9OZzJA9 = {
            "id" = "a9OZzJA9";
            "file" = "PSX-Core v0.1.3.zip";
            "hash" = "sha512-KevbL38lXYHGlu4faado+7b18aZ3FaH4rEgaxk1G80StTvpINGlVTj+jnYqWlAW9p5kmcINiq/JAlAzNafo6Vw==";
        };
        _8oWsi3FD = {
            "id" = "8oWsi3FD";
            "file" = "PSX-Core v0.1.4.zip";
            "hash" = "sha512-JJyP5uMLt8lvk6OIUiulOxF6vp1n3chN3GOoCARp0pPwxypOFdcjtI46vuH2lz9G9LDTfLZhF9HJeV4fPpaYRA==";
        };
        _C5z3XEBv = {
            "id" = "C5z3XEBv";
            "file" = "PSX-Core v0.1.5.zip";
            "hash" = "sha512-Bu9SBik8N+mg8bmGYUjvNgugVRBQgIihx+wd4K7Mfv7t+aTB9okUFErzQgVADFuXbDySUy8ZC7pv4oxGcm8oeg==";
        };
        _LPYMYfIo = {
            "id" = "LPYMYfIo";
            "file" = "PSX-Core v0.1.6.zip";
            "hash" = "sha512-qOe2rsYA0zCWsLVQ/DmGmrt5NfBjSPFa+k5CGfLkq68ReaVME5HU/AvmSHFTUp/O1srWgxdWiAZDVVKNocPw/Q==";
        };
    in {
        "uhrJmgJY" = _uhrJmgJY;
        "DU7DC7VU" = _DU7DC7VU;
        "tjkODnoV" = _tjkODnoV;
        "a9OZzJA9" = _a9OZzJA9;
        "8oWsi3FD" = _8oWsi3FD;
        "C5z3XEBv" = _C5z3XEBv;
        "LPYMYfIo" = _LPYMYfIo;
        "iris-1.18" = _LPYMYfIo;
        "iris-1.18.1" = _LPYMYfIo;
        "iris-1.18.2" = _LPYMYfIo;
        "iris-1.19" = _LPYMYfIo;
        "iris-1.19.1" = _LPYMYfIo;
        "iris-1.19.2" = _LPYMYfIo;
        "iris-1.19.3" = _LPYMYfIo;
        "iris-1.19.4" = _LPYMYfIo;
        "iris-1.20" = _LPYMYfIo;
        "iris-1.20.1" = _LPYMYfIo;
        "iris-1.20.2" = _LPYMYfIo;
        "iris-1.20.3" = _LPYMYfIo;
        "iris-1.20.4" = _LPYMYfIo;
        "iris-1.20.5" = _LPYMYfIo;
        "iris-1.20.6" = _LPYMYfIo;
        "iris-1.21" = _LPYMYfIo;
        "iris-1.21.1" = _LPYMYfIo;
        "iris-1.21.2" = _LPYMYfIo;
        "iris-1.21.3" = _LPYMYfIo;
        "iris-1.21.4" = _LPYMYfIo;
        "iris-1.21.5" = _LPYMYfIo;
        "iris-1.21.6" = _LPYMYfIo;
        "iris-1.21.7" = _LPYMYfIo;
        "iris-1.21.8" = _LPYMYfIo;
        "iris-1.21.9" = _LPYMYfIo;
        "iris-1.21.10" = _LPYMYfIo;
        "iris-1.21.11" = _LPYMYfIo;
        "iris-1.8" = _LPYMYfIo;
        "iris-1.8.1" = _LPYMYfIo;
        "iris-1.8.2" = _LPYMYfIo;
        "iris-1.8.3" = _LPYMYfIo;
        "iris-1.8.4" = _LPYMYfIo;
        "iris-1.8.5" = _LPYMYfIo;
        "iris-1.8.6" = _LPYMYfIo;
        "iris-1.8.7" = _LPYMYfIo;
        "iris-1.8.8" = _LPYMYfIo;
        "iris-1.8.9" = _LPYMYfIo;
        "iris-1.9" = _LPYMYfIo;
        "iris-1.9.1" = _LPYMYfIo;
        "iris-1.9.2" = _LPYMYfIo;
        "iris-1.9.3" = _LPYMYfIo;
        "iris-1.9.4" = _LPYMYfIo;
        "iris-1.10" = _LPYMYfIo;
        "iris-1.10.1" = _LPYMYfIo;
        "iris-1.10.2" = _LPYMYfIo;
        "iris-1.11" = _LPYMYfIo;
        "iris-1.11.1" = _LPYMYfIo;
        "iris-1.11.2" = _LPYMYfIo;
        "iris-1.12" = _LPYMYfIo;
        "iris-1.12.1" = _LPYMYfIo;
        "iris-1.12.2" = _LPYMYfIo;
        "iris-1.13" = _LPYMYfIo;
        "iris-1.13.1" = _LPYMYfIo;
        "iris-1.13.2" = _LPYMYfIo;
        "iris-1.14" = _LPYMYfIo;
        "iris-1.14.1" = _LPYMYfIo;
        "iris-1.14.2" = _LPYMYfIo;
        "iris-1.14.3" = _LPYMYfIo;
        "iris-1.14.4" = _LPYMYfIo;
        "iris-1.15" = _LPYMYfIo;
        "iris-1.15.1" = _LPYMYfIo;
        "iris-1.15.2" = _LPYMYfIo;
        "iris-1.16" = _LPYMYfIo;
        "iris-1.16.1" = _LPYMYfIo;
        "iris-1.16.2" = _LPYMYfIo;
        "iris-1.16.3" = _LPYMYfIo;
        "iris-1.16.4" = _LPYMYfIo;
        "iris-1.16.5" = _LPYMYfIo;
        "iris-1.17" = _LPYMYfIo;
        "iris-1.17.1" = _LPYMYfIo;
        "iris-26.1" = _LPYMYfIo;
        "iris-26.1.1" = _LPYMYfIo;
        "iris-26.1.2" = _LPYMYfIo;
        "iris-26.2" = _LPYMYfIo;
        "optifine-1.18" = _LPYMYfIo;
        "optifine-1.18.1" = _LPYMYfIo;
        "optifine-1.18.2" = _LPYMYfIo;
        "optifine-1.19" = _LPYMYfIo;
        "optifine-1.19.1" = _LPYMYfIo;
        "optifine-1.19.2" = _LPYMYfIo;
        "optifine-1.19.3" = _LPYMYfIo;
        "optifine-1.19.4" = _LPYMYfIo;
        "optifine-1.20" = _LPYMYfIo;
        "optifine-1.20.1" = _LPYMYfIo;
        "optifine-1.20.2" = _LPYMYfIo;
        "optifine-1.20.3" = _LPYMYfIo;
        "optifine-1.20.4" = _LPYMYfIo;
        "optifine-1.20.5" = _LPYMYfIo;
        "optifine-1.20.6" = _LPYMYfIo;
        "optifine-1.21" = _LPYMYfIo;
        "optifine-1.21.1" = _LPYMYfIo;
        "optifine-1.21.2" = _LPYMYfIo;
        "optifine-1.21.3" = _LPYMYfIo;
        "optifine-1.21.4" = _LPYMYfIo;
        "optifine-1.21.5" = _LPYMYfIo;
        "optifine-1.21.6" = _LPYMYfIo;
        "optifine-1.21.7" = _LPYMYfIo;
        "optifine-1.21.8" = _LPYMYfIo;
        "optifine-1.21.9" = _LPYMYfIo;
        "optifine-1.21.10" = _LPYMYfIo;
        "optifine-1.21.11" = _LPYMYfIo;
        "optifine-1.8" = _LPYMYfIo;
        "optifine-1.8.1" = _LPYMYfIo;
        "optifine-1.8.2" = _LPYMYfIo;
        "optifine-1.8.3" = _LPYMYfIo;
        "optifine-1.8.4" = _LPYMYfIo;
        "optifine-1.8.5" = _LPYMYfIo;
        "optifine-1.8.6" = _LPYMYfIo;
        "optifine-1.8.7" = _LPYMYfIo;
        "optifine-1.8.8" = _LPYMYfIo;
        "optifine-1.8.9" = _LPYMYfIo;
        "optifine-1.9" = _LPYMYfIo;
        "optifine-1.9.1" = _LPYMYfIo;
        "optifine-1.9.2" = _LPYMYfIo;
        "optifine-1.9.3" = _LPYMYfIo;
        "optifine-1.9.4" = _LPYMYfIo;
        "optifine-1.10" = _LPYMYfIo;
        "optifine-1.10.1" = _LPYMYfIo;
        "optifine-1.10.2" = _LPYMYfIo;
        "optifine-1.11" = _LPYMYfIo;
        "optifine-1.11.1" = _LPYMYfIo;
        "optifine-1.11.2" = _LPYMYfIo;
        "optifine-1.12" = _LPYMYfIo;
        "optifine-1.12.1" = _LPYMYfIo;
        "optifine-1.12.2" = _LPYMYfIo;
        "optifine-1.13" = _LPYMYfIo;
        "optifine-1.13.1" = _LPYMYfIo;
        "optifine-1.13.2" = _LPYMYfIo;
        "optifine-1.14" = _LPYMYfIo;
        "optifine-1.14.1" = _LPYMYfIo;
        "optifine-1.14.2" = _LPYMYfIo;
        "optifine-1.14.3" = _LPYMYfIo;
        "optifine-1.14.4" = _LPYMYfIo;
        "optifine-1.15" = _LPYMYfIo;
        "optifine-1.15.1" = _LPYMYfIo;
        "optifine-1.15.2" = _LPYMYfIo;
        "optifine-1.16" = _LPYMYfIo;
        "optifine-1.16.1" = _LPYMYfIo;
        "optifine-1.16.2" = _LPYMYfIo;
        "optifine-1.16.3" = _LPYMYfIo;
        "optifine-1.16.4" = _LPYMYfIo;
        "optifine-1.16.5" = _LPYMYfIo;
        "optifine-1.17" = _LPYMYfIo;
        "optifine-1.17.1" = _LPYMYfIo;
        "optifine-26.1" = _LPYMYfIo;
        "optifine-26.1.1" = _LPYMYfIo;
        "optifine-26.1.2" = _LPYMYfIo;
        "optifine-26.2" = _LPYMYfIo;
        "pkg-0.1.0" = _uhrJmgJY;
        "pkg-0.1.1" = _DU7DC7VU;
        "pkg-0.1.2" = _tjkODnoV;
        "pkg-0.1.3" = _a9OZzJA9;
        "pkg-0.1.4" = _8oWsi3FD;
        "pkg-0.1.5" = _C5z3XEBv;
        "pkg-0.1.6" = _LPYMYfIo;
        "default" = _LPYMYfIo;
    });
    fn = lib.prismnix.pkgs.mkVersionedModrinthPkgFn {
        name = "psx-core";
        id = "424Wbdmo";
        type = "shader";
        versions = versions;
        meta = {
            license = lib.getLicenseFromSpdxIdOr "LicenseRef-All-Rights-Reserved" {
                free = false;
                deprecated = false;
                redistributable = false;
                fullName = "LicenseRef-All-Rights-Reserved";
                shortName = "LicenseRef-All-Rights-Reserved";
                url = null;
            };
        };
    };
in callPackage fn {}