{lib, callPackage, ...}:
let
    versions = (let
        _fzCQiT0N = {
            "id" = "fzCQiT0N";
            "file" = "Simple+Click+1.20.2.zip";
            "hash" = "sha512-iufjdQ3erjRWeV3l5erUYQJT9TsNHIq30NEUItYpkq/YHOFVfXQ0BE/438Ab/x5b8T23phVybfV7vmRLpiH8VQ==";
        };
        _dsIdwc3p = {
            "id" = "dsIdwc3p";
            "file" = "Simple_Click_Universal.zip";
            "hash" = "sha512-IWLMwoIJ/ldqapNAoCf2TPyhUILz3blVdKFA9mP2Ek1w8azAhHBSJJ1HdxbjLj0YNL1pZH49iT3hXawEYKd+BQ==";
        };
    in {
        "fzCQiT0N" = _fzCQiT0N;
        "dsIdwc3p" = _dsIdwc3p;
        "minecraft-1.20" = _dsIdwc3p;
        "minecraft-1.20.1" = _dsIdwc3p;
        "minecraft-1.20.2" = _dsIdwc3p;
        "minecraft-1.20.3" = _dsIdwc3p;
        "minecraft-1.20.4" = _dsIdwc3p;
        "minecraft-1.20.5" = _dsIdwc3p;
        "minecraft-1.20.6" = _dsIdwc3p;
        "minecraft-1.7.2" = _dsIdwc3p;
        "minecraft-1.7.3" = _dsIdwc3p;
        "minecraft-1.7.4" = _dsIdwc3p;
        "minecraft-1.7.5" = _dsIdwc3p;
        "minecraft-1.7.6" = _dsIdwc3p;
        "minecraft-1.7.7" = _dsIdwc3p;
        "minecraft-1.7.8" = _dsIdwc3p;
        "minecraft-1.7.9" = _dsIdwc3p;
        "minecraft-1.7.10" = _dsIdwc3p;
        "minecraft-1.8" = _dsIdwc3p;
        "minecraft-1.8.1" = _dsIdwc3p;
        "minecraft-1.8.2" = _dsIdwc3p;
        "minecraft-1.8.3" = _dsIdwc3p;
        "minecraft-1.8.4" = _dsIdwc3p;
        "minecraft-1.8.5" = _dsIdwc3p;
        "minecraft-1.8.6" = _dsIdwc3p;
        "minecraft-1.8.7" = _dsIdwc3p;
        "minecraft-1.8.8" = _dsIdwc3p;
        "minecraft-1.8.9" = _dsIdwc3p;
        "minecraft-1.9" = _dsIdwc3p;
        "minecraft-1.9.1" = _dsIdwc3p;
        "minecraft-1.9.2" = _dsIdwc3p;
        "minecraft-1.9.3" = _dsIdwc3p;
        "minecraft-1.9.4" = _dsIdwc3p;
        "minecraft-1.10" = _dsIdwc3p;
        "minecraft-1.10.1" = _dsIdwc3p;
        "minecraft-1.10.2" = _dsIdwc3p;
        "minecraft-1.11" = _dsIdwc3p;
        "minecraft-1.11.1" = _dsIdwc3p;
        "minecraft-1.11.2" = _dsIdwc3p;
        "minecraft-1.12" = _dsIdwc3p;
        "minecraft-1.12.1" = _dsIdwc3p;
        "minecraft-1.12.2" = _dsIdwc3p;
        "minecraft-1.13" = _dsIdwc3p;
        "minecraft-1.13.1" = _dsIdwc3p;
        "minecraft-1.13.2" = _dsIdwc3p;
        "minecraft-1.14" = _dsIdwc3p;
        "minecraft-1.14.1" = _dsIdwc3p;
        "minecraft-1.14.2" = _dsIdwc3p;
        "minecraft-1.14.3" = _dsIdwc3p;
        "minecraft-1.14.4" = _dsIdwc3p;
        "minecraft-1.15" = _dsIdwc3p;
        "minecraft-1.15.1" = _dsIdwc3p;
        "minecraft-1.15.2" = _dsIdwc3p;
        "minecraft-1.16" = _dsIdwc3p;
        "minecraft-1.16.1" = _dsIdwc3p;
        "minecraft-1.16.2" = _dsIdwc3p;
        "minecraft-1.16.3" = _dsIdwc3p;
        "minecraft-1.16.4" = _dsIdwc3p;
        "minecraft-1.16.5" = _dsIdwc3p;
        "minecraft-1.17" = _dsIdwc3p;
        "minecraft-1.17.1" = _dsIdwc3p;
        "minecraft-1.18" = _dsIdwc3p;
        "minecraft-1.18.1" = _dsIdwc3p;
        "minecraft-1.18.2" = _dsIdwc3p;
        "minecraft-1.19" = _dsIdwc3p;
        "minecraft-1.19.1" = _dsIdwc3p;
        "minecraft-1.19.2" = _dsIdwc3p;
        "minecraft-1.19.3" = _dsIdwc3p;
        "minecraft-1.19.4" = _dsIdwc3p;
        "minecraft-1.21" = _dsIdwc3p;
        "minecraft-1.21.1" = _dsIdwc3p;
        "minecraft-1.21.2" = _dsIdwc3p;
        "minecraft-1.21.3" = _dsIdwc3p;
        "minecraft-1.21.4" = _dsIdwc3p;
        "minecraft-1.21.5" = _dsIdwc3p;
        "minecraft-1.21.6" = _dsIdwc3p;
        "minecraft-1.21.7" = _dsIdwc3p;
        "default" = _dsIdwc3p;
    });
    fn = lib.prismnix.pkgs.mkVersionedModrinthPkgFn {
        name = "simple-click";
        id = "5oPLc04X";
        type = "resourcepack";
        versions = versions;
        meta = {
            license = lib.getLicenseFromSpdxIdOr "MIT" {
                free = false;
                deprecated = false;
                redistributable = false;
                fullName = "MIT License";
                shortName = "MIT";
                url = null;
            };
        };
    };
in callPackage fn {}