{lib, callPackage, ...}:
let
    versions = (let
        _i6rC4Exw = {
            "id" = "i6rC4Exw";
            "file" = "notexture.zip";
            "hash" = "sha512-knf03wLOcgQq3b0sXOmrBKxKW9twHTwLGcQoAaeuvVjRaFXN6/FmebvV4x2pytAlsVT3aPnrAiHm996WYQ67aQ==";
        };
        _VmA6gOPw = {
            "id" = "VmA6gOPw";
            "file" = "notexture.zip";
            "hash" = "sha512-vLeoi4cpBax02nQFgNkNTLNOr5/TBZI8gDHXIVlqZ1jHDDhQR+Wla1tw2yjJJ3jBruZNZnQ8by/cDFN9r054ug==";
        };
        _lmPz2LFr = {
            "id" = "lmPz2LFr";
            "file" = "notexture.zip";
            "hash" = "sha512-xlvHrMLjzPVuMP1CtPZo6fvetMowM+SdB9TAQLEu5oj3BXsY+bvPw62BBRUEbyqc0dB+zMTaeltdCqXXZ4Er3Q==";
        };
    in {
        "i6rC4Exw" = _i6rC4Exw;
        "VmA6gOPw" = _VmA6gOPw;
        "lmPz2LFr" = _lmPz2LFr;
        "minecraft-1.0" = _lmPz2LFr;
        "minecraft-1.1" = _lmPz2LFr;
        "minecraft-1.2.1" = _lmPz2LFr;
        "minecraft-1.2.2" = _lmPz2LFr;
        "minecraft-1.2.3" = _lmPz2LFr;
        "minecraft-1.2.4" = _lmPz2LFr;
        "minecraft-1.2.5" = _lmPz2LFr;
        "minecraft-1.3.1" = _lmPz2LFr;
        "minecraft-1.3.2" = _lmPz2LFr;
        "minecraft-1.4.2" = _lmPz2LFr;
        "minecraft-1.4.4" = _lmPz2LFr;
        "minecraft-1.4.5" = _lmPz2LFr;
        "minecraft-1.4.6" = _lmPz2LFr;
        "minecraft-1.4.7" = _lmPz2LFr;
        "minecraft-1.5.1" = _lmPz2LFr;
        "minecraft-1.5.2" = _lmPz2LFr;
        "minecraft-1.6.1" = _lmPz2LFr;
        "minecraft-1.6.2" = _lmPz2LFr;
        "minecraft-1.6.4" = _lmPz2LFr;
        "minecraft-1.7.2" = _lmPz2LFr;
        "minecraft-1.7.3" = _lmPz2LFr;
        "minecraft-1.7.4" = _lmPz2LFr;
        "minecraft-1.7.5" = _lmPz2LFr;
        "minecraft-1.7.6" = _lmPz2LFr;
        "minecraft-1.7.7" = _lmPz2LFr;
        "minecraft-1.7.8" = _lmPz2LFr;
        "minecraft-1.7.9" = _lmPz2LFr;
        "minecraft-1.7.10" = _lmPz2LFr;
        "minecraft-1.8" = _lmPz2LFr;
        "minecraft-1.8.1" = _lmPz2LFr;
        "minecraft-1.8.2" = _lmPz2LFr;
        "minecraft-1.8.3" = _lmPz2LFr;
        "minecraft-1.8.4" = _lmPz2LFr;
        "minecraft-1.8.5" = _lmPz2LFr;
        "minecraft-1.8.6" = _lmPz2LFr;
        "minecraft-1.8.7" = _lmPz2LFr;
        "minecraft-1.8.8" = _lmPz2LFr;
        "minecraft-1.8.9" = _lmPz2LFr;
        "minecraft-1.9" = _lmPz2LFr;
        "minecraft-1.9.1" = _lmPz2LFr;
        "minecraft-1.9.2" = _lmPz2LFr;
        "minecraft-1.9.3" = _lmPz2LFr;
        "minecraft-1.9.4" = _lmPz2LFr;
        "minecraft-1.10" = _lmPz2LFr;
        "minecraft-1.10.1" = _lmPz2LFr;
        "minecraft-1.10.2" = _lmPz2LFr;
        "minecraft-1.11" = _lmPz2LFr;
        "minecraft-1.11.1" = _lmPz2LFr;
        "minecraft-1.11.2" = _lmPz2LFr;
        "minecraft-1.12" = _lmPz2LFr;
        "minecraft-1.12.1" = _lmPz2LFr;
        "minecraft-1.12.2" = _lmPz2LFr;
        "minecraft-1.13" = _lmPz2LFr;
        "minecraft-1.13.1" = _lmPz2LFr;
        "minecraft-1.13.2" = _lmPz2LFr;
        "minecraft-1.14" = _lmPz2LFr;
        "minecraft-1.14.1" = _lmPz2LFr;
        "minecraft-1.14.2" = _lmPz2LFr;
        "minecraft-1.14.3" = _lmPz2LFr;
        "minecraft-1.14.4" = _lmPz2LFr;
        "minecraft-1.15" = _lmPz2LFr;
        "minecraft-1.15.1" = _lmPz2LFr;
        "minecraft-1.15.2" = _lmPz2LFr;
        "minecraft-1.16" = _lmPz2LFr;
        "minecraft-1.16.1" = _lmPz2LFr;
        "minecraft-1.16.2" = _lmPz2LFr;
        "minecraft-1.16.3" = _lmPz2LFr;
        "minecraft-1.16.4" = _lmPz2LFr;
        "minecraft-1.16.5" = _lmPz2LFr;
        "minecraft-1.17" = _lmPz2LFr;
        "minecraft-1.17.1" = _lmPz2LFr;
        "minecraft-1.18" = _lmPz2LFr;
        "minecraft-1.18.1" = _lmPz2LFr;
        "minecraft-1.18.2" = _lmPz2LFr;
        "minecraft-1.19" = _lmPz2LFr;
        "minecraft-1.19.1" = _lmPz2LFr;
        "minecraft-1.19.2" = _lmPz2LFr;
        "minecraft-1.19.3" = _lmPz2LFr;
        "minecraft-1.19.4" = _lmPz2LFr;
        "minecraft-1.20" = _lmPz2LFr;
        "minecraft-1.20.1" = _lmPz2LFr;
        "minecraft-1.20.2" = _lmPz2LFr;
        "minecraft-1.20.3" = _lmPz2LFr;
        "minecraft-1.20.4" = _lmPz2LFr;
        "minecraft-1.20.5" = _lmPz2LFr;
        "minecraft-1.20.6" = _lmPz2LFr;
        "minecraft-1.21" = _lmPz2LFr;
        "default" = _lmPz2LFr;
    });
    fn = {stdenv, fetchurl, version, ...}:
        lib.prismnix.pkgs.mkVersionedModrinthPkg {
            inherit stdenv fetchurl;
            name = "notexture";
            id = "9ToYVqwz";
            type = "resourcepack";
            version = version;
            versions = versions;
            meta = {
                license = lib.getLicenseFromSpdxIdOr "LicenseRef-All-Rights-Reserved" {
                    free = false;
                    deprecated = false;
                    redistributable = false;
                    fullName = "LicenseRef-All-Rights-Reserved";
                    shortName = "LicenseRef-All-Rights-Reserved";
                    url = null;
                };
            };
        };
in callPackage fn {version="default";}