{lib, callPackage, ...}:
let
    versions = (let
        _ZpnuMn3U = {
            "id" = "ZpnuMn3U";
            "file" = "Vouchers-1.0.0.jar";
            "hash" = "sha512-cW1vB2mO4GTTmwH6I8XUCBDljEiHV3dvya0i32lzv29XEBYISGkBjyieJwQWsNM3p8V7j4QofpN/RQkbqDBF8w==";
        };
        _KzlU2wRH = {
            "id" = "KzlU2wRH";
            "file" = "Vouchers-1.0.1.jar";
            "hash" = "sha512-uzTSkY1tvNqK1RVYK/ow6oXlIkqomN+24+AP58y/8FztnU/juZ2tSkIrDyFYaSAWX+S0BY6mnBZ/+5Ok9IdVQA==";
        };
        _VqZbhRgp = {
            "id" = "VqZbhRgp";
            "file" = "Vouchers-1.0.2.jar";
            "hash" = "sha512-DfDFkKKMcN2hgT5fukNzvsq+H41BtwK9Qig418z0XkjcMuCaflb+/aFoXBR0/64Dnj27zduaPSRp0UWGpU2Fvw==";
        };
        _HmAeD9gg = {
            "id" = "HmAeD9gg";
            "file" = "Vouchers-1.0.3.jar";
            "hash" = "sha512-xmp9KXP7+CGekuDGkPd5tEbTES2oUEparnaG7KXXuWq8OQmRmKO2bHzTHG9hK4OiwHb1sEeKaiuvxruvvfo3Bg==";
        };
        _Okyy63xU = {
            "id" = "Okyy63xU";
            "file" = "Vouchers-1.0.4.jar";
            "hash" = "sha512-aa4utxIYl+6411dhypIutsuUJcMVZn1nE2ey0VRCIstOWHSB9kR7g6kl/898xv6Kz45fJYfgxTGqcatdbODguA==";
        };
        _PZcESO7h = {
            "id" = "PZcESO7h";
            "file" = "Vouchers-1.0.5.jar";
            "hash" = "sha512-NOJJjbG2WGioeolvFpHkUlCjJX6+0Y5XBIyZq1jFufO7rRylmqHtXPBBdidYrksjwHfMboRCM34DsRG74Tw7Dg==";
        };
        _cIvKQVaI = {
            "id" = "cIvKQVaI";
            "file" = "Vouchers-1.0.6.jar";
            "hash" = "sha512-UhgpJ6GGeHr2/Fe9j31MpDNbv7VmF9TNQPTxJGmY25ioJKJTCPaSDsB/JCXoaHcL4N42/wKNlTRtpoQ/Ab6Eiw==";
        };
        _claMXMZy = {
            "id" = "claMXMZy";
            "file" = "Vouchers-1.0.7.jar";
            "hash" = "sha512-tQKaqgJU/q5eix+kPfoJUBSQdYQVKATinWoUn9Uh31cYAPJvw55fTw2pdZF+yQu/PVPmusDqdv2dVjUhimwCxg==";
        };
        _oYtpX7hI = {
            "id" = "oYtpX7hI";
            "file" = "Vouchers-1.0.8.jar";
            "hash" = "sha512-eAD45xRfe+dhDlHDBFw9jaGKcM579+b7OifPVWX78xYRs8bbpZLOi7aCs5rgMb5aNoIVnMYI/nKQT/lv986x9A==";
        };
        _IPv1zeyY = {
            "id" = "IPv1zeyY";
            "file" = "Vouchers-1.0.9.jar";
            "hash" = "sha512-6ajnMTFg5N1cojfywYGdXvzp1M83lo+eLEpD/4gtvKY1X1w5Q1wjBy6gfCLMSyK04WIY5a7cjvzXgTrARGDbuA==";
        };
        _gTjaH8Dm = {
            "id" = "gTjaH8Dm";
            "file" = "Vouchers-1.1.0.jar";
            "hash" = "sha512-EM98hgjE/ko9+o82+fmIS/QuUZqPpv91/qjq6mGaC7mcxJnk5PqDghkRD2B6EVR8ZToPmQHNjjxfYzQxQ73tKA==";
        };
        _1He5haZ0 = {
            "id" = "1He5haZ0";
            "file" = "Vouchers-1.1.1.jar";
            "hash" = "sha512-JybTQba9exJrl2bq38iJdZYb9EVb9l5anLmQnxJy5z6yY3dl98sDQhNHi+pXf/5WPAR+5VSpM0oFaaxFuHzkXA==";
        };
        _QGxscciV = {
            "id" = "QGxscciV";
            "file" = "Vouchers-1.1.2.jar";
            "hash" = "sha512-zAvqHuLXr/cT63MYUpFITQhkwGmrn5fRsvIUPpQTgJZGBz1nb/fhC/H0olggOqkVBdm5e4AHhMV61TlXugvnDQ==";
        };
        _qDTUgdQj = {
            "id" = "qDTUgdQj";
            "file" = "Vouchers-1.1.3.jar";
            "hash" = "sha512-x3IZ7ZzZJlNv7gCwXFpa31dgec9mUc7RA48dnMrrLN0oy+IfeN3q78gLOCuHjxM4Dm4onm+EJbPNGARYQPWfMg==";
        };
    in {
        "ZpnuMn3U" = _ZpnuMn3U;
        "KzlU2wRH" = _KzlU2wRH;
        "VqZbhRgp" = _VqZbhRgp;
        "HmAeD9gg" = _HmAeD9gg;
        "Okyy63xU" = _Okyy63xU;
        "PZcESO7h" = _PZcESO7h;
        "cIvKQVaI" = _cIvKQVaI;
        "claMXMZy" = _claMXMZy;
        "oYtpX7hI" = _oYtpX7hI;
        "IPv1zeyY" = _IPv1zeyY;
        "gTjaH8Dm" = _gTjaH8Dm;
        "1He5haZ0" = _1He5haZ0;
        "QGxscciV" = _QGxscciV;
        "qDTUgdQj" = _qDTUgdQj;
        "bukkit-1.14" = _qDTUgdQj;
        "bukkit-1.14.1" = _qDTUgdQj;
        "bukkit-1.14.2" = _qDTUgdQj;
        "bukkit-1.14.3" = _qDTUgdQj;
        "bukkit-1.14.4" = _qDTUgdQj;
        "bukkit-1.15" = _qDTUgdQj;
        "bukkit-1.15.1" = _qDTUgdQj;
        "bukkit-1.15.2" = _qDTUgdQj;
        "bukkit-1.16" = _qDTUgdQj;
        "bukkit-1.16.1" = _qDTUgdQj;
        "bukkit-1.16.2" = _qDTUgdQj;
        "bukkit-1.16.3" = _qDTUgdQj;
        "bukkit-1.16.4" = _qDTUgdQj;
        "bukkit-1.16.5" = _qDTUgdQj;
        "bukkit-1.17" = _qDTUgdQj;
        "bukkit-1.17.1" = _qDTUgdQj;
        "bukkit-1.18" = _qDTUgdQj;
        "bukkit-1.18.1" = _qDTUgdQj;
        "bukkit-1.18.2" = _qDTUgdQj;
        "bukkit-1.19" = _qDTUgdQj;
        "bukkit-1.19.1" = _qDTUgdQj;
        "bukkit-1.19.2" = _qDTUgdQj;
        "bukkit-1.19.3" = _qDTUgdQj;
        "bukkit-1.19.4" = _qDTUgdQj;
        "bukkit-1.20" = _qDTUgdQj;
        "bukkit-1.20.1" = _qDTUgdQj;
        "bukkit-1.20.2" = _qDTUgdQj;
        "bukkit-1.20.3" = _qDTUgdQj;
        "bukkit-1.20.4" = _qDTUgdQj;
        "bukkit-1.13.2" = _oYtpX7hI;
        "bukkit-1.20.5" = _qDTUgdQj;
        "bukkit-1.20.6" = _qDTUgdQj;
        "bukkit-1.21" = _qDTUgdQj;
        "bukkit-1.21.1" = _qDTUgdQj;
        "bukkit-1.21.2" = _qDTUgdQj;
        "bukkit-1.21.3" = _qDTUgdQj;
        "bukkit-1.21.4" = _qDTUgdQj;
        "paper-1.14" = _qDTUgdQj;
        "paper-1.14.1" = _qDTUgdQj;
        "paper-1.14.2" = _qDTUgdQj;
        "paper-1.14.3" = _qDTUgdQj;
        "paper-1.14.4" = _qDTUgdQj;
        "paper-1.15" = _qDTUgdQj;
        "paper-1.15.1" = _qDTUgdQj;
        "paper-1.15.2" = _qDTUgdQj;
        "paper-1.16" = _qDTUgdQj;
        "paper-1.16.1" = _qDTUgdQj;
        "paper-1.16.2" = _qDTUgdQj;
        "paper-1.16.3" = _qDTUgdQj;
        "paper-1.16.4" = _qDTUgdQj;
        "paper-1.16.5" = _qDTUgdQj;
        "paper-1.17" = _qDTUgdQj;
        "paper-1.17.1" = _qDTUgdQj;
        "paper-1.18" = _qDTUgdQj;
        "paper-1.18.1" = _qDTUgdQj;
        "paper-1.18.2" = _qDTUgdQj;
        "paper-1.19" = _qDTUgdQj;
        "paper-1.19.1" = _qDTUgdQj;
        "paper-1.19.2" = _qDTUgdQj;
        "paper-1.19.3" = _qDTUgdQj;
        "paper-1.19.4" = _qDTUgdQj;
        "paper-1.20" = _qDTUgdQj;
        "paper-1.20.1" = _qDTUgdQj;
        "paper-1.20.2" = _qDTUgdQj;
        "paper-1.20.3" = _qDTUgdQj;
        "paper-1.20.4" = _qDTUgdQj;
        "paper-1.13.2" = _oYtpX7hI;
        "paper-1.20.5" = _qDTUgdQj;
        "paper-1.20.6" = _qDTUgdQj;
        "paper-1.21" = _qDTUgdQj;
        "paper-1.21.1" = _qDTUgdQj;
        "paper-1.21.2" = _qDTUgdQj;
        "paper-1.21.3" = _qDTUgdQj;
        "paper-1.21.4" = _qDTUgdQj;
        "purpur-1.14" = _qDTUgdQj;
        "purpur-1.14.1" = _qDTUgdQj;
        "purpur-1.14.2" = _qDTUgdQj;
        "purpur-1.14.3" = _qDTUgdQj;
        "purpur-1.14.4" = _qDTUgdQj;
        "purpur-1.15" = _qDTUgdQj;
        "purpur-1.15.1" = _qDTUgdQj;
        "purpur-1.15.2" = _qDTUgdQj;
        "purpur-1.16" = _qDTUgdQj;
        "purpur-1.16.1" = _qDTUgdQj;
        "purpur-1.16.2" = _qDTUgdQj;
        "purpur-1.16.3" = _qDTUgdQj;
        "purpur-1.16.4" = _qDTUgdQj;
        "purpur-1.16.5" = _qDTUgdQj;
        "purpur-1.17" = _qDTUgdQj;
        "purpur-1.17.1" = _qDTUgdQj;
        "purpur-1.18" = _qDTUgdQj;
        "purpur-1.18.1" = _qDTUgdQj;
        "purpur-1.18.2" = _qDTUgdQj;
        "purpur-1.19" = _qDTUgdQj;
        "purpur-1.19.1" = _qDTUgdQj;
        "purpur-1.19.2" = _qDTUgdQj;
        "purpur-1.19.3" = _qDTUgdQj;
        "purpur-1.19.4" = _qDTUgdQj;
        "purpur-1.20" = _qDTUgdQj;
        "purpur-1.20.1" = _qDTUgdQj;
        "purpur-1.20.2" = _qDTUgdQj;
        "purpur-1.20.3" = _qDTUgdQj;
        "purpur-1.20.4" = _qDTUgdQj;
        "purpur-1.13.2" = _oYtpX7hI;
        "purpur-1.20.5" = _qDTUgdQj;
        "purpur-1.20.6" = _qDTUgdQj;
        "purpur-1.21" = _qDTUgdQj;
        "purpur-1.21.1" = _qDTUgdQj;
        "purpur-1.21.2" = _qDTUgdQj;
        "purpur-1.21.3" = _qDTUgdQj;
        "purpur-1.21.4" = _qDTUgdQj;
        "spigot-1.14" = _qDTUgdQj;
        "spigot-1.14.1" = _qDTUgdQj;
        "spigot-1.14.2" = _qDTUgdQj;
        "spigot-1.14.3" = _qDTUgdQj;
        "spigot-1.14.4" = _qDTUgdQj;
        "spigot-1.15" = _qDTUgdQj;
        "spigot-1.15.1" = _qDTUgdQj;
        "spigot-1.15.2" = _qDTUgdQj;
        "spigot-1.16" = _qDTUgdQj;
        "spigot-1.16.1" = _qDTUgdQj;
        "spigot-1.16.2" = _qDTUgdQj;
        "spigot-1.16.3" = _qDTUgdQj;
        "spigot-1.16.4" = _qDTUgdQj;
        "spigot-1.16.5" = _qDTUgdQj;
        "spigot-1.17" = _qDTUgdQj;
        "spigot-1.17.1" = _qDTUgdQj;
        "spigot-1.18" = _qDTUgdQj;
        "spigot-1.18.1" = _qDTUgdQj;
        "spigot-1.18.2" = _qDTUgdQj;
        "spigot-1.19" = _qDTUgdQj;
        "spigot-1.19.1" = _qDTUgdQj;
        "spigot-1.19.2" = _qDTUgdQj;
        "spigot-1.19.3" = _qDTUgdQj;
        "spigot-1.19.4" = _qDTUgdQj;
        "spigot-1.20" = _qDTUgdQj;
        "spigot-1.20.1" = _qDTUgdQj;
        "spigot-1.20.2" = _qDTUgdQj;
        "spigot-1.20.3" = _qDTUgdQj;
        "spigot-1.20.4" = _qDTUgdQj;
        "spigot-1.13.2" = _oYtpX7hI;
        "spigot-1.20.5" = _qDTUgdQj;
        "spigot-1.20.6" = _qDTUgdQj;
        "spigot-1.21" = _qDTUgdQj;
        "spigot-1.21.1" = _qDTUgdQj;
        "spigot-1.21.2" = _qDTUgdQj;
        "spigot-1.21.3" = _qDTUgdQj;
        "spigot-1.21.4" = _qDTUgdQj;
    });
    fn = {stdenv, fetchurl, version, ...}:
        lib.prismnix.pkgs.mkVersionedModrinthPkg {
            inherit stdenv fetchurl;
            name = "vouchers";
            id = "aiTY6bBL";
            type = "mod";
            version = version;
            versions = versions;
            meta = {
                license = lib.getLicenseFromSpdxIdOr "GPL-3.0-only" {
                    free = false;
                    deprecated = false;
                    redistributable = false;
                    fullName = "GNU General Public License v3.0 only";
                    shortName = "GPL-3.0-only";
                    url = null;
                };
            };
        };
in callPackage fn {version="qDTUgdQj";}