{lib, callPackage, ...}:
let
    versions = (let
        _y0BtKray = {
            "id" = "y0BtKray";
            "file" = "Enhanced Audio Ambience r1.zip";
            "hash" = "sha512-Q65amRpo4di68ojYYm90zcRoNdGLZ2MyqEkWK6MYBXZWvOAjv9vmN3sOFW9+dp7RyTiS2g1IRQJorPKLgdxMIg==";
        };
        _hrMUh4pK = {
            "id" = "hrMUh4pK";
            "file" = "Enhanced Audio Ambience r2.zip";
            "hash" = "sha512-7VuCTMImeeJ2p0uk86NSfEM6nAv1IYSVD+8U/2DIm7U5fACxAJK4hz9S/S//LyMhhEq/3tDRqTVMIfcWZXTRnA==";
        };
    in {
        "y0BtKray" = _y0BtKray;
        "hrMUh4pK" = _hrMUh4pK;
        "minecraft-1.14" = _hrMUh4pK;
        "minecraft-1.14.1" = _hrMUh4pK;
        "minecraft-1.14.2" = _hrMUh4pK;
        "minecraft-1.14.3" = _hrMUh4pK;
        "minecraft-1.14.4" = _hrMUh4pK;
        "minecraft-1.15" = _hrMUh4pK;
        "minecraft-1.15.1" = _hrMUh4pK;
        "minecraft-1.15.2" = _hrMUh4pK;
        "minecraft-1.16" = _hrMUh4pK;
        "minecraft-1.16.1" = _hrMUh4pK;
        "minecraft-1.16.2" = _hrMUh4pK;
        "minecraft-1.16.3" = _hrMUh4pK;
        "minecraft-1.16.4" = _hrMUh4pK;
        "minecraft-1.16.5" = _hrMUh4pK;
        "minecraft-1.17" = _hrMUh4pK;
        "minecraft-1.17.1" = _hrMUh4pK;
        "minecraft-1.18" = _hrMUh4pK;
        "minecraft-1.18.1" = _hrMUh4pK;
        "minecraft-1.18.2" = _hrMUh4pK;
        "minecraft-1.19" = _hrMUh4pK;
        "minecraft-1.19.1" = _hrMUh4pK;
        "minecraft-1.19.2" = _hrMUh4pK;
        "minecraft-1.19.3" = _hrMUh4pK;
        "minecraft-1.19.4" = _hrMUh4pK;
        "minecraft-1.20" = _hrMUh4pK;
        "minecraft-1.20.1" = _hrMUh4pK;
        "minecraft-1.20.2" = _hrMUh4pK;
        "minecraft-1.20.3" = _hrMUh4pK;
        "minecraft-1.20.4" = _hrMUh4pK;
        "minecraft-1.20.5" = _hrMUh4pK;
        "minecraft-1.20.6" = _hrMUh4pK;
        "minecraft-1.21" = _hrMUh4pK;
        "minecraft-1.21.1" = _hrMUh4pK;
        "minecraft-1.21.2" = _hrMUh4pK;
        "minecraft-1.21.3" = _hrMUh4pK;
        "minecraft-1.21.4" = _hrMUh4pK;
        "minecraft-1.21.5" = _hrMUh4pK;
        "minecraft-1.21.6" = _hrMUh4pK;
        "minecraft-1.21.7" = _hrMUh4pK;
        "minecraft-1.21.8" = _hrMUh4pK;
        "minecraft-1.21.9" = _hrMUh4pK;
        "minecraft-1.21.10" = _hrMUh4pK;
        "minecraft-1.21.11" = _hrMUh4pK;
        "minecraft-26.1" = _hrMUh4pK;
        "minecraft-26.1.1" = _hrMUh4pK;
        "minecraft-23w31a" = _hrMUh4pK;
        "minecraft-23w32a" = _hrMUh4pK;
        "minecraft-23w33a" = _hrMUh4pK;
        "minecraft-23w35a" = _hrMUh4pK;
        "minecraft-1.20.2-pre1" = _hrMUh4pK;
        "minecraft-23w42a" = _hrMUh4pK;
        "minecraft-23w43a" = _hrMUh4pK;
        "minecraft-23w43b" = _hrMUh4pK;
        "minecraft-23w44a" = _hrMUh4pK;
        "minecraft-23w45a" = _hrMUh4pK;
        "minecraft-23w46a" = _hrMUh4pK;
        "minecraft-24w03a" = _hrMUh4pK;
        "minecraft-24w03b" = _hrMUh4pK;
        "minecraft-24w04a" = _hrMUh4pK;
        "minecraft-24w05a" = _hrMUh4pK;
        "minecraft-24w05b" = _hrMUh4pK;
        "minecraft-24w06a" = _hrMUh4pK;
        "minecraft-24w07a" = _hrMUh4pK;
        "minecraft-24w09a" = _hrMUh4pK;
        "minecraft-24w10a" = _hrMUh4pK;
        "minecraft-24w11a" = _hrMUh4pK;
        "minecraft-24w12a" = _hrMUh4pK;
        "minecraft-24w13a" = _hrMUh4pK;
        "minecraft-24w14potato" = _hrMUh4pK;
        "minecraft-24w14a" = _hrMUh4pK;
        "minecraft-1.20.5-pre1" = _hrMUh4pK;
        "minecraft-1.20.5-pre2" = _hrMUh4pK;
        "minecraft-1.20.5-pre3" = _hrMUh4pK;
        "minecraft-24w18a" = _hrMUh4pK;
        "minecraft-24w19a" = _hrMUh4pK;
        "minecraft-24w19b" = _hrMUh4pK;
        "minecraft-24w20a" = _hrMUh4pK;
        "minecraft-24w33a" = _hrMUh4pK;
        "minecraft-24w34a" = _hrMUh4pK;
        "minecraft-24w35a" = _hrMUh4pK;
        "minecraft-24w36a" = _hrMUh4pK;
        "minecraft-24w37a" = _hrMUh4pK;
        "minecraft-24w38a" = _hrMUh4pK;
        "minecraft-24w39a" = _hrMUh4pK;
        "minecraft-24w40a" = _hrMUh4pK;
        "minecraft-1.21.2-pre1" = _hrMUh4pK;
        "minecraft-1.21.2-pre2" = _hrMUh4pK;
        "minecraft-24w44a" = _hrMUh4pK;
        "minecraft-24w45a" = _hrMUh4pK;
        "minecraft-24w46a" = _hrMUh4pK;
        "minecraft-26.1.2" = _hrMUh4pK;
        "minecraft-26.2" = _hrMUh4pK;
        "default" = _hrMUh4pK;
    });
    fn = {stdenv, fetchurl, version, ...}:
        lib.prismnix.pkgs.mkVersionedModrinthPkg {
            inherit stdenv fetchurl;
            name = "enhanced-audio-ambience";
            id = "aMC0BRSF";
            type = "resourcepack";
            version = version;
            versions = versions;
            meta = {
                license = lib.getLicenseFromSpdxIdOr "LicenseRef-All-Rights-Reserved" {
                    free = false;
                    deprecated = false;
                    redistributable = false;
                    fullName = "LicenseRef-All-Rights-Reserved";
                    shortName = "LicenseRef-All-Rights-Reserved";
                    url = null;
                };
            };
        };
in callPackage fn {version="default";}