{lib, callPackage, ...}:
let
    versions = (let
        _uljO1Cgb = {
            "id" = "uljO1Cgb";
            "file" = "Silent Portals v1.0.zip";
            "hash" = "sha512-6C+VZTmOAiy/nUNZmIYBqn0tPpijgCYHTcokKrz9QP1javeYvnniX2fAU+Pv51yuc6sRM7kFvDF5cv87U545KQ==";
        };
        _iJhW5kLI = {
            "id" = "iJhW5kLI";
            "file" = "Silent Portals v1.1.zip";
            "hash" = "sha512-vR1vlH1JhFc/2gdVste67Cw7M9AHV28oQxQdtf8kRZmTO9AWQFaDVgaIqPYOWwSyCSbXArSQtb0VDOyIk8sWcw==";
        };
    in {
        "uljO1Cgb" = _uljO1Cgb;
        "iJhW5kLI" = _iJhW5kLI;
        "minecraft-1.6.1" = _iJhW5kLI;
        "minecraft-1.6.2" = _iJhW5kLI;
        "minecraft-1.6.4" = _iJhW5kLI;
        "minecraft-1.7.2" = _iJhW5kLI;
        "minecraft-1.7.3" = _iJhW5kLI;
        "minecraft-1.7.4" = _iJhW5kLI;
        "minecraft-1.7.5" = _iJhW5kLI;
        "minecraft-1.7.6" = _iJhW5kLI;
        "minecraft-1.7.7" = _iJhW5kLI;
        "minecraft-1.7.8" = _iJhW5kLI;
        "minecraft-1.7.9" = _iJhW5kLI;
        "minecraft-1.7.10" = _iJhW5kLI;
        "minecraft-1.8" = _iJhW5kLI;
        "minecraft-1.8.1" = _iJhW5kLI;
        "minecraft-1.8.2" = _iJhW5kLI;
        "minecraft-1.8.3" = _iJhW5kLI;
        "minecraft-1.8.4" = _iJhW5kLI;
        "minecraft-1.8.5" = _iJhW5kLI;
        "minecraft-1.8.6" = _iJhW5kLI;
        "minecraft-1.8.7" = _iJhW5kLI;
        "minecraft-1.8.8" = _iJhW5kLI;
        "minecraft-1.8.9" = _iJhW5kLI;
        "minecraft-1.9" = _iJhW5kLI;
        "minecraft-1.9.1" = _iJhW5kLI;
        "minecraft-1.9.2" = _iJhW5kLI;
        "minecraft-1.9.3" = _iJhW5kLI;
        "minecraft-1.9.4" = _iJhW5kLI;
        "minecraft-1.10" = _iJhW5kLI;
        "minecraft-1.10.1" = _iJhW5kLI;
        "minecraft-1.10.2" = _iJhW5kLI;
        "minecraft-1.11" = _iJhW5kLI;
        "minecraft-1.11.1" = _iJhW5kLI;
        "minecraft-1.11.2" = _iJhW5kLI;
        "minecraft-1.12" = _iJhW5kLI;
        "minecraft-1.12.1" = _iJhW5kLI;
        "minecraft-1.12.2" = _iJhW5kLI;
        "minecraft-1.13" = _iJhW5kLI;
        "minecraft-1.13.1" = _iJhW5kLI;
        "minecraft-1.13.2" = _iJhW5kLI;
        "minecraft-1.14" = _iJhW5kLI;
        "minecraft-1.14.1" = _iJhW5kLI;
        "minecraft-1.14.2" = _iJhW5kLI;
        "minecraft-1.14.3" = _iJhW5kLI;
        "minecraft-1.14.4" = _iJhW5kLI;
        "minecraft-1.15" = _iJhW5kLI;
        "minecraft-1.15.1" = _iJhW5kLI;
        "minecraft-1.15.2" = _iJhW5kLI;
        "minecraft-1.16" = _iJhW5kLI;
        "minecraft-1.16.1" = _iJhW5kLI;
        "minecraft-1.16.2" = _iJhW5kLI;
        "minecraft-1.16.3" = _iJhW5kLI;
        "minecraft-1.16.4" = _iJhW5kLI;
        "minecraft-1.16.5" = _iJhW5kLI;
        "minecraft-1.17" = _iJhW5kLI;
        "minecraft-1.17.1" = _iJhW5kLI;
        "minecraft-1.18" = _iJhW5kLI;
        "minecraft-1.18.1" = _iJhW5kLI;
        "minecraft-1.18.2" = _iJhW5kLI;
        "minecraft-1.19" = _iJhW5kLI;
        "minecraft-1.19.1" = _iJhW5kLI;
        "minecraft-1.19.2" = _iJhW5kLI;
        "minecraft-1.19.3" = _iJhW5kLI;
        "minecraft-1.19.4" = _iJhW5kLI;
        "minecraft-1.20" = _iJhW5kLI;
        "minecraft-1.20.1" = _iJhW5kLI;
        "minecraft-1.20.2" = _iJhW5kLI;
        "minecraft-1.20.3" = _iJhW5kLI;
        "minecraft-1.20.4" = _iJhW5kLI;
        "minecraft-1.20.5" = _iJhW5kLI;
        "minecraft-1.20.6" = _iJhW5kLI;
        "minecraft-1.21" = _iJhW5kLI;
        "minecraft-1.21.1" = _iJhW5kLI;
        "minecraft-1.21.2" = _iJhW5kLI;
        "minecraft-1.21.3" = _iJhW5kLI;
        "minecraft-1.21.4" = _iJhW5kLI;
        "minecraft-1.21.5" = _iJhW5kLI;
        "minecraft-1.21.6" = _iJhW5kLI;
        "minecraft-1.21.7" = _iJhW5kLI;
        "minecraft-1.21.8" = _iJhW5kLI;
        "minecraft-1.21.9" = _iJhW5kLI;
        "minecraft-1.21.10" = _iJhW5kLI;
        "minecraft-1.21.11" = _iJhW5kLI;
        "minecraft-26.1" = _iJhW5kLI;
        "minecraft-26.1.1" = _iJhW5kLI;
        "minecraft-26.1.2" = _iJhW5kLI;
        "minecraft-26.2" = _iJhW5kLI;
        "default" = _iJhW5kLI;
    });
    fn = {stdenv, fetchurl, version, ...}:
        lib.prismnix.pkgs.mkVersionedModrinthPkg {
            inherit stdenv fetchurl;
            name = "silent-portals";
            id = "DfFblSfP";
            type = "resourcepack";
            version = version;
            versions = versions;
            meta = {
                license = lib.getLicenseFromSpdxIdOr "GPL-3.0-only" {
                    free = false;
                    deprecated = false;
                    redistributable = false;
                    fullName = "GNU General Public License v3.0 only";
                    shortName = "GPL-3.0-only";
                    url = "https://github.com/TheCodingCarson/SilentPortals/blob/main/LICENSE";
                };
            };
        };
in callPackage fn {version="default";}