{lib, callPackage, ...}:
let
    versions = (let
        _VCYUxFk2 = {
            "id" = "VCYUxFk2";
            "file" = "Enchant Plus 1.21 - 1.21.2.zip";
            "hash" = "sha512-SpP3ECYaLI2V7XfB0eyKa+10hwl4U/qckbT0ckNEPERw3lQn8BKWMLXT9B1EiLNpewVgOLsZWe095pJTrqL12g==";
        };
        _GVe0LBTR = {
            "id" = "GVe0LBTR";
            "file" = "Enchant Plus 1.21.3 - 1.21.4.zip";
            "hash" = "sha512-+VGliXWxW9FCqpNrKOo1VkqiS/SsorolnWVnwBBJgSJUhp0z2LtjPXwwQfRWgMcnWuS1+TxoT7+D0FHtcvBKgQ==";
        };
        _ukc9DKGR = {
            "id" = "ukc9DKGR";
            "file" = "Enchant Plus 1.21.5 - 1.21.8.zip";
            "hash" = "sha512-aiJHX5o4fISBUZZHyWz6dsiXt06eC5BMxdsacARCDfOeW7vp4pF+XXcyumDFvRUyn5SyXx3Js/MwFg5yNjredA==";
        };
        _IHkeyUaq = {
            "id" = "IHkeyUaq";
            "file" = "Enchant Plus 1.21.9 - 1.21.10.zip";
            "hash" = "sha512-5L/I6qc27m+d6wAHEywyMqgjFOYRrJPB3DMIRn0+WJoVce/29Sn/OUV+Uvgr2eKDY25T15hr1RWXZo9U4FFTJQ==";
        };
        _zSDkuKg1 = {
            "id" = "zSDkuKg1";
            "file" = "Enchant Plus 1.21.11.zip";
            "hash" = "sha512-072W6SRsGgBvvZ4dc7VpBO4dfDZ6KgUlB/AKSzl1tve32wvn+/CsgN/asMrhRZ4ghgOebLXVAEx7Soqv1y3aVw==";
        };
        _XspJSSD9 = {
            "id" = "XspJSSD9";
            "file" = "Enchant Plus 26.1+.zip";
            "hash" = "sha512-+6nkm0roaEcG52a+00LBsGjR2/XVpT0RizsWQNjUxdpLf8BBkjd/tzVhrkDI1Hruddo354eLNamJyNbXpFkHKA==";
        };
        _rNNAIINp = {
            "id" = "rNNAIINp";
            "file" = "enchant-plus-0.5.jar";
            "hash" = "sha512-Ei7XsJOkHtv1XPUDM8/wsfw/kM+C1HOIeHSz54yvm/wRQaSSQq/jc5txIozcrz5gCLsrcICiMGhr1paeXBkkEA==";
        };
        _QwxuBKqI = {
            "id" = "QwxuBKqI";
            "file" = "enchant-plus-0.5.jar";
            "hash" = "sha512-CvJ4oQUefnQVTASo6BgsD+F4e3X7O9qE1cbW9O9iM+zMlb67VRpBIRpO/kZmFyOAvxDzd1KsKq3IjbCfLmJy0A==";
        };
        _8HAQ4xBA = {
            "id" = "8HAQ4xBA";
            "file" = "enchant-plus-0.5.jar";
            "hash" = "sha512-Ns5ADBS2Go5LsbXybTrSCpDhqUaHLTlzhFEpYC3Wsx6Qwx+2HwDsYJkYYxTQfH49iRS8zdWxCVkDKmU8+TJg/Q==";
        };
        _oBnN97H7 = {
            "id" = "oBnN97H7";
            "file" = "enchant-plus-0.5.jar";
            "hash" = "sha512-8HBAh5JeMvU48bSEJspxOtJXZdm6jsdK4FndvJXLQVCE/csgvohLCV6yTAFNsMOxEF9RO0mFKR+jnSK10c2Wxw==";
        };
        _pEdo9ZRz = {
            "id" = "pEdo9ZRz";
            "file" = "enchant-plus-0.5.jar";
            "hash" = "sha512-G3xUP+sYbs2SQ1hznKq9DJB1ezsLlM5vrcTdAdXSqztFpcgNr6FXhV6rBQ659eRtqylJOg2QsOGtEiidyUmmSQ==";
        };
        _YsxhsVLx = {
            "id" = "YsxhsVLx";
            "file" = "enchant-plus-0.5.jar";
            "hash" = "sha512-avDkyaUOuv4rIfuvh8KFsYxl77dAgmDoLl0pTePQLC0a5WApzSTPgndq/Ieexld1jLv8b5GjPvi4G5KPAFhCtQ==";
        };
    in {
        "VCYUxFk2" = _VCYUxFk2;
        "GVe0LBTR" = _GVe0LBTR;
        "ukc9DKGR" = _ukc9DKGR;
        "IHkeyUaq" = _IHkeyUaq;
        "zSDkuKg1" = _zSDkuKg1;
        "XspJSSD9" = _XspJSSD9;
        "rNNAIINp" = _rNNAIINp;
        "QwxuBKqI" = _QwxuBKqI;
        "8HAQ4xBA" = _8HAQ4xBA;
        "oBnN97H7" = _oBnN97H7;
        "pEdo9ZRz" = _pEdo9ZRz;
        "YsxhsVLx" = _YsxhsVLx;
        "datapack-1.21" = _VCYUxFk2;
        "datapack-1.21.1" = _VCYUxFk2;
        "datapack-1.21.2" = _VCYUxFk2;
        "datapack-1.21.3" = _GVe0LBTR;
        "datapack-1.21.4" = _GVe0LBTR;
        "datapack-1.21.5" = _ukc9DKGR;
        "datapack-1.21.6" = _ukc9DKGR;
        "datapack-1.21.7" = _ukc9DKGR;
        "datapack-1.21.8" = _ukc9DKGR;
        "datapack-1.21.9" = _IHkeyUaq;
        "datapack-1.21.10" = _IHkeyUaq;
        "datapack-1.21.11" = _zSDkuKg1;
        "datapack-26.1" = _XspJSSD9;
        "datapack-26.1.1" = _XspJSSD9;
        "datapack-26.1.2" = _XspJSSD9;
        "datapack-26.2-snapshot-2" = _XspJSSD9;
        "datapack-26.2-snapshot-3" = _XspJSSD9;
        "datapack-26.2-snapshot-4" = _XspJSSD9;
        "datapack-26.2-snapshot-5" = _XspJSSD9;
        "datapack-26.2-snapshot-6" = _XspJSSD9;
        "datapack-26.2-snapshot-7" = _XspJSSD9;
        "datapack-26.2-snapshot-8" = _XspJSSD9;
        "datapack-26.2-pre-1" = _XspJSSD9;
        "datapack-26.2-pre-2" = _XspJSSD9;
        "datapack-26.2-pre-3" = _XspJSSD9;
        "datapack-26.2-pre-4" = _XspJSSD9;
        "datapack-26.2-pre-5" = _XspJSSD9;
        "datapack-26.2-pre-6" = _XspJSSD9;
        "datapack-26.2-rc-1" = _XspJSSD9;
        "datapack-26.2-rc-2" = _XspJSSD9;
        "datapack-26.2" = _XspJSSD9;
        "datapack-26.3-snapshot-1" = _XspJSSD9;
        "datapack-26.3-snapshot-2" = _XspJSSD9;
        "datapack-26.3-snapshot-3" = _XspJSSD9;
        "fabric-1.21" = _rNNAIINp;
        "fabric-1.21.1" = _rNNAIINp;
        "fabric-1.21.2" = _rNNAIINp;
        "fabric-1.21.3" = _QwxuBKqI;
        "fabric-1.21.4" = _QwxuBKqI;
        "fabric-1.21.5" = _8HAQ4xBA;
        "fabric-1.21.6" = _8HAQ4xBA;
        "fabric-1.21.7" = _8HAQ4xBA;
        "fabric-1.21.8" = _8HAQ4xBA;
        "fabric-1.21.9" = _oBnN97H7;
        "fabric-1.21.10" = _oBnN97H7;
        "fabric-1.21.11" = _pEdo9ZRz;
        "fabric-26.1" = _YsxhsVLx;
        "fabric-26.1.1" = _YsxhsVLx;
        "fabric-26.1.2" = _YsxhsVLx;
        "fabric-26.2-snapshot-2" = _YsxhsVLx;
        "fabric-26.2-snapshot-3" = _YsxhsVLx;
        "fabric-26.2-snapshot-4" = _YsxhsVLx;
        "fabric-26.2-snapshot-5" = _YsxhsVLx;
        "fabric-26.2-snapshot-6" = _YsxhsVLx;
        "fabric-26.2-snapshot-7" = _YsxhsVLx;
        "fabric-26.2-snapshot-8" = _YsxhsVLx;
        "fabric-26.2-pre-1" = _YsxhsVLx;
        "fabric-26.2-pre-2" = _YsxhsVLx;
        "fabric-26.2-pre-3" = _YsxhsVLx;
        "fabric-26.2-pre-4" = _YsxhsVLx;
        "fabric-26.2-pre-5" = _YsxhsVLx;
        "fabric-26.2-pre-6" = _YsxhsVLx;
        "fabric-26.2-rc-1" = _YsxhsVLx;
        "fabric-26.2-rc-2" = _YsxhsVLx;
        "fabric-26.2" = _YsxhsVLx;
        "fabric-26.3-snapshot-1" = _YsxhsVLx;
        "fabric-26.3-snapshot-2" = _YsxhsVLx;
        "fabric-26.3-snapshot-3" = _YsxhsVLx;
        "forge-1.21" = _rNNAIINp;
        "forge-1.21.1" = _rNNAIINp;
        "forge-1.21.2" = _rNNAIINp;
        "forge-1.21.3" = _QwxuBKqI;
        "forge-1.21.4" = _QwxuBKqI;
        "forge-1.21.5" = _8HAQ4xBA;
        "forge-1.21.6" = _8HAQ4xBA;
        "forge-1.21.7" = _8HAQ4xBA;
        "forge-1.21.8" = _8HAQ4xBA;
        "forge-1.21.9" = _oBnN97H7;
        "forge-1.21.10" = _oBnN97H7;
        "forge-1.21.11" = _pEdo9ZRz;
        "forge-26.1" = _YsxhsVLx;
        "forge-26.1.1" = _YsxhsVLx;
        "forge-26.1.2" = _YsxhsVLx;
        "forge-26.2-snapshot-2" = _YsxhsVLx;
        "forge-26.2-snapshot-3" = _YsxhsVLx;
        "forge-26.2-snapshot-4" = _YsxhsVLx;
        "forge-26.2-snapshot-5" = _YsxhsVLx;
        "forge-26.2-snapshot-6" = _YsxhsVLx;
        "forge-26.2-snapshot-7" = _YsxhsVLx;
        "forge-26.2-snapshot-8" = _YsxhsVLx;
        "forge-26.2-pre-1" = _YsxhsVLx;
        "forge-26.2-pre-2" = _YsxhsVLx;
        "forge-26.2-pre-3" = _YsxhsVLx;
        "forge-26.2-pre-4" = _YsxhsVLx;
        "forge-26.2-pre-5" = _YsxhsVLx;
        "forge-26.2-pre-6" = _YsxhsVLx;
        "forge-26.2-rc-1" = _YsxhsVLx;
        "forge-26.2-rc-2" = _YsxhsVLx;
        "forge-26.2" = _YsxhsVLx;
        "forge-26.3-snapshot-1" = _YsxhsVLx;
        "forge-26.3-snapshot-2" = _YsxhsVLx;
        "forge-26.3-snapshot-3" = _YsxhsVLx;
        "neoforge-1.21" = _rNNAIINp;
        "neoforge-1.21.1" = _rNNAIINp;
        "neoforge-1.21.2" = _rNNAIINp;
        "neoforge-1.21.3" = _QwxuBKqI;
        "neoforge-1.21.4" = _QwxuBKqI;
        "neoforge-1.21.5" = _8HAQ4xBA;
        "neoforge-1.21.6" = _8HAQ4xBA;
        "neoforge-1.21.7" = _8HAQ4xBA;
        "neoforge-1.21.8" = _8HAQ4xBA;
        "neoforge-1.21.9" = _oBnN97H7;
        "neoforge-1.21.10" = _oBnN97H7;
        "neoforge-1.21.11" = _pEdo9ZRz;
        "neoforge-26.1" = _YsxhsVLx;
        "neoforge-26.1.1" = _YsxhsVLx;
        "neoforge-26.1.2" = _YsxhsVLx;
        "neoforge-26.2-snapshot-2" = _YsxhsVLx;
        "neoforge-26.2-snapshot-3" = _YsxhsVLx;
        "neoforge-26.2-snapshot-4" = _YsxhsVLx;
        "neoforge-26.2-snapshot-5" = _YsxhsVLx;
        "neoforge-26.2-snapshot-6" = _YsxhsVLx;
        "neoforge-26.2-snapshot-7" = _YsxhsVLx;
        "neoforge-26.2-snapshot-8" = _YsxhsVLx;
        "neoforge-26.2-pre-1" = _YsxhsVLx;
        "neoforge-26.2-pre-2" = _YsxhsVLx;
        "neoforge-26.2-pre-3" = _YsxhsVLx;
        "neoforge-26.2-pre-4" = _YsxhsVLx;
        "neoforge-26.2-pre-5" = _YsxhsVLx;
        "neoforge-26.2-pre-6" = _YsxhsVLx;
        "neoforge-26.2-rc-1" = _YsxhsVLx;
        "neoforge-26.2-rc-2" = _YsxhsVLx;
        "neoforge-26.2" = _YsxhsVLx;
        "neoforge-26.3-snapshot-1" = _YsxhsVLx;
        "neoforge-26.3-snapshot-2" = _YsxhsVLx;
        "neoforge-26.3-snapshot-3" = _YsxhsVLx;
        "quilt-1.21" = _rNNAIINp;
        "quilt-1.21.1" = _rNNAIINp;
        "quilt-1.21.2" = _rNNAIINp;
        "quilt-1.21.3" = _QwxuBKqI;
        "quilt-1.21.4" = _QwxuBKqI;
        "quilt-1.21.5" = _8HAQ4xBA;
        "quilt-1.21.6" = _8HAQ4xBA;
        "quilt-1.21.7" = _8HAQ4xBA;
        "quilt-1.21.8" = _8HAQ4xBA;
        "quilt-1.21.9" = _oBnN97H7;
        "quilt-1.21.10" = _oBnN97H7;
        "quilt-1.21.11" = _pEdo9ZRz;
        "quilt-26.1" = _YsxhsVLx;
        "quilt-26.1.1" = _YsxhsVLx;
        "quilt-26.1.2" = _YsxhsVLx;
        "quilt-26.2-snapshot-2" = _YsxhsVLx;
        "quilt-26.2-snapshot-3" = _YsxhsVLx;
        "quilt-26.2-snapshot-4" = _YsxhsVLx;
        "quilt-26.2-snapshot-5" = _YsxhsVLx;
        "quilt-26.2-snapshot-6" = _YsxhsVLx;
        "quilt-26.2-snapshot-7" = _YsxhsVLx;
        "quilt-26.2-snapshot-8" = _YsxhsVLx;
        "quilt-26.2-pre-1" = _YsxhsVLx;
        "quilt-26.2-pre-2" = _YsxhsVLx;
        "quilt-26.2-pre-3" = _YsxhsVLx;
        "quilt-26.2-pre-4" = _YsxhsVLx;
        "quilt-26.2-pre-5" = _YsxhsVLx;
        "quilt-26.2-pre-6" = _YsxhsVLx;
        "quilt-26.2-rc-1" = _YsxhsVLx;
        "quilt-26.2-rc-2" = _YsxhsVLx;
        "quilt-26.2" = _YsxhsVLx;
        "quilt-26.3-snapshot-1" = _YsxhsVLx;
        "quilt-26.3-snapshot-2" = _YsxhsVLx;
        "quilt-26.3-snapshot-3" = _YsxhsVLx;
        "default" = _YsxhsVLx;
    });
    fn = {stdenv, fetchurl, version, ...}:
        lib.prismnix.pkgs.mkVersionedModrinthPkg {
            inherit stdenv fetchurl;
            name = "enchant-plus";
            id = "dQhrtnd5";
            type = "mod";
            version = version;
            versions = versions;
            meta = {
                license = lib.getLicenseFromSpdxIdOr "CC-BY-NC-4.0" {
                    free = false;
                    deprecated = false;
                    redistributable = false;
                    fullName = "Creative Commons Attribution Non Commercial 4.0 International";
                    shortName = "CC-BY-NC-4.0";
                    url = "https://github.com/BibekTheLegend/enchant-plus/blob/main/LICENSE";
                };
            };
        };
in callPackage fn {version="default";}