{lib, callPackage, ...}:
let
    versions = (let
        _MgaVMfak = {
            "id" = "MgaVMfak";
            "file" = "constructionwand-1.0.4+1.21-polymer.jar";
            "hash" = "sha512-p/OwKjCi2gJU8dbichR4kpetXfZa7cw+Zmmdi9YkiQjyaE4+f14tupVTAgPiULZrcKeAFghAdQU+eiFRuiKH2A==";
        };
        _hy9SnwZp = {
            "id" = "hy9SnwZp";
            "file" = "constructionwand-1.0.5+1.21-polymer.jar";
            "hash" = "sha512-V1rYbmIOsX56yAlXoPDz8dmRGYIhbirs8cSbm3BTEYzVgCK9u2ssa3oAF0KfehQJh01SdanM1LJyPrOt7yAnKQ==";
        };
        _P8itZ90U = {
            "id" = "P8itZ90U";
            "file" = "constructionwand-1.0.5+1.21.3-polymer.jar";
            "hash" = "sha512-K7IOkkKLS2jZHx/QRG39ymSQL98Com/6pDF9rluVOgEXQgO2iVS5qPL4e6zW/QYgLiVusS4nOGHD9EQzY+p6EQ==";
        };
        _qBl0ILFp = {
            "id" = "qBl0ILFp";
            "file" = "constructionwandpolymer-1.0.0.jar";
            "hash" = "sha512-6ExijWscQRzxfuOyvu4vsSc4L2H3fNnA6HkOJY/M5f6iEQHyaQ9j3jfmbfog/vqsPXHgLESuhCZsXHVs3WvHpw==";
        };
        _OcFIwZqI = {
            "id" = "OcFIwZqI";
            "file" = "constructionwandpolymer-1.0.1.jar";
            "hash" = "sha512-gQfBG9MZ9jwrh7K4mK5G9Ws4xBplxPepFSJjpBgeME810vzJkzm6cbb3Q4RwoWwFyHhFPCp/RsqP9K0GpP8HIg==";
        };
    in {
        "MgaVMfak" = _MgaVMfak;
        "hy9SnwZp" = _hy9SnwZp;
        "P8itZ90U" = _P8itZ90U;
        "qBl0ILFp" = _qBl0ILFp;
        "OcFIwZqI" = _OcFIwZqI;
        "fabric-1.21" = _qBl0ILFp;
        "fabric-1.21.1" = _qBl0ILFp;
        "fabric-1.21.3" = _qBl0ILFp;
        "fabric-1.0" = _qBl0ILFp;
        "fabric-1.1" = _qBl0ILFp;
        "fabric-1.2.1" = _qBl0ILFp;
        "fabric-1.2.2" = _qBl0ILFp;
        "fabric-1.2.3" = _qBl0ILFp;
        "fabric-1.2.4" = _qBl0ILFp;
        "fabric-1.2.5" = _qBl0ILFp;
        "fabric-1.3.1" = _qBl0ILFp;
        "fabric-1.3.2" = _qBl0ILFp;
        "fabric-1.4.2" = _qBl0ILFp;
        "fabric-1.4.4" = _qBl0ILFp;
        "fabric-1.4.5" = _qBl0ILFp;
        "fabric-1.4.6" = _qBl0ILFp;
        "fabric-1.4.7" = _qBl0ILFp;
        "fabric-1.5.1" = _qBl0ILFp;
        "fabric-1.5.2" = _qBl0ILFp;
        "fabric-1.6.1" = _qBl0ILFp;
        "fabric-1.6.2" = _qBl0ILFp;
        "fabric-1.6.4" = _qBl0ILFp;
        "fabric-1.7.2" = _qBl0ILFp;
        "fabric-1.7.3" = _qBl0ILFp;
        "fabric-1.7.4" = _qBl0ILFp;
        "fabric-1.7.5" = _qBl0ILFp;
        "fabric-1.7.6" = _qBl0ILFp;
        "fabric-1.7.7" = _qBl0ILFp;
        "fabric-1.7.8" = _qBl0ILFp;
        "fabric-1.7.9" = _qBl0ILFp;
        "fabric-1.7.10" = _qBl0ILFp;
        "fabric-1.8" = _qBl0ILFp;
        "fabric-1.8.1" = _qBl0ILFp;
        "fabric-1.8.2" = _qBl0ILFp;
        "fabric-1.8.3" = _qBl0ILFp;
        "fabric-1.8.4" = _qBl0ILFp;
        "fabric-1.8.5" = _qBl0ILFp;
        "fabric-1.8.6" = _qBl0ILFp;
        "fabric-1.8.7" = _qBl0ILFp;
        "fabric-1.8.8" = _qBl0ILFp;
        "fabric-1.8.9" = _qBl0ILFp;
        "fabric-1.9" = _qBl0ILFp;
        "fabric-1.9.1" = _qBl0ILFp;
        "fabric-1.9.2" = _qBl0ILFp;
        "fabric-1.9.3" = _qBl0ILFp;
        "fabric-1.9.4" = _qBl0ILFp;
        "fabric-1.10" = _qBl0ILFp;
        "fabric-1.10.1" = _qBl0ILFp;
        "fabric-1.10.2" = _qBl0ILFp;
        "fabric-1.11" = _qBl0ILFp;
        "fabric-1.11.1" = _qBl0ILFp;
        "fabric-1.11.2" = _qBl0ILFp;
        "fabric-1.12" = _qBl0ILFp;
        "fabric-1.12.1" = _qBl0ILFp;
        "fabric-1.12.2" = _qBl0ILFp;
        "fabric-1.13" = _qBl0ILFp;
        "fabric-1.13.1" = _qBl0ILFp;
        "fabric-1.13.2" = _qBl0ILFp;
        "fabric-1.14" = _qBl0ILFp;
        "fabric-1.14.1" = _qBl0ILFp;
        "fabric-1.14.2" = _qBl0ILFp;
        "fabric-1.14.3" = _qBl0ILFp;
        "fabric-1.14.4" = _qBl0ILFp;
        "fabric-1.15" = _qBl0ILFp;
        "fabric-1.15.1" = _qBl0ILFp;
        "fabric-1.15.2" = _qBl0ILFp;
        "fabric-1.16" = _qBl0ILFp;
        "fabric-1.16.1" = _qBl0ILFp;
        "fabric-1.16.2" = _qBl0ILFp;
        "fabric-1.16.3" = _qBl0ILFp;
        "fabric-1.16.4" = _qBl0ILFp;
        "fabric-1.16.5" = _qBl0ILFp;
        "fabric-1.17" = _qBl0ILFp;
        "fabric-1.17.1" = _qBl0ILFp;
        "fabric-1.18" = _qBl0ILFp;
        "fabric-1.18.1" = _qBl0ILFp;
        "fabric-1.18.2" = _qBl0ILFp;
        "fabric-1.19" = _qBl0ILFp;
        "fabric-1.19.1" = _qBl0ILFp;
        "fabric-1.19.2" = _qBl0ILFp;
        "fabric-1.19.3" = _qBl0ILFp;
        "fabric-1.19.4" = _qBl0ILFp;
        "fabric-1.20" = _qBl0ILFp;
        "fabric-1.20.1" = _qBl0ILFp;
        "fabric-1.20.2" = _qBl0ILFp;
        "fabric-1.20.3" = _qBl0ILFp;
        "fabric-1.20.4" = _qBl0ILFp;
        "fabric-1.20.5" = _qBl0ILFp;
        "fabric-1.20.6" = _qBl0ILFp;
        "fabric-1.21.2" = _qBl0ILFp;
        "fabric-1.21.4" = _qBl0ILFp;
        "fabric-1.21.5" = _qBl0ILFp;
        "fabric-1.21.6" = _qBl0ILFp;
        "fabric-1.21.7" = _qBl0ILFp;
        "fabric-1.21.8" = _qBl0ILFp;
        "fabric-1.21.9" = _qBl0ILFp;
        "fabric-1.21.10" = _qBl0ILFp;
        "fabric-1.21.11" = _qBl0ILFp;
        "fabric-26.1" = _OcFIwZqI;
        "fabric-26.1.1" = _OcFIwZqI;
        "fabric-26.1.2" = _OcFIwZqI;
        "fabric-26.2" = _OcFIwZqI;
        "default" = _OcFIwZqI;
    });
    fn = {stdenv, fetchurl, version, ...}:
        lib.prismnix.pkgs.mkVersionedModrinthPkg {
            inherit stdenv fetchurl;
            name = "construction-wand-polymer";
            id = "EfQ1lKWq";
            type = "mod";
            version = version;
            versions = versions;
            meta = {
                license = lib.getLicenseFromSpdxIdOr "MIT" {
                    free = false;
                    deprecated = false;
                    redistributable = false;
                    fullName = "MIT License";
                    shortName = "MIT";
                    url = null;
                };
            };
        };
in callPackage fn {version="default";}