{lib, callPackage, ...}:
let
    versions = (let
        _lYxqpYtV = {
            "id" = "lYxqpYtV";
            "file" = "HideAndSeek-1.0.0.jar";
            "hash" = "sha512-1VpnpYOz2CEK/Lzoxj86vXFUNf2jo4PolC9k87Fvd564ifEF33O+4Qtmmf9NMr0OThu38Wbr0OIwi24orPZJWg==";
        };
        _FL0gJbQN = {
            "id" = "FL0gJbQN";
            "file" = "HideAndSeek-1.1.0.jar";
            "hash" = "sha512-VULhOHBIdnsxrKHl/u2thNOWIeq51fm1ad/8NwjfJ8KAONi+HJG/Jat74AJi8kV1h9mjjd2DaV73Tf3yhCvPUQ==";
        };
        _vp3mAc0x = {
            "id" = "vp3mAc0x";
            "file" = "HideAndSeek-1.1.2.jar";
            "hash" = "sha512-IPh8pvHPCeAoN8AvEd/rifP0z0BcaUn5AV2r+rgXRH/j1AgfdvDslmBYlCPHEe6RaYr8w+9Fffy4yFdLP4lCwQ==";
        };
        _wpw07qZV = {
            "id" = "wpw07qZV";
            "file" = "HideAndSeek-1.2.0.jar";
            "hash" = "sha512-6dFg9TqDK9QsJRg/lQq1L0gDsJ5WjJHvd/5kSBClSzQ6ZOIJtcVHS/J/bO0InkDAGdwjvmPkCwtY7hoegl2kIQ==";
        };
        _MtW7YEHY = {
            "id" = "MtW7YEHY";
            "file" = "HideAndSeek-1.3.0.jar";
            "hash" = "sha512-uhhsFFzygUfeWDwdTluyIeq/h9m06YFmQFMtFnN/7NdWZG9p6XunVojyTV/e/lCN5Z04YiS/7sdQeSNnbgj7zQ==";
        };
        _fvyMigxl = {
            "id" = "fvyMigxl";
            "file" = "HideAndSeek-1.3.1.jar";
            "hash" = "sha512-qRa4Ia3XhqRtSDD819K6a3XWoz7kHxwC+iyO0d/GrIzY/cixvES6RSa1jBHg5afqPWkjSLN1ZPQmhCNLeP0tYg==";
        };
        _gJnauXo1 = {
            "id" = "gJnauXo1";
            "file" = "HideAndSeek-1.3.2.jar";
            "hash" = "sha512-YKbvLYe2UkzrTvNswRRdXsELC302UAIuwadNhyEzuwtFMFzEiP3Qu8WbGNaRaf2ClT4tjNlqOFX32FHt0PQpUQ==";
        };
        _E7QFTHZU = {
            "id" = "E7QFTHZU";
            "file" = "HideAndSeek-1.3.3.jar";
            "hash" = "sha512-JiXfySzzNWGmSQqvj2Z+s5O/pBgx7J2hHpu5FRkToOU9dpMRbu9kRGmJvs+15QKXcNtAHLgfWhsvCanOlVty/w==";
        };
        _madNumoz = {
            "id" = "madNumoz";
            "file" = "HideAndSeek-1.4.0.jar";
            "hash" = "sha512-g6rjIK4GFE1C+taCk7Me4vBOXQ1QK5N43KV2D0SJy7LBNzNHYF4GY11ANSYCGZgNctCX6V5WdeeX2EMcjSnuTA==";
        };
        _QLvSR21e = {
            "id" = "QLvSR21e";
            "file" = "HideAndSeek-1.4.1.jar";
            "hash" = "sha512-EaZFQbjo1cxFyeQ0xUK4laWgj1YhuLVx25XU6mUoa7JsJImPHDVVOKSmQOh160pI8k7R6XwZM1TXzA6w6YBpcQ==";
        };
        _ug9bB3JF = {
            "id" = "ug9bB3JF";
            "file" = "HideAndSeek-1.4.2.jar";
            "hash" = "sha512-PmkGv8TWWo3nb9gw94AkaVCRabSntMlXHDKkfwjecmX5b2Am8BcB4jk1W+PH7ZkLRqKdGUconfAV63zjhf+uPg==";
        };
        _i2m05uPe = {
            "id" = "i2m05uPe";
            "file" = "KenshinsHideAndSeek-1.5.0.jar";
            "hash" = "sha512-rAEnwrKaJ0rbhsei6AA5pkLPpikvc/WioAlEMm6hZmg1ColqFMV2L63XQGmNGb3tPRrD1wwnG/Sx4k9lt70C7Q==";
        };
        _RNGrvD9S = {
            "id" = "RNGrvD9S";
            "file" = "KenshinsHideAndSeek-1.5.1.jar";
            "hash" = "sha512-p/eYsHNFN8V34epzVdoUvST0uDOdd7PnKU19DjQQBQCXg6BetO0eYexHFI8H0Uvdez+sQzZ9Yay+WP6CrTkrcw==";
        };
        _yDYasvmy = {
            "id" = "yDYasvmy";
            "file" = "KenshinsHideAndSeek-1.6.0.jar";
            "hash" = "sha512-BFwnepus7Q/4T0holoazH2DayZtp8pcxHYA2b+ch5la7ZuvATCtrxlWFTaDq5QR14U3ygZ/NVgvZDily/S/liQ==";
        };
        _bJegbuNh = {
            "id" = "bJegbuNh";
            "file" = "KenshinsHideAndSeek-1.6.1.jar";
            "hash" = "sha512-FM0hBQ4lIG+Xksx3P4KX9nXVPK/SdaGMpn4QLO+uOrIR000KU6X/gEvmh3HRKLZl5k++uT32jysh9jKccPMhGw==";
        };
        _uF270dzn = {
            "id" = "uF270dzn";
            "file" = "KenshinsHideAndSeek-1.6.2.jar";
            "hash" = "sha512-o4E681lJFvyQMpVyEWBx4MhJ/2MR5Orxtso3nkggkrMz+wKlrCKjcYjTo59SJcGQUvHox+recrDSHXwbaxLAmw==";
        };
        _Hx2yVXJV = {
            "id" = "Hx2yVXJV";
            "file" = "KenshinsHideAndSeek-1.7.0.jar";
            "hash" = "sha512-nVBqZySLARVXvoLWlIjD5jtdvbZcXkrjbPRdQBe6Etn6SRiBAKRRug/BpOziCmWTKDt3tg/RzQpoJZwKRpQEyQ==";
        };
        _HDWF7Yhq = {
            "id" = "HDWF7Yhq";
            "file" = "KenshinsHideAndSeek-1.7.1.jar";
            "hash" = "sha512-+KYhc1MLU4c2K8wdvbxDop5+aUGf3W7oybfXZMqavF0y+aTX+9iF1UKcdQe3XmKUhAnsgANXk03thtD3PEy+qw==";
        };
        _8DNu4wba = {
            "id" = "8DNu4wba";
            "file" = "KenshinsHideAndSeek-1.7.2.jar";
            "hash" = "sha512-LL0Jni6cpDoyHY/IZKCCrY+5xrFEV2lPM8QTIPy3p3QzNNNhrssOQAVmWm+QAGW71ufuR/87hlW3PJ0uCEm9yQ==";
        };
        _LfelDaHB = {
            "id" = "LfelDaHB";
            "file" = "KenshinsHideAndSeek-1.7.3.jar";
            "hash" = "sha512-ptha6e7ONe4BDtNWP4x1gzr7PGmpwNIbNnGSgZ9W6mfiz+C1idy/Tnjet8gbHI00Hdi4/qGQ1QAFHOg/unOM7A==";
        };
        _IpsCe4Xw = {
            "id" = "IpsCe4Xw";
            "file" = "KenshinsHideAndSeek-1.7.4.jar";
            "hash" = "sha512-mD4mq5KzUANEIrDc4RpaTTf+ihoqv3i18eI3WIuROAhUkmVhkAFtmwXw9+7gdFLSdytsn3q7PUL5CMyMuF/JeQ==";
        };
        _oOHP1qI7 = {
            "id" = "oOHP1qI7";
            "file" = "KenshinsHideAndSeek-1.7.5.jar";
            "hash" = "sha512-zNZgGLu9tTM0kZw0x2STWq6G/T3OK+j7jQjk77VqNLYSTIRZpZ2wm2rPLNxX9p5o5XW6IHXrwgKVBsoD/mZMZQ==";
        };
        _se7wS5Ck = {
            "id" = "se7wS5Ck";
            "file" = "KenshinsHideAndSeek-1.7.6.jar";
            "hash" = "sha512-BDCaNqlGjq4Kqrep2Zdz8Ipszr2mtL/3VNKdx9Hk9tjETK9jSX8fx1J6ZlhqeqaVo5lU2Xic70KA+GLInWFK4g==";
        };
        _HpPqGdg7 = {
            "id" = "HpPqGdg7";
            "file" = "KenshinsHideAndSeek-2.0.0-alpha1.jar";
            "hash" = "sha512-Gcjat90GiwEnIj7LaqWdr5MdX1GZ/CNTFBA4tMOf80TUdTXwXa598uLHieFPiYqNRTs5OR0EZd1nol/tYOJHdw==";
        };
        _3LSgPD0M = {
            "id" = "3LSgPD0M";
            "file" = "KenshinsHideAndSeek-2.0.0-alpha2.jar";
            "hash" = "sha512-CM07g58Y2qlo1VAY3dSEDgoDxEGWmYEuBybuYt+9cXRD0nfeH9hKLX7qGdCdL+rEquwZZqqGu1oP1jbEW5wJBw==";
        };
        _BoX4w2W3 = {
            "id" = "BoX4w2W3";
            "file" = "KenshinsHideAndSeek-2.0.0-alpha3.jar";
            "hash" = "sha512-s+PAkGrb/3CjMrYCeQMl/tNLNzAF1Q0dYqDY8hdCu6P3QpPTdf2hOhWwO7mSo4Vu3mOKlFoM00H0NiG0YMxjUw==";
        };
        _VnRnRs8m = {
            "id" = "VnRnRs8m";
            "file" = "KenshinsHideAndSeek-2.0.0.jar";
            "hash" = "sha512-86YL2lmxpAF5FrknyCKsPkQHFEy75KfgeQ0VCv0i9SFf0R8OPzzZnsprOj23ge5ZU38Vfti2nmWkkktLQcABZw==";
        };
        _xESA2U8z = {
            "id" = "xESA2U8z";
            "file" = "KenshinsHideAndSeek-2.0.1.jar";
            "hash" = "sha512-2/xMXj16yrFkYDSZLGjKnsgUk0PAypDTXm6eehaqApDGbMtYOjoPylQEbvQYP8s0Txg70GLTx5zcg1lmZa0JTg==";
        };
        _ZBDMWnwC = {
            "id" = "ZBDMWnwC";
            "file" = "KenshinsHideAndSeek-2.0.2.jar";
            "hash" = "sha512-ROWEDrx4Ghfc/nKYtRv36dEWrlvsWzpQm1R06FMoOalpTXqcIzI2wQwuDMtrWriQGo6m+s5LjxlPb303OOpd7Q==";
        };
        _kytWiOwi = {
            "id" = "kytWiOwi";
            "file" = "KenshinsHideAndSeek-2.1.0+bukkit.jar";
            "hash" = "sha512-GCkBK7gEpuwpqqlvlv6WEG3oM2Xx7CvarS53gh/loJSyKdAVPDimYi7mbFx49mnGhsWqJrOYZ6RjCgk0a7v+YQ==";
        };
        _yJ2UxLr7 = {
            "id" = "yJ2UxLr7";
            "file" = "KenshinsHideAndSeek-2.1.1+bukkit.jar";
            "hash" = "sha512-GMNC1MJQNzHInRvJOSaTO+r3wOKISyl5Kb7b5OPrTdmx7hD9ukQkbIJZTXFkar/NvxlDgp81JfJeJ+11ajDnlA==";
        };
        _FQRcJzTU = {
            "id" = "FQRcJzTU";
            "file" = "KenshinsHideAndSeek-2.1.2+bukkit.jar";
            "hash" = "sha512-htTnego7DkOiD7Vlw+2bbmj6CDILx/nI53Fcw7TP+WKqj18MGkgzRBqKQcpr7auXcwEUsmPaUrqkUwSLvfO1WQ==";
        };
        _lTcuTNdF = {
            "id" = "lTcuTNdF";
            "file" = "KenshinsHideAndSeek-2.2.0+bukkit.jar";
            "hash" = "sha512-niFtG0DgfLvqB+G3616Shi3EYj4Ro0zBfWQiVW69YIbGlj6M48KWATrMVzUiZe017hThfIwv5vdy1776QeixRQ==";
        };
    in {
        "lYxqpYtV" = _lYxqpYtV;
        "FL0gJbQN" = _FL0gJbQN;
        "vp3mAc0x" = _vp3mAc0x;
        "wpw07qZV" = _wpw07qZV;
        "MtW7YEHY" = _MtW7YEHY;
        "fvyMigxl" = _fvyMigxl;
        "gJnauXo1" = _gJnauXo1;
        "E7QFTHZU" = _E7QFTHZU;
        "madNumoz" = _madNumoz;
        "QLvSR21e" = _QLvSR21e;
        "ug9bB3JF" = _ug9bB3JF;
        "i2m05uPe" = _i2m05uPe;
        "RNGrvD9S" = _RNGrvD9S;
        "yDYasvmy" = _yDYasvmy;
        "bJegbuNh" = _bJegbuNh;
        "uF270dzn" = _uF270dzn;
        "Hx2yVXJV" = _Hx2yVXJV;
        "HDWF7Yhq" = _HDWF7Yhq;
        "8DNu4wba" = _8DNu4wba;
        "LfelDaHB" = _LfelDaHB;
        "IpsCe4Xw" = _IpsCe4Xw;
        "oOHP1qI7" = _oOHP1qI7;
        "se7wS5Ck" = _se7wS5Ck;
        "HpPqGdg7" = _HpPqGdg7;
        "3LSgPD0M" = _3LSgPD0M;
        "BoX4w2W3" = _BoX4w2W3;
        "VnRnRs8m" = _VnRnRs8m;
        "xESA2U8z" = _xESA2U8z;
        "ZBDMWnwC" = _ZBDMWnwC;
        "kytWiOwi" = _kytWiOwi;
        "yJ2UxLr7" = _yJ2UxLr7;
        "FQRcJzTU" = _FQRcJzTU;
        "lTcuTNdF" = _lTcuTNdF;
        "bukkit-1.17" = _lTcuTNdF;
        "bukkit-1.17.1" = _lTcuTNdF;
        "bukkit-1.18" = _lTcuTNdF;
        "bukkit-1.18.1" = _lTcuTNdF;
        "bukkit-1.18.2" = _lTcuTNdF;
        "bukkit-1.14" = _lTcuTNdF;
        "bukkit-1.14.1" = _lTcuTNdF;
        "bukkit-1.14.2" = _lTcuTNdF;
        "bukkit-1.14.3" = _lTcuTNdF;
        "bukkit-1.14.4" = _lTcuTNdF;
        "bukkit-1.15" = _lTcuTNdF;
        "bukkit-1.15.1" = _lTcuTNdF;
        "bukkit-1.15.2" = _lTcuTNdF;
        "bukkit-1.16" = _lTcuTNdF;
        "bukkit-1.16.1" = _lTcuTNdF;
        "bukkit-1.16.2" = _lTcuTNdF;
        "bukkit-1.16.3" = _lTcuTNdF;
        "bukkit-1.16.4" = _lTcuTNdF;
        "bukkit-1.16.5" = _lTcuTNdF;
        "bukkit-1.8" = _lTcuTNdF;
        "bukkit-1.8.1" = _lTcuTNdF;
        "bukkit-1.8.2" = _lTcuTNdF;
        "bukkit-1.8.3" = _lTcuTNdF;
        "bukkit-1.8.4" = _lTcuTNdF;
        "bukkit-1.8.5" = _lTcuTNdF;
        "bukkit-1.8.6" = _lTcuTNdF;
        "bukkit-1.8.7" = _lTcuTNdF;
        "bukkit-1.8.8" = _lTcuTNdF;
        "bukkit-1.8.9" = _lTcuTNdF;
        "bukkit-1.9" = _lTcuTNdF;
        "bukkit-1.9.1" = _lTcuTNdF;
        "bukkit-1.9.2" = _lTcuTNdF;
        "bukkit-1.9.3" = _lTcuTNdF;
        "bukkit-1.9.4" = _lTcuTNdF;
        "bukkit-1.10" = _lTcuTNdF;
        "bukkit-1.10.1" = _lTcuTNdF;
        "bukkit-1.10.2" = _lTcuTNdF;
        "bukkit-1.11" = _lTcuTNdF;
        "bukkit-1.11.1" = _lTcuTNdF;
        "bukkit-1.11.2" = _lTcuTNdF;
        "bukkit-1.12" = _lTcuTNdF;
        "bukkit-1.12.1" = _lTcuTNdF;
        "bukkit-1.12.2" = _lTcuTNdF;
        "bukkit-1.13" = _lTcuTNdF;
        "bukkit-1.13.1" = _lTcuTNdF;
        "bukkit-1.13.2" = _lTcuTNdF;
        "bukkit-1.19" = _lTcuTNdF;
        "bukkit-1.19.1" = _lTcuTNdF;
        "bukkit-1.19.2" = _lTcuTNdF;
        "bukkit-1.19.3" = _lTcuTNdF;
        "bukkit-1.19.4" = _lTcuTNdF;
        "bukkit-1.20" = _lTcuTNdF;
        "bukkit-1.20.1" = _lTcuTNdF;
        "bukkit-1.20.2" = _lTcuTNdF;
        "bukkit-1.20.3" = _lTcuTNdF;
        "bukkit-1.20.4" = _lTcuTNdF;
        "bukkit-1.20.5" = _lTcuTNdF;
        "bukkit-1.20.6" = _lTcuTNdF;
        "bukkit-1.21" = _lTcuTNdF;
        "bukkit-1.21.1" = _lTcuTNdF;
        "bukkit-1.21.2" = _lTcuTNdF;
        "bukkit-1.21.3" = _lTcuTNdF;
        "bukkit-1.21.4" = _lTcuTNdF;
        "bukkit-1.21.5" = _lTcuTNdF;
        "bukkit-1.21.6" = _lTcuTNdF;
        "bukkit-1.21.7" = _lTcuTNdF;
        "bukkit-1.21.8" = _lTcuTNdF;
        "bukkit-1.21.9" = _lTcuTNdF;
        "bukkit-1.21.10" = _lTcuTNdF;
        "bukkit-1.21.11" = _lTcuTNdF;
        "bukkit-26.1" = _lTcuTNdF;
        "bukkit-26.1.1" = _lTcuTNdF;
        "bukkit-26.1.2" = _lTcuTNdF;
        "bukkit-26.2" = _lTcuTNdF;
        "paper-1.17" = _lTcuTNdF;
        "paper-1.17.1" = _lTcuTNdF;
        "paper-1.18" = _lTcuTNdF;
        "paper-1.18.1" = _lTcuTNdF;
        "paper-1.18.2" = _lTcuTNdF;
        "paper-1.14" = _lTcuTNdF;
        "paper-1.14.1" = _lTcuTNdF;
        "paper-1.14.2" = _lTcuTNdF;
        "paper-1.14.3" = _lTcuTNdF;
        "paper-1.14.4" = _lTcuTNdF;
        "paper-1.15" = _lTcuTNdF;
        "paper-1.15.1" = _lTcuTNdF;
        "paper-1.15.2" = _lTcuTNdF;
        "paper-1.16" = _lTcuTNdF;
        "paper-1.16.1" = _lTcuTNdF;
        "paper-1.16.2" = _lTcuTNdF;
        "paper-1.16.3" = _lTcuTNdF;
        "paper-1.16.4" = _lTcuTNdF;
        "paper-1.16.5" = _lTcuTNdF;
        "paper-1.8" = _lTcuTNdF;
        "paper-1.8.1" = _lTcuTNdF;
        "paper-1.8.2" = _lTcuTNdF;
        "paper-1.8.3" = _lTcuTNdF;
        "paper-1.8.4" = _lTcuTNdF;
        "paper-1.8.5" = _lTcuTNdF;
        "paper-1.8.6" = _lTcuTNdF;
        "paper-1.8.7" = _lTcuTNdF;
        "paper-1.8.8" = _lTcuTNdF;
        "paper-1.8.9" = _lTcuTNdF;
        "paper-1.9" = _lTcuTNdF;
        "paper-1.9.1" = _lTcuTNdF;
        "paper-1.9.2" = _lTcuTNdF;
        "paper-1.9.3" = _lTcuTNdF;
        "paper-1.9.4" = _lTcuTNdF;
        "paper-1.10" = _lTcuTNdF;
        "paper-1.10.1" = _lTcuTNdF;
        "paper-1.10.2" = _lTcuTNdF;
        "paper-1.11" = _lTcuTNdF;
        "paper-1.11.1" = _lTcuTNdF;
        "paper-1.11.2" = _lTcuTNdF;
        "paper-1.12" = _lTcuTNdF;
        "paper-1.12.1" = _lTcuTNdF;
        "paper-1.12.2" = _lTcuTNdF;
        "paper-1.13" = _lTcuTNdF;
        "paper-1.13.1" = _lTcuTNdF;
        "paper-1.13.2" = _lTcuTNdF;
        "paper-1.19" = _lTcuTNdF;
        "paper-1.19.1" = _lTcuTNdF;
        "paper-1.19.2" = _lTcuTNdF;
        "paper-1.19.3" = _lTcuTNdF;
        "paper-1.19.4" = _lTcuTNdF;
        "paper-1.20" = _lTcuTNdF;
        "paper-1.20.1" = _lTcuTNdF;
        "paper-1.20.2" = _lTcuTNdF;
        "paper-1.20.3" = _lTcuTNdF;
        "paper-1.20.4" = _lTcuTNdF;
        "paper-1.20.5" = _lTcuTNdF;
        "paper-1.20.6" = _lTcuTNdF;
        "paper-1.21" = _lTcuTNdF;
        "paper-1.21.1" = _lTcuTNdF;
        "paper-1.21.2" = _lTcuTNdF;
        "paper-1.21.3" = _lTcuTNdF;
        "paper-1.21.4" = _lTcuTNdF;
        "paper-1.21.5" = _lTcuTNdF;
        "paper-1.21.6" = _lTcuTNdF;
        "paper-1.21.7" = _lTcuTNdF;
        "paper-1.21.8" = _lTcuTNdF;
        "paper-1.21.9" = _lTcuTNdF;
        "paper-1.21.10" = _lTcuTNdF;
        "paper-1.21.11" = _lTcuTNdF;
        "paper-26.1" = _lTcuTNdF;
        "paper-26.1.1" = _lTcuTNdF;
        "paper-26.1.2" = _lTcuTNdF;
        "paper-26.2" = _lTcuTNdF;
        "spigot-1.17" = _lTcuTNdF;
        "spigot-1.17.1" = _lTcuTNdF;
        "spigot-1.18" = _lTcuTNdF;
        "spigot-1.18.1" = _lTcuTNdF;
        "spigot-1.18.2" = _lTcuTNdF;
        "spigot-1.14" = _lTcuTNdF;
        "spigot-1.14.1" = _lTcuTNdF;
        "spigot-1.14.2" = _lTcuTNdF;
        "spigot-1.14.3" = _lTcuTNdF;
        "spigot-1.14.4" = _lTcuTNdF;
        "spigot-1.15" = _lTcuTNdF;
        "spigot-1.15.1" = _lTcuTNdF;
        "spigot-1.15.2" = _lTcuTNdF;
        "spigot-1.16" = _lTcuTNdF;
        "spigot-1.16.1" = _lTcuTNdF;
        "spigot-1.16.2" = _lTcuTNdF;
        "spigot-1.16.3" = _lTcuTNdF;
        "spigot-1.16.4" = _lTcuTNdF;
        "spigot-1.16.5" = _lTcuTNdF;
        "spigot-1.8" = _lTcuTNdF;
        "spigot-1.8.1" = _lTcuTNdF;
        "spigot-1.8.2" = _lTcuTNdF;
        "spigot-1.8.3" = _lTcuTNdF;
        "spigot-1.8.4" = _lTcuTNdF;
        "spigot-1.8.5" = _lTcuTNdF;
        "spigot-1.8.6" = _lTcuTNdF;
        "spigot-1.8.7" = _lTcuTNdF;
        "spigot-1.8.8" = _lTcuTNdF;
        "spigot-1.8.9" = _lTcuTNdF;
        "spigot-1.9" = _lTcuTNdF;
        "spigot-1.9.1" = _lTcuTNdF;
        "spigot-1.9.2" = _lTcuTNdF;
        "spigot-1.9.3" = _lTcuTNdF;
        "spigot-1.9.4" = _lTcuTNdF;
        "spigot-1.10" = _lTcuTNdF;
        "spigot-1.10.1" = _lTcuTNdF;
        "spigot-1.10.2" = _lTcuTNdF;
        "spigot-1.11" = _lTcuTNdF;
        "spigot-1.11.1" = _lTcuTNdF;
        "spigot-1.11.2" = _lTcuTNdF;
        "spigot-1.12" = _lTcuTNdF;
        "spigot-1.12.1" = _lTcuTNdF;
        "spigot-1.12.2" = _lTcuTNdF;
        "spigot-1.13" = _lTcuTNdF;
        "spigot-1.13.1" = _lTcuTNdF;
        "spigot-1.13.2" = _lTcuTNdF;
        "spigot-1.19" = _lTcuTNdF;
        "spigot-1.19.1" = _lTcuTNdF;
        "spigot-1.19.2" = _lTcuTNdF;
        "spigot-1.19.3" = _lTcuTNdF;
        "spigot-1.19.4" = _lTcuTNdF;
        "spigot-1.20" = _lTcuTNdF;
        "spigot-1.20.1" = _lTcuTNdF;
        "spigot-1.20.2" = _lTcuTNdF;
        "spigot-1.20.3" = _lTcuTNdF;
        "spigot-1.20.4" = _lTcuTNdF;
        "spigot-1.20.5" = _lTcuTNdF;
        "spigot-1.20.6" = _lTcuTNdF;
        "spigot-1.21" = _lTcuTNdF;
        "spigot-1.21.1" = _lTcuTNdF;
        "spigot-1.21.2" = _lTcuTNdF;
        "spigot-1.21.3" = _lTcuTNdF;
        "spigot-1.21.4" = _lTcuTNdF;
        "spigot-1.21.5" = _lTcuTNdF;
        "spigot-1.21.6" = _lTcuTNdF;
        "spigot-1.21.7" = _lTcuTNdF;
        "spigot-1.21.8" = _lTcuTNdF;
        "spigot-1.21.9" = _lTcuTNdF;
        "spigot-1.21.10" = _lTcuTNdF;
        "spigot-1.21.11" = _lTcuTNdF;
        "spigot-26.1" = _lTcuTNdF;
        "spigot-26.1.1" = _lTcuTNdF;
        "spigot-26.1.2" = _lTcuTNdF;
        "spigot-26.2" = _lTcuTNdF;
        "default" = _lTcuTNdF;
    });
    fn = {stdenv, fetchurl, version, ...}:
        lib.prismnix.pkgs.mkVersionedModrinthPkg {
            inherit stdenv fetchurl;
            name = "kenshins-hide-and-seek";
            id = "FJb0qrsn";
            type = "mod";
            version = version;
            versions = versions;
            meta = {
                license = lib.getLicenseFromSpdxIdOr "GPL-3.0-only" {
                    free = false;
                    deprecated = false;
                    redistributable = false;
                    fullName = "GNU General Public License v3.0 only";
                    shortName = "GPL-3.0-only";
                    url = null;
                };
            };
        };
in callPackage fn {version="default";}