{lib, callPackage, ...}:
let
    versions = (let
        _9RYfxKZG = {
            "id" = "9RYfxKZG";
            "file" = "Clean HUD.zip";
            "hash" = "sha512-me/mWlO1AOP1+yZujeFgtiexM1Yg6N9f8jbc4akKzVQKevk5CJTDzgy/zLMCKi8r3FSr0hSaB4fw+yEA0hwhcg==";
        };
        _ytmBRueT = {
            "id" = "ytmBRueT";
            "file" = "Clean HUD.zip";
            "hash" = "sha512-cjEzO+CQO7ip3YVPmroCjlC14qtW5p5IzSCyD4Xt0z79/aAx/QS6przBetJ+Mo9JRiMXgWr30uZoCgHZ0QHR9Q==";
        };
        _GBUmJVuc = {
            "id" = "GBUmJVuc";
            "file" = "Clean HUD.zip";
            "hash" = "sha512-hMO7eWYXbC5jCEDNFzAmNnnBjcaOn5jogh368E3CBsSnLPuVxI4SYgL/lqVYgyxvKKiKE47ARHS0I8bJTHREhA==";
        };
        _9BJuNIgR = {
            "id" = "9BJuNIgR";
            "file" = "Clean HUD Legacy.zip";
            "hash" = "sha512-g7WJIaJnXhAsm4OW92C5czsd0+5kgyn0+inDw6RU72DWB67MZEKnkLtR6Om2WPvXKTcyjEcrSLAd3JciWD5DFA==";
        };
        _rK5D76ud = {
            "id" = "rK5D76ud";
            "file" = "Clean HUD Legacy.zip";
            "hash" = "sha512-DL/BUl24mX6l9lVPNnSBqmfBPvId+WBNx/6BZURCrG3iyKEVAGIRDe81pr3Hb6s43Tjpc3mpPF6Y77G9gqY+jQ==";
        };
        _dLm3EkQG = {
            "id" = "dLm3EkQG";
            "file" = "Clean HUD.zip";
            "hash" = "sha512-I59T9pnRVMxqY89pZ0KuKPkNfH1OtVHPaZYIAgcwnZk7yytR7X3Gg1M28bUv54dd+BMZxBKB5VrZOlJqVN6fVg==";
        };
        _v9RxB4fo = {
            "id" = "v9RxB4fo";
            "file" = "Clean HUD.zip";
            "hash" = "sha512-c9Ioh2hIqxOGfbqCaCIXsNNR9x4Fdvk4+NmfKTxnWgwUIUJQdZ6Klq3rbANC129g9bBcM1kzZ/CA5hlFJl1+ig==";
        };
        _UpOiNL7o = {
            "id" = "UpOiNL7o";
            "file" = "Clean Hud.zip";
            "hash" = "sha512-hUcIwrQAaRXeB/dvvRSZEmw41uyrKlJbEkvP6TFqMlcAXrNTu7RHvtjmjWZ/X+X7ovLd/+88+I3wdAivHnsdWw==";
        };
        _Q2IFIhlT = {
            "id" = "Q2IFIhlT";
            "file" = "Clean Hud 1.6.1-1.8.9-v2.zip";
            "hash" = "sha512-t4YZlJXGBZc12+aY5RGzPSSqORaEKshqSgoWB6yZTgMKN+gu4DTcqQz8+3m14CslvI3zrYACft/LBv0kaB8m4A==";
        };
        _qOvFunQi = {
            "id" = "qOvFunQi";
            "file" = "Clean Hud 1.9-1.10.2-v2.zip";
            "hash" = "sha512-NsPzRwxqS4KljYRLT0mV0OCX8Yy8eCafYbK6Px6SCTOPTOhOYgpZT+q2lzNp6AF3rlX9WHszlf/nOP8LMndxPQ==";
        };
        _UanQUWSw = {
            "id" = "UanQUWSw";
            "file" = "Clean Hud 1.11-1.12.2-v2.zip";
            "hash" = "sha512-SXAMSsNwFRw7BAI+eKdbnI3RBW0O9H7x4jRF23NWpxlMm4B3aBIJ25pGQP/8vUWeGzpldJuKoKoVKV9jkbeF5w==";
        };
        _YdgdzvHZ = {
            "id" = "YdgdzvHZ";
            "file" = "Clean Hud 1.13-1.14.4-v2.zip";
            "hash" = "sha512-GlnwRe38uPh0e0YkERsaxwRjzJNh17hzPwc5URpdtbcgi27raQ33uI93zz1MEISEALNgVSQSYEYLLghYpHPYvQ==";
        };
        _2Tt2WlYH = {
            "id" = "2Tt2WlYH";
            "file" = "Clean Hud 1.15-1.16.1-v2.zip";
            "hash" = "sha512-YbBXNAGQvGc2RlDyrawD4s0Bxfz/3vwlkx/LdBtY0u5RR80OXw0gikaRPctBvw7jWvfx5zO2muSk7TSKZyZzUQ==";
        };
        _lY3BPQr7 = {
            "id" = "lY3BPQr7";
            "file" = "Clean Hud 1.16.2-1.16.5-v2.zip";
            "hash" = "sha512-eOxd7c8jNDDdT1zpc1Y6h8malOFSp85gFq1aFZUuSNQVL2ucDg+s1ofF1T7yLFKn2E6defgnXHbNPWV2MLDv9Q==";
        };
        _5W8eBUz1 = {
            "id" = "5W8eBUz1";
            "file" = "Clean Hud 1.17-1.17.1-v2.zip";
            "hash" = "sha512-/nVLa/9t3uPXNgBCrCxCmZC27U09TtGNsUrFMm545VK3bt9eCAn7jDoRXu+7N4gec19in2zmY5peOSPs8Pq5ww==";
        };
        _GHG3BiKq = {
            "id" = "GHG3BiKq";
            "file" = "Clean Hud 1.18-1.18.2-v2.zip";
            "hash" = "sha512-2RFJYAFFhdNEtM/UbevdljaHaA4ckQ7vKTqjjPolNSrCj/Tya3AgR/xiPBJ9ZxG4v3fse54WV94TMzicI7EcIw==";
        };
        _55FXo0wE = {
            "id" = "55FXo0wE";
            "file" = "Clean Hud 1.19-1.19.2-v2.zip";
            "hash" = "sha512-rIiZ0RtuxW+yfbitg+2lPJ7YOiGpUn/qBZWhGS2zEAT0EcaDFYaqFK1tfBFAkpOJ7qfrw3mGq3YDep+4jycZ/g==";
        };
        _cXODGrMw = {
            "id" = "cXODGrMw";
            "file" = "Clean Hud 22w42a-22w44a-v2.zip";
            "hash" = "sha512-4rCBSutB35V9rHcBCFTguAtcXNVLypUPbq+e8GkXwjUeEOGlD5d2v3XhgeyGQhjrNwf4KsOZ8alA3XMKAN3tbg==";
        };
        _CQz1x54N = {
            "id" = "CQz1x54N";
            "file" = "Clean Hud 1.19.3-v2.zip";
            "hash" = "sha512-zHSIA5rEXT7se7PsR77eqJa4oTNAjkFLP/VK6CST+qNRRtR7RQHRFgwTXeAZ/DXoehbY1eTBVWA8BTTzdopp4A==";
        };
        _E37ZXlFs = {
            "id" = "E37ZXlFs";
            "file" = "Clean Hud 1.19.4-v2.zip";
            "hash" = "sha512-WY5mmw1mcLHM7V4y0b1dAuAdRw5eQKrA3/tXiDyswz3bMAp8Lvl44ZPvovxGmfT4I4otRh21LDzMgb7VmZ4pCQ==";
        };
        _xgfIKswi = {
            "id" = "xgfIKswi";
            "file" = "Clean Hud 23w14a-23w16a-v2.zip";
            "hash" = "sha512-jYNSLtPbro848KkivAVIh9CW2RDWa0mHdQNUkLBchremBeSmR6OtLanJOSHMB1VPQAuEqxvIgHcXpRrhxvMUvQ==";
        };
        _rFrStWbE = {
            "id" = "rFrStWbE";
            "file" = "Clean Hud 1.20-1.20.1-v2.zip";
            "hash" = "sha512-GHbeBQYnvpWnOgy3Yq9QSg2y//h8j/mL1JcgPxF1Sq9uZ+G6J2XpXc+zubNd5gaErAhA8o1S9khVZLp6pkj5EQ==";
        };
        _UqvaSRxr = {
            "id" = "UqvaSRxr";
            "file" = "Clean Hud v3.zip";
            "hash" = "sha512-qqjs7N8uZwjIEUT7DSD8WWUJfPSXy2XSrzsiqsMWaYX6gbWfFEcJaA8MdFHqIi3aeKXBegGQhQGCld+WuC3Lcw==";
        };
    in {
        "9RYfxKZG" = _9RYfxKZG;
        "ytmBRueT" = _ytmBRueT;
        "GBUmJVuc" = _GBUmJVuc;
        "9BJuNIgR" = _9BJuNIgR;
        "rK5D76ud" = _rK5D76ud;
        "dLm3EkQG" = _dLm3EkQG;
        "v9RxB4fo" = _v9RxB4fo;
        "UpOiNL7o" = _UpOiNL7o;
        "Q2IFIhlT" = _Q2IFIhlT;
        "qOvFunQi" = _qOvFunQi;
        "UanQUWSw" = _UanQUWSw;
        "YdgdzvHZ" = _YdgdzvHZ;
        "2Tt2WlYH" = _2Tt2WlYH;
        "lY3BPQr7" = _lY3BPQr7;
        "5W8eBUz1" = _5W8eBUz1;
        "GHG3BiKq" = _GHG3BiKq;
        "55FXo0wE" = _55FXo0wE;
        "cXODGrMw" = _cXODGrMw;
        "CQz1x54N" = _CQz1x54N;
        "E37ZXlFs" = _E37ZXlFs;
        "xgfIKswi" = _xgfIKswi;
        "rFrStWbE" = _rFrStWbE;
        "UqvaSRxr" = _UqvaSRxr;
        "minecraft-1.20.2" = _UqvaSRxr;
        "minecraft-1.20.3" = _UqvaSRxr;
        "minecraft-1.20.4" = _UqvaSRxr;
        "minecraft-1.20.5" = _UqvaSRxr;
        "minecraft-1.20.6" = _UqvaSRxr;
        "minecraft-1.21" = _UqvaSRxr;
        "minecraft-1.21.1" = _UqvaSRxr;
        "minecraft-1.21.2" = _UqvaSRxr;
        "minecraft-1.21.3" = _UqvaSRxr;
        "minecraft-1.21.4" = _UqvaSRxr;
        "minecraft-1.21.5" = _UqvaSRxr;
        "minecraft-1.21.6" = _UqvaSRxr;
        "minecraft-1.21.7" = _UqvaSRxr;
        "minecraft-1.21.8" = _UqvaSRxr;
        "minecraft-1.6.1" = _Q2IFIhlT;
        "minecraft-1.6.2" = _Q2IFIhlT;
        "minecraft-1.6.4" = _Q2IFIhlT;
        "minecraft-1.7.2" = _Q2IFIhlT;
        "minecraft-1.7.3" = _Q2IFIhlT;
        "minecraft-1.7.4" = _Q2IFIhlT;
        "minecraft-1.7.5" = _Q2IFIhlT;
        "minecraft-1.7.6" = _Q2IFIhlT;
        "minecraft-1.7.7" = _Q2IFIhlT;
        "minecraft-1.7.8" = _Q2IFIhlT;
        "minecraft-1.7.9" = _Q2IFIhlT;
        "minecraft-1.7.10" = _Q2IFIhlT;
        "minecraft-1.8" = _Q2IFIhlT;
        "minecraft-1.8.1" = _Q2IFIhlT;
        "minecraft-1.8.2" = _Q2IFIhlT;
        "minecraft-1.8.3" = _Q2IFIhlT;
        "minecraft-1.8.4" = _Q2IFIhlT;
        "minecraft-1.8.5" = _Q2IFIhlT;
        "minecraft-1.8.6" = _Q2IFIhlT;
        "minecraft-1.8.7" = _Q2IFIhlT;
        "minecraft-1.8.8" = _Q2IFIhlT;
        "minecraft-1.8.9" = _Q2IFIhlT;
        "minecraft-1.9" = _qOvFunQi;
        "minecraft-1.9.1" = _qOvFunQi;
        "minecraft-1.9.2" = _qOvFunQi;
        "minecraft-1.9.3" = _qOvFunQi;
        "minecraft-1.9.4" = _qOvFunQi;
        "minecraft-1.10" = _qOvFunQi;
        "minecraft-1.10.1" = _qOvFunQi;
        "minecraft-1.10.2" = _qOvFunQi;
        "minecraft-1.11" = _UanQUWSw;
        "minecraft-1.11.1" = _UanQUWSw;
        "minecraft-1.11.2" = _UanQUWSw;
        "minecraft-1.12" = _UanQUWSw;
        "minecraft-1.12.1" = _UanQUWSw;
        "minecraft-1.12.2" = _UanQUWSw;
        "minecraft-1.13" = _YdgdzvHZ;
        "minecraft-1.13.1" = _YdgdzvHZ;
        "minecraft-1.13.2" = _YdgdzvHZ;
        "minecraft-1.14" = _YdgdzvHZ;
        "minecraft-1.14.1" = _YdgdzvHZ;
        "minecraft-1.14.2" = _YdgdzvHZ;
        "minecraft-1.14.3" = _YdgdzvHZ;
        "minecraft-1.14.4" = _YdgdzvHZ;
        "minecraft-1.15" = _2Tt2WlYH;
        "minecraft-1.15.1" = _2Tt2WlYH;
        "minecraft-1.15.2" = _2Tt2WlYH;
        "minecraft-1.16" = _2Tt2WlYH;
        "minecraft-1.16.1" = _2Tt2WlYH;
        "minecraft-1.16.2" = _lY3BPQr7;
        "minecraft-1.16.3" = _lY3BPQr7;
        "minecraft-1.16.4" = _lY3BPQr7;
        "minecraft-1.16.5" = _lY3BPQr7;
        "minecraft-1.17" = _5W8eBUz1;
        "minecraft-1.17.1" = _5W8eBUz1;
        "minecraft-1.18" = _GHG3BiKq;
        "minecraft-1.18.1" = _GHG3BiKq;
        "minecraft-1.18.2" = _GHG3BiKq;
        "minecraft-1.19" = _55FXo0wE;
        "minecraft-1.19.1" = _55FXo0wE;
        "minecraft-1.19.2" = _55FXo0wE;
        "minecraft-1.19.3" = _CQz1x54N;
        "minecraft-1.19.4" = _E37ZXlFs;
        "minecraft-1.20" = _rFrStWbE;
        "minecraft-1.20.1" = _rFrStWbE;
        "minecraft-1.21.9" = _UqvaSRxr;
        "minecraft-1.21.10" = _UqvaSRxr;
        "minecraft-1.21.11" = _UqvaSRxr;
        "minecraft-22w42a" = _cXODGrMw;
        "minecraft-22w43a" = _cXODGrMw;
        "minecraft-22w44a" = _cXODGrMw;
        "minecraft-23w14a" = _xgfIKswi;
        "minecraft-23w16a" = _xgfIKswi;
        "minecraft-23w17a" = _rFrStWbE;
        "minecraft-23w18a" = _rFrStWbE;
        "minecraft-23w31a" = _UqvaSRxr;
        "minecraft-23w32a" = _UqvaSRxr;
        "minecraft-23w33a" = _UqvaSRxr;
        "minecraft-23w35a" = _UqvaSRxr;
        "minecraft-1.20.2-pre1" = _UqvaSRxr;
        "minecraft-1.20.2-pre2" = _UqvaSRxr;
        "minecraft-1.20.2-pre3" = _UqvaSRxr;
        "minecraft-1.20.2-pre4" = _UqvaSRxr;
        "minecraft-1.20.2-rc1" = _UqvaSRxr;
        "minecraft-1.20.2-rc2" = _UqvaSRxr;
        "minecraft-23w40a" = _UqvaSRxr;
        "minecraft-23w41a" = _UqvaSRxr;
        "minecraft-23w42a" = _UqvaSRxr;
        "minecraft-23w43a" = _UqvaSRxr;
        "minecraft-23w43b" = _UqvaSRxr;
        "minecraft-23w44a" = _UqvaSRxr;
        "minecraft-23w45a" = _UqvaSRxr;
        "minecraft-23w46a" = _UqvaSRxr;
        "minecraft-1.20.3-pre1" = _UqvaSRxr;
        "minecraft-1.20.3-pre2" = _UqvaSRxr;
        "minecraft-1.20.3-pre3" = _UqvaSRxr;
        "minecraft-1.20.3-pre4" = _UqvaSRxr;
        "minecraft-1.20.3-rc1" = _UqvaSRxr;
        "minecraft-1.20.4-rc1" = _UqvaSRxr;
        "minecraft-23w51a" = _UqvaSRxr;
        "minecraft-23w51b" = _UqvaSRxr;
        "minecraft-24w03a" = _UqvaSRxr;
        "minecraft-24w03b" = _UqvaSRxr;
        "minecraft-24w04a" = _UqvaSRxr;
        "minecraft-24w05a" = _UqvaSRxr;
        "minecraft-24w05b" = _UqvaSRxr;
        "minecraft-24w06a" = _UqvaSRxr;
        "minecraft-24w07a" = _UqvaSRxr;
        "minecraft-24w09a" = _UqvaSRxr;
        "minecraft-24w10a" = _UqvaSRxr;
        "minecraft-24w11a" = _UqvaSRxr;
        "minecraft-24w12a" = _UqvaSRxr;
        "minecraft-24w13a" = _UqvaSRxr;
        "minecraft-24w14potato" = _UqvaSRxr;
        "minecraft-24w14a" = _UqvaSRxr;
        "minecraft-1.20.5-pre1" = _UqvaSRxr;
        "minecraft-1.20.5-pre2" = _UqvaSRxr;
        "minecraft-1.20.5-pre3" = _UqvaSRxr;
        "minecraft-1.20.5-pre4" = _UqvaSRxr;
        "minecraft-1.20.5-rc1" = _UqvaSRxr;
        "minecraft-1.20.5-rc2" = _UqvaSRxr;
        "minecraft-1.20.5-rc3" = _UqvaSRxr;
        "minecraft-1.20.6-rc1" = _UqvaSRxr;
        "minecraft-24w18a" = _UqvaSRxr;
        "minecraft-24w19a" = _UqvaSRxr;
        "minecraft-24w19b" = _UqvaSRxr;
        "minecraft-24w20a" = _UqvaSRxr;
        "minecraft-24w21a" = _UqvaSRxr;
        "minecraft-24w21b" = _UqvaSRxr;
        "minecraft-1.21-pre1" = _UqvaSRxr;
        "minecraft-1.21-pre2" = _UqvaSRxr;
        "minecraft-1.21-pre3" = _UqvaSRxr;
        "minecraft-1.21-pre4" = _UqvaSRxr;
        "minecraft-1.21-rc1" = _UqvaSRxr;
        "minecraft-1.21.1-rc1" = _UqvaSRxr;
        "minecraft-24w33a" = _UqvaSRxr;
        "minecraft-24w34a" = _UqvaSRxr;
        "minecraft-24w35a" = _UqvaSRxr;
        "minecraft-24w36a" = _UqvaSRxr;
        "minecraft-24w37a" = _UqvaSRxr;
        "minecraft-24w38a" = _UqvaSRxr;
        "minecraft-24w39a" = _UqvaSRxr;
        "minecraft-24w40a" = _UqvaSRxr;
        "minecraft-1.21.2-pre1" = _UqvaSRxr;
        "minecraft-1.21.2-pre2" = _UqvaSRxr;
        "minecraft-1.21.2-pre3" = _UqvaSRxr;
        "minecraft-1.21.2-pre4" = _UqvaSRxr;
        "minecraft-1.21.2-pre5" = _UqvaSRxr;
        "minecraft-1.21.2-rc1" = _UqvaSRxr;
        "minecraft-1.21.2-rc2" = _UqvaSRxr;
        "minecraft-24w44a" = _UqvaSRxr;
        "minecraft-24w45a" = _UqvaSRxr;
        "minecraft-24w46a" = _UqvaSRxr;
        "minecraft-1.21.4-pre1" = _UqvaSRxr;
        "minecraft-1.21.4-pre2" = _UqvaSRxr;
        "minecraft-1.21.4-pre3" = _UqvaSRxr;
        "minecraft-1.21.4-rc1" = _UqvaSRxr;
        "minecraft-1.21.4-rc2" = _UqvaSRxr;
        "minecraft-1.21.4-rc3" = _UqvaSRxr;
        "minecraft-25w02a" = _UqvaSRxr;
        "minecraft-25w03a" = _UqvaSRxr;
        "minecraft-25w04a" = _UqvaSRxr;
        "minecraft-25w05a" = _UqvaSRxr;
        "minecraft-25w06a" = _UqvaSRxr;
        "minecraft-25w07a" = _UqvaSRxr;
        "minecraft-25w08a" = _UqvaSRxr;
        "minecraft-25w09a" = _UqvaSRxr;
        "minecraft-25w09b" = _UqvaSRxr;
        "minecraft-25w10a" = _UqvaSRxr;
        "minecraft-1.21.5-pre1" = _UqvaSRxr;
        "minecraft-1.21.5-pre2" = _UqvaSRxr;
        "minecraft-1.21.5-pre3" = _UqvaSRxr;
        "minecraft-1.21.5-rc1" = _UqvaSRxr;
        "minecraft-1.21.5-rc2" = _UqvaSRxr;
        "minecraft-25w14craftmine" = _UqvaSRxr;
        "minecraft-25w15a" = _UqvaSRxr;
        "minecraft-25w16a" = _UqvaSRxr;
        "minecraft-25w17a" = _UqvaSRxr;
        "minecraft-25w18a" = _UqvaSRxr;
        "minecraft-25w19a" = _UqvaSRxr;
        "minecraft-25w20a" = _UqvaSRxr;
        "minecraft-25w21a" = _UqvaSRxr;
        "minecraft-1.21.6-pre1" = _UqvaSRxr;
        "minecraft-1.21.6-pre2" = _UqvaSRxr;
        "minecraft-1.21.6-pre3" = _UqvaSRxr;
        "minecraft-1.21.6-pre4" = _UqvaSRxr;
        "minecraft-1.21.6-rc1" = _UqvaSRxr;
        "minecraft-1.21.7-rc1" = _UqvaSRxr;
        "minecraft-1.21.7-rc2" = _UqvaSRxr;
        "minecraft-1.21.8-rc1" = _UqvaSRxr;
        "minecraft-25w31a" = _UqvaSRxr;
        "minecraft-25w32a" = _UqvaSRxr;
        "minecraft-25w33a" = _UqvaSRxr;
        "minecraft-25w34a" = _UqvaSRxr;
        "minecraft-25w34b" = _UqvaSRxr;
        "minecraft-25w35a" = _UqvaSRxr;
        "minecraft-25w36a" = _UqvaSRxr;
        "minecraft-25w36b" = _UqvaSRxr;
        "minecraft-25w37a" = _UqvaSRxr;
        "minecraft-1.21.9-pre1" = _UqvaSRxr;
        "minecraft-1.21.9-pre2" = _UqvaSRxr;
        "minecraft-1.21.9-pre3" = _UqvaSRxr;
        "minecraft-1.21.9-pre4" = _UqvaSRxr;
        "minecraft-1.21.9-rc1" = _UqvaSRxr;
        "minecraft-1.21.10-rc1" = _UqvaSRxr;
        "minecraft-25w41a" = _UqvaSRxr;
        "minecraft-25w42a" = _UqvaSRxr;
        "minecraft-25w43a" = _UqvaSRxr;
        "minecraft-25w44a" = _UqvaSRxr;
        "minecraft-25w45a" = _UqvaSRxr;
        "minecraft-25w46a" = _UqvaSRxr;
        "minecraft-1.21.11-pre1" = _UqvaSRxr;
        "minecraft-1.21.11-pre2" = _UqvaSRxr;
        "minecraft-1.21.11-pre3" = _UqvaSRxr;
        "minecraft-1.21.11-pre4" = _UqvaSRxr;
        "minecraft-1.21.11-pre5" = _UqvaSRxr;
        "minecraft-1.21.11-rc1" = _UqvaSRxr;
        "minecraft-1.21.11-rc2" = _UqvaSRxr;
        "minecraft-1.21.11-rc3" = _UqvaSRxr;
        "minecraft-26.1-snapshot-1" = _UqvaSRxr;
        "minecraft-26.1-snapshot-2" = _UqvaSRxr;
        "minecraft-26.1-snapshot-3" = _UqvaSRxr;
        "minecraft-26.1-snapshot-4" = _UqvaSRxr;
        "minecraft-26.1-snapshot-5" = _UqvaSRxr;
        "minecraft-26.1-snapshot-6" = _UqvaSRxr;
        "minecraft-26.1-snapshot-7" = _UqvaSRxr;
        "minecraft-26.1-snapshot-8" = _UqvaSRxr;
        "minecraft-26.1-snapshot-9" = _UqvaSRxr;
        "minecraft-26.1-snapshot-10" = _UqvaSRxr;
        "minecraft-26.1-snapshot-11" = _UqvaSRxr;
        "minecraft-26.1-pre-1" = _UqvaSRxr;
        "minecraft-26.1-pre-2" = _UqvaSRxr;
        "minecraft-26.1-pre-3" = _UqvaSRxr;
        "minecraft-26.1-rc-1" = _UqvaSRxr;
        "minecraft-26.1-rc-2" = _UqvaSRxr;
        "minecraft-26.1-rc-3" = _UqvaSRxr;
        "minecraft-26.1" = _UqvaSRxr;
        "minecraft-26.1.1-rc-1" = _UqvaSRxr;
        "minecraft-26.1.1" = _UqvaSRxr;
        "minecraft-26w14a" = _UqvaSRxr;
        "minecraft-26.2-snapshot-1" = _UqvaSRxr;
        "minecraft-26.1.2-rc-1" = _UqvaSRxr;
        "minecraft-26.1.2" = _UqvaSRxr;
        "minecraft-26.2-snapshot-2" = _UqvaSRxr;
        "minecraft-26.2-snapshot-3" = _UqvaSRxr;
        "minecraft-26.2-snapshot-4" = _UqvaSRxr;
        "minecraft-26.2-snapshot-5" = _UqvaSRxr;
        "minecraft-26.2-snapshot-6" = _UqvaSRxr;
        "minecraft-26.2-snapshot-7" = _UqvaSRxr;
        "minecraft-26.2-snapshot-8" = _UqvaSRxr;
        "minecraft-26.2-pre-1" = _UqvaSRxr;
        "minecraft-26.2-pre-2" = _UqvaSRxr;
        "minecraft-26.2-pre-3" = _UqvaSRxr;
        "minecraft-26.2-pre-4" = _UqvaSRxr;
        "minecraft-26.2-pre-5" = _UqvaSRxr;
        "minecraft-26.2-pre-6" = _UqvaSRxr;
        "minecraft-26.2-rc-1" = _UqvaSRxr;
        "minecraft-26.2-rc-2" = _UqvaSRxr;
        "minecraft-26.2" = _UqvaSRxr;
        "minecraft-26.3-snapshot-1" = _UqvaSRxr;
        "minecraft-26.3-snapshot-2" = _UqvaSRxr;
        "minecraft-26.3-snapshot-3" = _UqvaSRxr;
        "minecraft-26.3-snapshot-4" = _UqvaSRxr;
        "minecraft-26.3-snapshot-5" = _UqvaSRxr;
        "minecraft-26.3-snapshot-6" = _UqvaSRxr;
        "minecraft-26.3-snapshot-7" = _UqvaSRxr;
    });
    fn = {stdenv, fetchurl, version, ...}:
        lib.prismnix.pkgs.mkVersionedModrinthPkg {
            inherit stdenv fetchurl;
            name = "clean-hud";
            id = "iTWyyQmj";
            type = "resourcepack";
            version = version;
            versions = versions;
            meta = {
                license = lib.getLicenseFromSpdxIdOr "CC-BY-4.0" {
                    free = false;
                    deprecated = false;
                    redistributable = false;
                    fullName = "Creative Commons Attribution 4.0 International";
                    shortName = "CC-BY-4.0";
                    url = null;
                };
            };
        };
in callPackage fn {version="UqvaSRxr";}