{lib, callPackage, ...}:
let
    versions = (let
        _IzaY0OCN = {
            "id" = "IzaY0OCN";
            "file" = "LoginMe-1.0.0 (1).jar";
            "hash" = "sha512-UasnJoUGlexwvaU2pVoLD0Rq6u421tn99BLrBRABsRzSyEvYYQi6mIlpoM+7mGZgrNeWs5JbO+gHbxlhxOeruA==";
        };
        _JEUbXjEt = {
            "id" = "JEUbXjEt";
            "file" = "LoginMe-1.0.1.jar";
            "hash" = "sha512-B1bNFB7knL5kYrZN2JnqereqcAKKmXRs96siAcrN0Tif7WBaLO3wCvRqw5H8XHupYtXgVqnJVbYRaOnykq+gZA==";
        };
    in {
        "IzaY0OCN" = _IzaY0OCN;
        "JEUbXjEt" = _JEUbXjEt;
        "paper-1.21" = _JEUbXjEt;
        "paper-1.21.1" = _JEUbXjEt;
        "paper-1.21.2" = _JEUbXjEt;
        "paper-1.21.3" = _JEUbXjEt;
        "paper-1.21.4" = _JEUbXjEt;
        "paper-1.21.5" = _JEUbXjEt;
        "paper-1.21.6" = _JEUbXjEt;
        "paper-1.21.7" = _JEUbXjEt;
        "paper-1.21.8" = _JEUbXjEt;
        "paper-1.21.9" = _JEUbXjEt;
        "paper-1.21.10" = _JEUbXjEt;
        "paper-1.21.11" = _JEUbXjEt;
        "spigot-1.21" = _JEUbXjEt;
        "spigot-1.21.1" = _JEUbXjEt;
        "spigot-1.21.2" = _JEUbXjEt;
        "spigot-1.21.3" = _JEUbXjEt;
        "spigot-1.21.4" = _JEUbXjEt;
        "spigot-1.21.5" = _JEUbXjEt;
        "spigot-1.21.6" = _JEUbXjEt;
        "spigot-1.21.7" = _JEUbXjEt;
        "spigot-1.21.8" = _JEUbXjEt;
        "spigot-1.21.9" = _JEUbXjEt;
        "spigot-1.21.10" = _JEUbXjEt;
        "spigot-1.21.11" = _JEUbXjEt;
        "bukkit-1.21" = _JEUbXjEt;
        "bukkit-1.21.1" = _JEUbXjEt;
        "bukkit-1.21.2" = _JEUbXjEt;
        "bukkit-1.21.3" = _JEUbXjEt;
        "bukkit-1.21.4" = _JEUbXjEt;
        "bukkit-1.21.5" = _JEUbXjEt;
        "bukkit-1.21.6" = _JEUbXjEt;
        "bukkit-1.21.7" = _JEUbXjEt;
        "bukkit-1.21.8" = _JEUbXjEt;
        "bukkit-1.21.9" = _JEUbXjEt;
        "bukkit-1.21.10" = _JEUbXjEt;
        "bukkit-1.21.11" = _JEUbXjEt;
        "bungeecord-1.21" = _JEUbXjEt;
        "bungeecord-1.21.1" = _JEUbXjEt;
        "bungeecord-1.21.2" = _JEUbXjEt;
        "bungeecord-1.21.3" = _JEUbXjEt;
        "bungeecord-1.21.4" = _JEUbXjEt;
        "bungeecord-1.21.5" = _JEUbXjEt;
        "bungeecord-1.21.6" = _JEUbXjEt;
        "bungeecord-1.21.7" = _JEUbXjEt;
        "bungeecord-1.21.8" = _JEUbXjEt;
        "bungeecord-1.21.9" = _JEUbXjEt;
        "bungeecord-1.21.10" = _JEUbXjEt;
        "bungeecord-1.21.11" = _JEUbXjEt;
        "folia-1.21" = _JEUbXjEt;
        "folia-1.21.1" = _JEUbXjEt;
        "folia-1.21.2" = _JEUbXjEt;
        "folia-1.21.3" = _JEUbXjEt;
        "folia-1.21.4" = _JEUbXjEt;
        "folia-1.21.5" = _JEUbXjEt;
        "folia-1.21.6" = _JEUbXjEt;
        "folia-1.21.7" = _JEUbXjEt;
        "folia-1.21.8" = _JEUbXjEt;
        "folia-1.21.9" = _JEUbXjEt;
        "folia-1.21.10" = _JEUbXjEt;
        "folia-1.21.11" = _JEUbXjEt;
        "purpur-1.21" = _JEUbXjEt;
        "purpur-1.21.1" = _JEUbXjEt;
        "purpur-1.21.2" = _JEUbXjEt;
        "purpur-1.21.3" = _JEUbXjEt;
        "purpur-1.21.4" = _JEUbXjEt;
        "purpur-1.21.5" = _JEUbXjEt;
        "purpur-1.21.6" = _JEUbXjEt;
        "purpur-1.21.7" = _JEUbXjEt;
        "purpur-1.21.8" = _JEUbXjEt;
        "purpur-1.21.9" = _JEUbXjEt;
        "purpur-1.21.10" = _JEUbXjEt;
        "purpur-1.21.11" = _JEUbXjEt;
        "velocity-1.21" = _JEUbXjEt;
        "velocity-1.21.1" = _JEUbXjEt;
        "velocity-1.21.2" = _JEUbXjEt;
        "velocity-1.21.3" = _JEUbXjEt;
        "velocity-1.21.4" = _JEUbXjEt;
        "velocity-1.21.5" = _JEUbXjEt;
        "velocity-1.21.6" = _JEUbXjEt;
        "velocity-1.21.7" = _JEUbXjEt;
        "velocity-1.21.8" = _JEUbXjEt;
        "velocity-1.21.9" = _JEUbXjEt;
        "velocity-1.21.10" = _JEUbXjEt;
        "velocity-1.21.11" = _JEUbXjEt;
        "waterfall-1.21" = _JEUbXjEt;
        "waterfall-1.21.1" = _JEUbXjEt;
        "waterfall-1.21.2" = _JEUbXjEt;
        "waterfall-1.21.3" = _JEUbXjEt;
        "waterfall-1.21.4" = _JEUbXjEt;
        "waterfall-1.21.5" = _JEUbXjEt;
        "waterfall-1.21.6" = _JEUbXjEt;
        "waterfall-1.21.7" = _JEUbXjEt;
        "waterfall-1.21.8" = _JEUbXjEt;
        "waterfall-1.21.9" = _JEUbXjEt;
        "waterfall-1.21.10" = _JEUbXjEt;
        "waterfall-1.21.11" = _JEUbXjEt;
        "default" = _JEUbXjEt;
    });
    fn = {stdenv, fetchurl, version, ...}:
        lib.prismnix.pkgs.mkVersionedModrinthPkg {
            inherit stdenv fetchurl;
            name = "loginme";
            id = "kbUCkuFX";
            type = "mod";
            version = version;
            versions = versions;
            meta = {
                license = lib.getLicenseFromSpdxIdOr "LicenseRef-All-Rights-Reserved" {
                    free = false;
                    deprecated = false;
                    redistributable = false;
                    fullName = "LicenseRef-All-Rights-Reserved";
                    shortName = "LicenseRef-All-Rights-Reserved";
                    url = null;
                };
            };
        };
in callPackage fn {version="default";}