{lib, callPackage, ...}:
let
    versions = (let
        _j7DEawFL = {
            "id" = "j7DEawFL";
            "file" = "Font+.zip";
            "hash" = "sha512-WuLEjBB4hCE4fBcmuXODWgkNVSc/L0Q/k81mwdvk8FBw2HG9kW5Wr4O4hOHVu15hjv+rDcmC02lxzPpuqFcq4A==";
        };
    in {
        "j7DEawFL" = _j7DEawFL;
        "minecraft-1.18" = _j7DEawFL;
        "minecraft-1.18.1" = _j7DEawFL;
        "minecraft-1.18.2" = _j7DEawFL;
        "minecraft-1.19" = _j7DEawFL;
        "minecraft-1.19.1" = _j7DEawFL;
        "minecraft-1.19.2" = _j7DEawFL;
        "minecraft-1.19.3" = _j7DEawFL;
        "minecraft-1.19.4" = _j7DEawFL;
        "minecraft-1.20" = _j7DEawFL;
        "minecraft-1.20.1" = _j7DEawFL;
        "minecraft-23w31a" = _j7DEawFL;
        "minecraft-23w32a" = _j7DEawFL;
        "minecraft-23w33a" = _j7DEawFL;
        "minecraft-23w35a" = _j7DEawFL;
        "minecraft-1.20.2-pre1" = _j7DEawFL;
        "minecraft-1.20.2" = _j7DEawFL;
        "minecraft-23w42a" = _j7DEawFL;
        "minecraft-23w43a" = _j7DEawFL;
        "minecraft-23w43b" = _j7DEawFL;
        "minecraft-23w44a" = _j7DEawFL;
        "minecraft-23w45a" = _j7DEawFL;
        "minecraft-23w46a" = _j7DEawFL;
        "minecraft-1.20.3" = _j7DEawFL;
        "minecraft-1.20.4" = _j7DEawFL;
        "minecraft-24w03a" = _j7DEawFL;
        "minecraft-24w03b" = _j7DEawFL;
        "minecraft-24w04a" = _j7DEawFL;
        "minecraft-24w05a" = _j7DEawFL;
        "minecraft-24w05b" = _j7DEawFL;
        "minecraft-24w06a" = _j7DEawFL;
        "minecraft-24w07a" = _j7DEawFL;
        "minecraft-24w09a" = _j7DEawFL;
        "minecraft-24w10a" = _j7DEawFL;
        "minecraft-24w11a" = _j7DEawFL;
        "minecraft-24w12a" = _j7DEawFL;
        "minecraft-24w13a" = _j7DEawFL;
        "minecraft-24w14potato" = _j7DEawFL;
        "minecraft-24w14a" = _j7DEawFL;
        "minecraft-1.20.5-pre1" = _j7DEawFL;
        "minecraft-1.20.5-pre2" = _j7DEawFL;
        "minecraft-1.20.5-pre3" = _j7DEawFL;
        "minecraft-1.20.5" = _j7DEawFL;
        "minecraft-1.20.6" = _j7DEawFL;
        "minecraft-24w18a" = _j7DEawFL;
        "minecraft-24w19a" = _j7DEawFL;
        "minecraft-24w19b" = _j7DEawFL;
        "minecraft-24w20a" = _j7DEawFL;
        "minecraft-1.21" = _j7DEawFL;
        "minecraft-1.21.1" = _j7DEawFL;
        "minecraft-24w33a" = _j7DEawFL;
        "minecraft-24w34a" = _j7DEawFL;
        "minecraft-24w35a" = _j7DEawFL;
        "minecraft-24w36a" = _j7DEawFL;
        "minecraft-24w37a" = _j7DEawFL;
        "minecraft-24w38a" = _j7DEawFL;
        "minecraft-24w39a" = _j7DEawFL;
        "minecraft-24w40a" = _j7DEawFL;
        "minecraft-1.21.2-pre1" = _j7DEawFL;
        "minecraft-1.21.2-pre2" = _j7DEawFL;
        "minecraft-1.21.2" = _j7DEawFL;
        "minecraft-1.21.3" = _j7DEawFL;
        "minecraft-24w44a" = _j7DEawFL;
        "minecraft-24w45a" = _j7DEawFL;
        "minecraft-24w46a" = _j7DEawFL;
        "minecraft-1.21.4" = _j7DEawFL;
        "minecraft-1.21.5" = _j7DEawFL;
        "minecraft-1.21.6" = _j7DEawFL;
        "minecraft-1.21.7" = _j7DEawFL;
        "minecraft-1.21.8" = _j7DEawFL;
        "minecraft-1.21.9" = _j7DEawFL;
        "minecraft-1.21.10" = _j7DEawFL;
        "minecraft-1.21.11" = _j7DEawFL;
        "minecraft-26.1" = _j7DEawFL;
        "minecraft-26.1.1" = _j7DEawFL;
        "minecraft-26.1.2" = _j7DEawFL;
        "minecraft-26.2-snapshot-2" = _j7DEawFL;
        "minecraft-26.2-snapshot-3" = _j7DEawFL;
        "minecraft-26.2-snapshot-4" = _j7DEawFL;
        "minecraft-26.2-snapshot-5" = _j7DEawFL;
        "minecraft-26.2-snapshot-6" = _j7DEawFL;
        "minecraft-26.2-snapshot-7" = _j7DEawFL;
        "minecraft-26.2-snapshot-8" = _j7DEawFL;
        "minecraft-26.2-pre-1" = _j7DEawFL;
        "minecraft-26.2-pre-2" = _j7DEawFL;
        "minecraft-26.2" = _j7DEawFL;
        "default" = _j7DEawFL;
    });
    fn = {stdenv, fetchurl, version, ...}:
        lib.prismnix.pkgs.mkVersionedModrinthPkg {
            inherit stdenv fetchurl;
            name = "font+";
            id = "mtgrw1kg";
            type = "resourcepack";
            version = version;
            versions = versions;
            meta = {
                license = lib.getLicenseFromSpdxIdOr "LicenseRef-All-Rights-Reserved" {
                    free = false;
                    deprecated = false;
                    redistributable = false;
                    fullName = "LicenseRef-All-Rights-Reserved";
                    shortName = "LicenseRef-All-Rights-Reserved";
                    url = null;
                };
            };
        };
in callPackage fn {version="default";}