{lib, callPackage, ...}:
let
    versions = (let
        _qMbNd6YF = {
            "id" = "qMbNd6YF";
            "file" = "No Pumpkin Overlay.zip";
            "hash" = "sha512-YTTrD6gLaNu7MPUh/H4cyZL9rMn1rjS7ucdTGRxc2OgexNq2uqma3gCOhK77Iw2Z6JOFVFX5Af+n05ptCJIceA==";
        };
    in {
        "qMbNd6YF" = _qMbNd6YF;
        "minecraft-1.6.1" = _qMbNd6YF;
        "minecraft-1.6.2" = _qMbNd6YF;
        "minecraft-1.6.4" = _qMbNd6YF;
        "minecraft-1.7.2" = _qMbNd6YF;
        "minecraft-1.7.3" = _qMbNd6YF;
        "minecraft-1.7.4" = _qMbNd6YF;
        "minecraft-1.7.5" = _qMbNd6YF;
        "minecraft-1.7.6" = _qMbNd6YF;
        "minecraft-1.7.7" = _qMbNd6YF;
        "minecraft-1.7.8" = _qMbNd6YF;
        "minecraft-1.7.9" = _qMbNd6YF;
        "minecraft-1.7.10" = _qMbNd6YF;
        "minecraft-1.8" = _qMbNd6YF;
        "minecraft-1.8.1" = _qMbNd6YF;
        "minecraft-1.8.2" = _qMbNd6YF;
        "minecraft-1.8.3" = _qMbNd6YF;
        "minecraft-1.8.4" = _qMbNd6YF;
        "minecraft-1.8.5" = _qMbNd6YF;
        "minecraft-1.8.6" = _qMbNd6YF;
        "minecraft-1.8.7" = _qMbNd6YF;
        "minecraft-1.8.8" = _qMbNd6YF;
        "minecraft-1.8.9" = _qMbNd6YF;
        "minecraft-1.9" = _qMbNd6YF;
        "minecraft-1.9.1" = _qMbNd6YF;
        "minecraft-1.9.2" = _qMbNd6YF;
        "minecraft-1.9.3" = _qMbNd6YF;
        "minecraft-1.9.4" = _qMbNd6YF;
        "minecraft-1.10" = _qMbNd6YF;
        "minecraft-1.10.1" = _qMbNd6YF;
        "minecraft-1.10.2" = _qMbNd6YF;
        "minecraft-1.11" = _qMbNd6YF;
        "minecraft-1.11.1" = _qMbNd6YF;
        "minecraft-1.11.2" = _qMbNd6YF;
        "minecraft-1.12" = _qMbNd6YF;
        "minecraft-1.12.1" = _qMbNd6YF;
        "minecraft-1.12.2" = _qMbNd6YF;
        "minecraft-1.13" = _qMbNd6YF;
        "minecraft-1.13.1" = _qMbNd6YF;
        "minecraft-1.13.2" = _qMbNd6YF;
        "minecraft-1.14" = _qMbNd6YF;
        "minecraft-1.14.1" = _qMbNd6YF;
        "minecraft-1.14.2" = _qMbNd6YF;
        "minecraft-1.14.3" = _qMbNd6YF;
        "minecraft-1.14.4" = _qMbNd6YF;
        "minecraft-1.15" = _qMbNd6YF;
        "minecraft-1.15.1" = _qMbNd6YF;
        "minecraft-1.15.2" = _qMbNd6YF;
        "minecraft-1.16" = _qMbNd6YF;
        "minecraft-1.16.1" = _qMbNd6YF;
        "minecraft-1.16.2" = _qMbNd6YF;
        "minecraft-1.16.3" = _qMbNd6YF;
        "minecraft-1.16.4" = _qMbNd6YF;
        "minecraft-1.16.5" = _qMbNd6YF;
        "minecraft-1.17" = _qMbNd6YF;
        "minecraft-1.17.1" = _qMbNd6YF;
        "minecraft-1.18" = _qMbNd6YF;
        "minecraft-1.18.1" = _qMbNd6YF;
        "minecraft-1.18.2" = _qMbNd6YF;
        "minecraft-1.19" = _qMbNd6YF;
        "minecraft-1.19.1" = _qMbNd6YF;
        "minecraft-1.19.2" = _qMbNd6YF;
        "minecraft-1.19.3" = _qMbNd6YF;
        "minecraft-1.19.4" = _qMbNd6YF;
        "minecraft-1.20" = _qMbNd6YF;
        "minecraft-1.20.1" = _qMbNd6YF;
        "minecraft-1.20.2" = _qMbNd6YF;
        "minecraft-1.20.3" = _qMbNd6YF;
        "minecraft-1.20.4" = _qMbNd6YF;
        "minecraft-1.20.5" = _qMbNd6YF;
        "minecraft-1.20.6" = _qMbNd6YF;
        "minecraft-1.21" = _qMbNd6YF;
        "minecraft-1.21.1" = _qMbNd6YF;
        "minecraft-1.21.2" = _qMbNd6YF;
        "minecraft-1.21.3" = _qMbNd6YF;
        "minecraft-1.21.4" = _qMbNd6YF;
        "minecraft-1.21.5" = _qMbNd6YF;
        "minecraft-1.21.6" = _qMbNd6YF;
        "minecraft-1.21.7" = _qMbNd6YF;
        "minecraft-1.21.8" = _qMbNd6YF;
        "minecraft-1.21.9" = _qMbNd6YF;
        "default" = _qMbNd6YF;
    });
    fn = {stdenv, fetchurl, version, ...}:
        lib.prismnix.pkgs.mkVersionedModrinthPkg {
            inherit stdenv fetchurl;
            name = "pumpkinlessoverlay";
            id = "O6T2GhVZ";
            type = "resourcepack";
            version = version;
            versions = versions;
            meta = {
                license = lib.getLicenseFromSpdxIdOr "LicenseRef-All-Rights-Reserved" {
                    free = false;
                    deprecated = false;
                    redistributable = false;
                    fullName = "LicenseRef-All-Rights-Reserved";
                    shortName = "LicenseRef-All-Rights-Reserved";
                    url = null;
                };
            };
        };
in callPackage fn {version="default";}