{lib, callPackage, ...}:
let
    versions = (let
        _i1SVCoyS = {
            "id" = "i1SVCoyS";
            "file" = "Invisible World Border.zip";
            "hash" = "sha512-V8Xh6mJtBx5YcO13GTOHWvJTjTuM9XTXWa+9tN9mHUwHYehwFVg/DtpIfXNNomnG02UawK5iXJP4+cFetW/0Gw==";
        };
    in {
        "i1SVCoyS" = _i1SVCoyS;
        "minecraft-1.8" = _i1SVCoyS;
        "minecraft-1.8.1" = _i1SVCoyS;
        "minecraft-1.8.2" = _i1SVCoyS;
        "minecraft-1.8.3" = _i1SVCoyS;
        "minecraft-1.8.4" = _i1SVCoyS;
        "minecraft-1.8.5" = _i1SVCoyS;
        "minecraft-1.8.6" = _i1SVCoyS;
        "minecraft-1.8.7" = _i1SVCoyS;
        "minecraft-1.8.8" = _i1SVCoyS;
        "minecraft-1.8.9" = _i1SVCoyS;
        "minecraft-1.9" = _i1SVCoyS;
        "minecraft-1.9.1" = _i1SVCoyS;
        "minecraft-1.9.2" = _i1SVCoyS;
        "minecraft-1.9.3" = _i1SVCoyS;
        "minecraft-1.9.4" = _i1SVCoyS;
        "minecraft-1.10" = _i1SVCoyS;
        "minecraft-1.10.1" = _i1SVCoyS;
        "minecraft-1.10.2" = _i1SVCoyS;
        "minecraft-1.11" = _i1SVCoyS;
        "minecraft-1.11.1" = _i1SVCoyS;
        "minecraft-1.11.2" = _i1SVCoyS;
        "minecraft-1.12" = _i1SVCoyS;
        "minecraft-1.12.1" = _i1SVCoyS;
        "minecraft-1.12.2" = _i1SVCoyS;
        "minecraft-1.13" = _i1SVCoyS;
        "minecraft-1.13.1" = _i1SVCoyS;
        "minecraft-1.13.2" = _i1SVCoyS;
        "minecraft-1.14" = _i1SVCoyS;
        "minecraft-1.14.1" = _i1SVCoyS;
        "minecraft-1.14.2" = _i1SVCoyS;
        "minecraft-1.14.3" = _i1SVCoyS;
        "minecraft-1.14.4" = _i1SVCoyS;
        "minecraft-1.15" = _i1SVCoyS;
        "minecraft-1.15.1" = _i1SVCoyS;
        "minecraft-1.15.2" = _i1SVCoyS;
        "minecraft-1.16" = _i1SVCoyS;
        "minecraft-1.16.1" = _i1SVCoyS;
        "minecraft-1.16.2" = _i1SVCoyS;
        "minecraft-1.16.3" = _i1SVCoyS;
        "minecraft-1.16.4" = _i1SVCoyS;
        "minecraft-1.16.5" = _i1SVCoyS;
        "minecraft-1.17" = _i1SVCoyS;
        "minecraft-1.17.1" = _i1SVCoyS;
        "minecraft-1.18" = _i1SVCoyS;
        "minecraft-1.18.1" = _i1SVCoyS;
        "minecraft-1.18.2" = _i1SVCoyS;
        "minecraft-1.19" = _i1SVCoyS;
        "minecraft-1.19.1" = _i1SVCoyS;
        "minecraft-1.19.2" = _i1SVCoyS;
        "minecraft-1.19.3" = _i1SVCoyS;
        "minecraft-1.19.4" = _i1SVCoyS;
        "minecraft-1.20" = _i1SVCoyS;
        "minecraft-1.20.1" = _i1SVCoyS;
        "minecraft-1.20.2" = _i1SVCoyS;
        "minecraft-1.20.3" = _i1SVCoyS;
        "minecraft-1.20.4" = _i1SVCoyS;
        "minecraft-1.20.5" = _i1SVCoyS;
        "minecraft-1.20.6" = _i1SVCoyS;
        "minecraft-1.21" = _i1SVCoyS;
        "minecraft-1.21.1" = _i1SVCoyS;
        "minecraft-1.21.2" = _i1SVCoyS;
        "minecraft-1.21.3" = _i1SVCoyS;
        "minecraft-1.21.4" = _i1SVCoyS;
        "minecraft-1.21.5" = _i1SVCoyS;
        "minecraft-1.21.6" = _i1SVCoyS;
        "minecraft-1.21.7" = _i1SVCoyS;
        "minecraft-1.21.8" = _i1SVCoyS;
        "minecraft-1.21.9" = _i1SVCoyS;
        "minecraft-1.21.10" = _i1SVCoyS;
        "minecraft-1.21.11" = _i1SVCoyS;
        "minecraft-26.1" = _i1SVCoyS;
        "minecraft-26.1.1" = _i1SVCoyS;
        "minecraft-26.1.2" = _i1SVCoyS;
        "default" = _i1SVCoyS;
    });
    fn = lib.prismnix.pkgs.mkVersionedModrinthPkgFn {
        name = "invisible-world-border";
        id = "pL8RrDwJ";
        type = "resourcepack";
        versions = versions;
        meta = {
            license = lib.getLicenseFromSpdxIdOr "CC0-1.0" {
                free = false;
                deprecated = false;
                redistributable = false;
                fullName = "Creative Commons Zero v1.0 Universal";
                shortName = "CC0-1.0";
                url = null;
            };
        };
    };
in callPackage fn {}