{lib, callPackage, ...}:
let
    versions = (let
        _xLK5Uv3u = {
            "id" = "xLK5Uv3u";
            "file" = "PVP CROSSHAIR 1.21.zip";
            "hash" = "sha512-tE9zYqQRlXmhvap6Vf0LITKgGYJBpcUKylFQnSLbOTDbbY5AAnLGZp5ARC0uy8jjiyweI4Pe2w9iGIRpWu3qFA==";
        };
        _bNyQVVB2 = {
            "id" = "bNyQVVB2";
            "file" = "PVP CROSSHAIR (2).zip";
            "hash" = "sha512-zYnRcx2y9Xbdv2x/1fFi8vs3wJ/eCGyfa5iHegCkiANyq8cBh17YrcbMv6JnqfRIClg4sF7SC+Y2SPisedz4gg==";
        };
        _kKTDuECr = {
            "id" = "kKTDuECr";
            "file" = "PVP CROSSHAIR 1.8-1.20.6.zip";
            "hash" = "sha512-EU5D2bIbbqfBeNyUrU/iYQBGqyOCMXMiAD9K2dcAEBvdjGqPUwlO14deFWzaQrb4A7UEp8JQtjSty81Rnrt6pw==";
        };
        _Bgg3WhQX = {
            "id" = "Bgg3WhQX";
            "file" = "PVP CROSSHAIR 1.21 - 26.1.2+.zip";
            "hash" = "sha512-9PHepzboZRrrRRXOcTOCxBipiBAk4jroPfMHWC2QJQqftx5jbNywcwMQz07HfH/fJW5olEaxG7LjamvQBIvB4A==";
        };
    in {
        "xLK5Uv3u" = _xLK5Uv3u;
        "bNyQVVB2" = _bNyQVVB2;
        "kKTDuECr" = _kKTDuECr;
        "Bgg3WhQX" = _Bgg3WhQX;
        "minecraft-1.21" = _Bgg3WhQX;
        "minecraft-1.21.1" = _Bgg3WhQX;
        "minecraft-1.21.2" = _Bgg3WhQX;
        "minecraft-1.21.3" = _Bgg3WhQX;
        "minecraft-1.21.4" = _Bgg3WhQX;
        "minecraft-1.21.5" = _Bgg3WhQX;
        "minecraft-1.8" = _kKTDuECr;
        "minecraft-1.8.1" = _kKTDuECr;
        "minecraft-1.8.2" = _kKTDuECr;
        "minecraft-1.8.3" = _kKTDuECr;
        "minecraft-1.8.4" = _kKTDuECr;
        "minecraft-1.8.5" = _kKTDuECr;
        "minecraft-1.8.6" = _kKTDuECr;
        "minecraft-1.8.7" = _kKTDuECr;
        "minecraft-1.8.8" = _kKTDuECr;
        "minecraft-1.8.9" = _kKTDuECr;
        "minecraft-1.9" = _kKTDuECr;
        "minecraft-1.9.1" = _kKTDuECr;
        "minecraft-1.9.2" = _kKTDuECr;
        "minecraft-1.9.3" = _kKTDuECr;
        "minecraft-1.9.4" = _kKTDuECr;
        "minecraft-1.10" = _kKTDuECr;
        "minecraft-1.10.1" = _kKTDuECr;
        "minecraft-1.10.2" = _kKTDuECr;
        "minecraft-1.11" = _kKTDuECr;
        "minecraft-1.11.1" = _kKTDuECr;
        "minecraft-1.11.2" = _kKTDuECr;
        "minecraft-1.12" = _kKTDuECr;
        "minecraft-1.12.1" = _kKTDuECr;
        "minecraft-1.12.2" = _kKTDuECr;
        "minecraft-1.13" = _kKTDuECr;
        "minecraft-1.13.1" = _kKTDuECr;
        "minecraft-1.13.2" = _kKTDuECr;
        "minecraft-1.14" = _kKTDuECr;
        "minecraft-1.14.1" = _kKTDuECr;
        "minecraft-1.14.2" = _kKTDuECr;
        "minecraft-1.14.3" = _kKTDuECr;
        "minecraft-1.14.4" = _kKTDuECr;
        "minecraft-1.15" = _kKTDuECr;
        "minecraft-1.15.1" = _kKTDuECr;
        "minecraft-1.15.2" = _kKTDuECr;
        "minecraft-1.16" = _kKTDuECr;
        "minecraft-1.16.1" = _kKTDuECr;
        "minecraft-1.16.2" = _kKTDuECr;
        "minecraft-1.16.3" = _kKTDuECr;
        "minecraft-1.16.4" = _kKTDuECr;
        "minecraft-1.16.5" = _kKTDuECr;
        "minecraft-1.17" = _kKTDuECr;
        "minecraft-1.17.1" = _kKTDuECr;
        "minecraft-1.18" = _kKTDuECr;
        "minecraft-1.18.1" = _kKTDuECr;
        "minecraft-1.18.2" = _kKTDuECr;
        "minecraft-1.19" = _kKTDuECr;
        "minecraft-1.19.1" = _kKTDuECr;
        "minecraft-1.19.2" = _kKTDuECr;
        "minecraft-1.19.3" = _kKTDuECr;
        "minecraft-1.19.4" = _kKTDuECr;
        "minecraft-1.20" = _kKTDuECr;
        "minecraft-1.20.1" = _kKTDuECr;
        "minecraft-1.20.2" = _kKTDuECr;
        "minecraft-1.20.3" = _kKTDuECr;
        "minecraft-1.20.4" = _kKTDuECr;
        "minecraft-1.20.5" = _kKTDuECr;
        "minecraft-1.20.6" = _kKTDuECr;
        "minecraft-23w31a" = _Bgg3WhQX;
        "minecraft-23w32a" = _Bgg3WhQX;
        "minecraft-23w33a" = _Bgg3WhQX;
        "minecraft-23w35a" = _Bgg3WhQX;
        "minecraft-1.20.2-pre1" = _Bgg3WhQX;
        "minecraft-23w42a" = _Bgg3WhQX;
        "minecraft-23w43a" = _Bgg3WhQX;
        "minecraft-23w43b" = _Bgg3WhQX;
        "minecraft-23w44a" = _Bgg3WhQX;
        "minecraft-23w45a" = _Bgg3WhQX;
        "minecraft-23w46a" = _Bgg3WhQX;
        "minecraft-24w03a" = _Bgg3WhQX;
        "minecraft-24w03b" = _Bgg3WhQX;
        "minecraft-24w04a" = _Bgg3WhQX;
        "minecraft-24w05a" = _Bgg3WhQX;
        "minecraft-24w05b" = _Bgg3WhQX;
        "minecraft-24w06a" = _Bgg3WhQX;
        "minecraft-24w07a" = _Bgg3WhQX;
        "minecraft-24w09a" = _Bgg3WhQX;
        "minecraft-24w10a" = _Bgg3WhQX;
        "minecraft-24w11a" = _Bgg3WhQX;
        "minecraft-24w12a" = _Bgg3WhQX;
        "minecraft-24w13a" = _Bgg3WhQX;
        "minecraft-24w14potato" = _Bgg3WhQX;
        "minecraft-24w14a" = _Bgg3WhQX;
        "minecraft-1.20.5-pre1" = _Bgg3WhQX;
        "minecraft-1.20.5-pre2" = _Bgg3WhQX;
        "minecraft-1.20.5-pre3" = _Bgg3WhQX;
        "minecraft-24w18a" = _Bgg3WhQX;
        "minecraft-24w19a" = _Bgg3WhQX;
        "minecraft-24w19b" = _Bgg3WhQX;
        "minecraft-24w20a" = _Bgg3WhQX;
        "minecraft-24w33a" = _Bgg3WhQX;
        "minecraft-24w34a" = _Bgg3WhQX;
        "minecraft-24w35a" = _Bgg3WhQX;
        "minecraft-24w36a" = _Bgg3WhQX;
        "minecraft-24w37a" = _Bgg3WhQX;
        "minecraft-24w38a" = _Bgg3WhQX;
        "minecraft-24w39a" = _Bgg3WhQX;
        "minecraft-24w40a" = _Bgg3WhQX;
        "minecraft-1.21.2-pre1" = _Bgg3WhQX;
        "minecraft-1.21.2-pre2" = _Bgg3WhQX;
        "minecraft-24w44a" = _Bgg3WhQX;
        "minecraft-24w45a" = _Bgg3WhQX;
        "minecraft-24w46a" = _Bgg3WhQX;
        "minecraft-1.21.6" = _Bgg3WhQX;
        "minecraft-1.21.7" = _Bgg3WhQX;
        "minecraft-1.21.8" = _Bgg3WhQX;
        "minecraft-1.21.9" = _Bgg3WhQX;
        "minecraft-1.21.10" = _Bgg3WhQX;
        "minecraft-1.21.11" = _Bgg3WhQX;
        "minecraft-26.1" = _Bgg3WhQX;
        "minecraft-26.1.1" = _Bgg3WhQX;
        "minecraft-26.1.2" = _Bgg3WhQX;
        "default" = _Bgg3WhQX;
    });
    fn = {stdenv, fetchurl, version, ...}:
        lib.prismnix.pkgs.mkVersionedModrinthPkg {
            inherit stdenv fetchurl;
            name = "pvp-crosshair.";
            id = "qCkkZMIo";
            type = "resourcepack";
            version = version;
            versions = versions;
            meta = {
                license = lib.getLicenseFromSpdxIdOr "LicenseRef-All-Rights-Reserved" {
                    free = false;
                    deprecated = false;
                    redistributable = false;
                    fullName = "LicenseRef-All-Rights-Reserved";
                    shortName = "LicenseRef-All-Rights-Reserved";
                    url = null;
                };
            };
        };
in callPackage fn {version="default";}