{lib, callPackage, ...}:
let
    versions = (let
        _wRWiwNGQ = {
            "id" = "wRWiwNGQ";
            "file" = "Bare Bones Plus v1.0.0.zip";
            "hash" = "sha512-hvqVqjp1ug0AXcQdZ2Lu/+Bn3uhfpGGTzCWrDj/xbunKH1hAljz16JAFw1dTFwt5Tgog5aEpg2aikMhS6vw/qA==";
        };
        _68Dxv2br = {
            "id" = "68Dxv2br";
            "file" = "Bare Bones Plus v1.0.1.zip";
            "hash" = "sha512-BP8obC5yKzqsulyFlYHbLN6pwwLU+NdbW8dUd0/F9vcKinpP//OQZvZW8Ahl16QQOPK3W1PvpuO/cD+vrFMvGA==";
        };
        _Eucyfplm = {
            "id" = "Eucyfplm";
            "file" = "Bare Bones Plus v1.0.2.zip";
            "hash" = "sha512-zbJXHlviA3mJqcbLYo0CJwgDsJB0Wno+3Y3tbcwjOnWzeeZQQjjpfedddbPwMCY0QHrCIxpEUbhsfx66BL407Q==";
        };
    in {
        "wRWiwNGQ" = _wRWiwNGQ;
        "68Dxv2br" = _68Dxv2br;
        "Eucyfplm" = _Eucyfplm;
        "minecraft-1.12" = _Eucyfplm;
        "minecraft-1.12.1" = _Eucyfplm;
        "minecraft-1.12.2" = _Eucyfplm;
        "minecraft-1.13" = _Eucyfplm;
        "minecraft-1.13.1" = _Eucyfplm;
        "minecraft-1.13.2" = _Eucyfplm;
        "minecraft-1.14" = _Eucyfplm;
        "minecraft-1.14.1" = _Eucyfplm;
        "minecraft-1.14.2" = _Eucyfplm;
        "minecraft-1.14.3" = _Eucyfplm;
        "minecraft-1.14.4" = _Eucyfplm;
        "minecraft-1.15" = _Eucyfplm;
        "minecraft-1.15.1" = _Eucyfplm;
        "minecraft-1.15.2" = _Eucyfplm;
        "minecraft-1.16" = _Eucyfplm;
        "minecraft-1.16.1" = _Eucyfplm;
        "minecraft-1.16.2" = _Eucyfplm;
        "minecraft-1.16.3" = _Eucyfplm;
        "minecraft-1.16.4" = _Eucyfplm;
        "minecraft-1.16.5" = _Eucyfplm;
        "minecraft-1.17" = _Eucyfplm;
        "minecraft-1.17.1" = _Eucyfplm;
        "minecraft-1.18" = _Eucyfplm;
        "minecraft-1.18.1" = _Eucyfplm;
        "minecraft-1.18.2" = _Eucyfplm;
        "minecraft-1.19" = _Eucyfplm;
        "minecraft-1.19.1" = _Eucyfplm;
        "minecraft-1.19.2" = _Eucyfplm;
        "minecraft-1.19.3" = _Eucyfplm;
        "minecraft-1.19.4" = _Eucyfplm;
        "minecraft-1.20" = _Eucyfplm;
        "minecraft-1.20.1" = _Eucyfplm;
        "minecraft-1.20.2" = _Eucyfplm;
        "minecraft-1.20.3" = _Eucyfplm;
        "minecraft-1.20.4" = _Eucyfplm;
        "minecraft-1.20.5" = _Eucyfplm;
        "minecraft-1.20.6" = _Eucyfplm;
        "minecraft-1.21" = _Eucyfplm;
        "minecraft-1.21.1" = _Eucyfplm;
        "minecraft-1.21.2" = _Eucyfplm;
        "minecraft-1.21.3" = _Eucyfplm;
        "minecraft-1.21.4" = _Eucyfplm;
        "minecraft-1.21.5" = _Eucyfplm;
        "minecraft-1.6.1" = _Eucyfplm;
        "minecraft-1.6.2" = _Eucyfplm;
        "minecraft-1.6.4" = _Eucyfplm;
        "minecraft-1.7.2" = _Eucyfplm;
        "minecraft-1.7.3" = _Eucyfplm;
        "minecraft-1.7.4" = _Eucyfplm;
        "minecraft-1.7.5" = _Eucyfplm;
        "minecraft-1.7.6" = _Eucyfplm;
        "minecraft-1.7.7" = _Eucyfplm;
        "minecraft-1.7.8" = _Eucyfplm;
        "minecraft-1.7.9" = _Eucyfplm;
        "minecraft-1.7.10" = _Eucyfplm;
        "minecraft-1.8" = _Eucyfplm;
        "minecraft-1.8.1" = _Eucyfplm;
        "minecraft-1.8.2" = _Eucyfplm;
        "minecraft-1.8.3" = _Eucyfplm;
        "minecraft-1.8.4" = _Eucyfplm;
        "minecraft-1.8.5" = _Eucyfplm;
        "minecraft-1.8.6" = _Eucyfplm;
        "minecraft-1.8.7" = _Eucyfplm;
        "minecraft-1.8.8" = _Eucyfplm;
        "minecraft-1.8.9" = _Eucyfplm;
        "minecraft-1.9" = _Eucyfplm;
        "minecraft-1.9.1" = _Eucyfplm;
        "minecraft-1.9.2" = _Eucyfplm;
        "minecraft-1.9.3" = _Eucyfplm;
        "minecraft-1.9.4" = _Eucyfplm;
        "minecraft-1.10" = _Eucyfplm;
        "minecraft-1.10.1" = _Eucyfplm;
        "minecraft-1.10.2" = _Eucyfplm;
        "minecraft-1.11" = _Eucyfplm;
        "minecraft-1.11.1" = _Eucyfplm;
        "minecraft-1.11.2" = _Eucyfplm;
        "minecraft-1.21.6" = _Eucyfplm;
        "minecraft-1.21.7" = _Eucyfplm;
        "minecraft-1.21.8" = _Eucyfplm;
        "minecraft-1.21.9" = _Eucyfplm;
        "minecraft-1.21.10" = _Eucyfplm;
        "minecraft-1.21.11" = _Eucyfplm;
        "pkg-v1.0.0" = _wRWiwNGQ;
        "pkg-v1.0.1" = _68Dxv2br;
        "pkg-v1.0.2" = _Eucyfplm;
        "default" = _Eucyfplm;
    });
    fn = lib.prismnix.pkgs.mkVersionedModrinthPkgFn {
        name = "bare-bones-plus";
        id = "ucW2PdGM";
        type = "resourcepack";
        versions = versions;
        meta = {
            license = lib.getLicenseFromSpdxIdOr "LicenseRef-All-Rights-Reserved" {
                free = false;
                deprecated = false;
                redistributable = false;
                fullName = "LicenseRef-All-Rights-Reserved";
                shortName = "LicenseRef-All-Rights-Reserved";
                url = null;
            };
        };
    };
in callPackage fn {}