{lib, callPackage, ...}:
let
    versions = (let
        _aAgnQwlc = {
            "id" = "aAgnQwlc";
            "file" = "CraftFlowers-1.1.0.jar";
            "hash" = "sha512-4dVVJtixYHKlTVMMyRCkoeUEnh6PezaCBchL9pSAL2gEKJ8TlUe4grbDJrnUtcgCLwgKr/N9AbffMyU80B91ew==";
        };
        _8AI4yj4j = {
            "id" = "8AI4yj4j";
            "file" = "CraftFlowers-1.2.0-all.jar";
            "hash" = "sha512-epBTa5lzRsWTGWIuDkvOy8egutvuR0UYbY72Yr4SYkqQnOnM/un/XwE8BVeWx7F7gYToUYO7kPxo1Iz6QnCOmQ==";
        };
        _WNeE7uzr = {
            "id" = "WNeE7uzr";
            "file" = "CraftFlowers-1.2.1-all.jar";
            "hash" = "sha512-IPHioeHKUVvfMIKqhx4gc58Yg57yaARLfNIGB02xzCTTZxGs+0YHzhn8cOWEOBYBHffIG2OqP5o9PBqhi6dxqw==";
        };
        _zyCyj7Qq = {
            "id" = "zyCyj7Qq";
            "file" = "CraftFlowers-1.2.2.jar";
            "hash" = "sha512-ZYZ9+1I9LcJ2kO4vSt2tjAWt0Tx13LI6y/LpDIf11U7gWdoJjSg+kSrYuGFbKF6upkyaW3/EMGwyLGZpPhyGqg==";
        };
        _Ktq3AtNU = {
            "id" = "Ktq3AtNU";
            "file" = "CraftFlowers-1.2.3.jar";
            "hash" = "sha512-vhvPHMYUamQHkOmNR1rBoAy0xuHYQJZyuLCJFfXjC+94iZ6d3T2KypG9hXmYu0ddi4iU+AGH0g8XavvNR4HeBw==";
        };
        _zkl2AgIG = {
            "id" = "zkl2AgIG";
            "file" = "CraftFlowers-1.2.4.jar";
            "hash" = "sha512-mCreEqLKhFLuzsQtvXCoKZisQshJhxsS46c7LPij58zAyOX4qtGeSrj7F5GJb1tN2xxu5dumkypnENIJmcau0A==";
        };
        _JRSZeOJR = {
            "id" = "JRSZeOJR";
            "file" = "CraftFlowers-1.2.5-all.jar";
            "hash" = "sha512-YBzjxqKGygAZ3aSEWCXU/rvsc5o9ZKebLouD1YLMfrPkV98A4+7XEuzr8qZCvVkMHv5Srapv99ZgJrsrvZQnRg==";
        };
    in {
        "aAgnQwlc" = _aAgnQwlc;
        "8AI4yj4j" = _8AI4yj4j;
        "WNeE7uzr" = _WNeE7uzr;
        "zyCyj7Qq" = _zyCyj7Qq;
        "Ktq3AtNU" = _Ktq3AtNU;
        "zkl2AgIG" = _zkl2AgIG;
        "JRSZeOJR" = _JRSZeOJR;
        "paper-1.16.5" = _JRSZeOJR;
        "paper-1.17" = _JRSZeOJR;
        "paper-1.18" = _JRSZeOJR;
        "paper-1.19" = _JRSZeOJR;
        "paper-1.16.4" = _JRSZeOJR;
        "paper-1.17.1" = _JRSZeOJR;
        "paper-1.18.1" = _JRSZeOJR;
        "paper-1.18.2" = _JRSZeOJR;
        "paper-1.19.1" = _JRSZeOJR;
        "paper-1.19.2" = _JRSZeOJR;
        "paper-1.19.3" = _JRSZeOJR;
        "paper-1.16" = _JRSZeOJR;
        "paper-1.16.1" = _JRSZeOJR;
        "paper-1.16.2" = _JRSZeOJR;
        "paper-1.16.3" = _JRSZeOJR;
        "paper-1.19.4" = _JRSZeOJR;
        "paper-1.20" = _JRSZeOJR;
        "paper-1.20.1" = _JRSZeOJR;
        "paper-1.20.2" = _JRSZeOJR;
        "paper-1.20.3" = _JRSZeOJR;
        "paper-1.20.4" = _JRSZeOJR;
        "paper-1.20.5" = _JRSZeOJR;
        "paper-1.20.6" = _JRSZeOJR;
        "paper-1.21" = _JRSZeOJR;
        "paper-1.21.1" = _JRSZeOJR;
        "paper-1.21.2" = _JRSZeOJR;
        "paper-1.21.3" = _JRSZeOJR;
        "paper-1.21.4" = _JRSZeOJR;
        "purpur-1.16.5" = _JRSZeOJR;
        "purpur-1.17" = _JRSZeOJR;
        "purpur-1.18" = _JRSZeOJR;
        "purpur-1.19" = _JRSZeOJR;
        "purpur-1.16.4" = _JRSZeOJR;
        "purpur-1.17.1" = _JRSZeOJR;
        "purpur-1.18.1" = _JRSZeOJR;
        "purpur-1.18.2" = _JRSZeOJR;
        "purpur-1.19.1" = _JRSZeOJR;
        "purpur-1.19.2" = _JRSZeOJR;
        "purpur-1.19.3" = _JRSZeOJR;
        "purpur-1.16" = _JRSZeOJR;
        "purpur-1.16.1" = _JRSZeOJR;
        "purpur-1.16.2" = _JRSZeOJR;
        "purpur-1.16.3" = _JRSZeOJR;
        "purpur-1.19.4" = _JRSZeOJR;
        "purpur-1.20" = _JRSZeOJR;
        "purpur-1.20.1" = _JRSZeOJR;
        "purpur-1.20.2" = _JRSZeOJR;
        "purpur-1.20.3" = _JRSZeOJR;
        "purpur-1.20.4" = _JRSZeOJR;
        "purpur-1.20.5" = _JRSZeOJR;
        "purpur-1.20.6" = _JRSZeOJR;
        "purpur-1.21" = _JRSZeOJR;
        "purpur-1.21.1" = _JRSZeOJR;
        "purpur-1.21.2" = _JRSZeOJR;
        "purpur-1.21.3" = _JRSZeOJR;
        "purpur-1.21.4" = _JRSZeOJR;
        "spigot-1.16.5" = _JRSZeOJR;
        "spigot-1.17" = _JRSZeOJR;
        "spigot-1.18" = _JRSZeOJR;
        "spigot-1.19" = _JRSZeOJR;
        "spigot-1.16.4" = _JRSZeOJR;
        "spigot-1.17.1" = _JRSZeOJR;
        "spigot-1.18.1" = _JRSZeOJR;
        "spigot-1.18.2" = _JRSZeOJR;
        "spigot-1.19.1" = _JRSZeOJR;
        "spigot-1.19.2" = _JRSZeOJR;
        "spigot-1.19.3" = _JRSZeOJR;
        "spigot-1.16" = _JRSZeOJR;
        "spigot-1.16.1" = _JRSZeOJR;
        "spigot-1.16.2" = _JRSZeOJR;
        "spigot-1.16.3" = _JRSZeOJR;
        "spigot-1.19.4" = _JRSZeOJR;
        "spigot-1.20" = _JRSZeOJR;
        "spigot-1.20.1" = _JRSZeOJR;
        "spigot-1.20.2" = _JRSZeOJR;
        "spigot-1.20.3" = _JRSZeOJR;
        "spigot-1.20.4" = _JRSZeOJR;
        "spigot-1.20.5" = _JRSZeOJR;
        "spigot-1.20.6" = _JRSZeOJR;
        "spigot-1.21" = _JRSZeOJR;
        "spigot-1.21.1" = _JRSZeOJR;
        "spigot-1.21.2" = _JRSZeOJR;
        "spigot-1.21.3" = _JRSZeOJR;
        "spigot-1.21.4" = _JRSZeOJR;
        "bukkit-1.16" = _JRSZeOJR;
        "bukkit-1.16.1" = _JRSZeOJR;
        "bukkit-1.16.2" = _JRSZeOJR;
        "bukkit-1.16.3" = _JRSZeOJR;
        "bukkit-1.16.4" = _JRSZeOJR;
        "bukkit-1.16.5" = _JRSZeOJR;
        "bukkit-1.17" = _JRSZeOJR;
        "bukkit-1.17.1" = _JRSZeOJR;
        "bukkit-1.18" = _JRSZeOJR;
        "bukkit-1.18.1" = _JRSZeOJR;
        "bukkit-1.18.2" = _JRSZeOJR;
        "bukkit-1.19" = _JRSZeOJR;
        "bukkit-1.19.1" = _JRSZeOJR;
        "bukkit-1.19.2" = _JRSZeOJR;
        "bukkit-1.19.3" = _JRSZeOJR;
        "bukkit-1.19.4" = _JRSZeOJR;
        "bukkit-1.20" = _JRSZeOJR;
        "bukkit-1.20.1" = _JRSZeOJR;
        "bukkit-1.20.2" = _JRSZeOJR;
        "bukkit-1.20.3" = _JRSZeOJR;
        "bukkit-1.20.4" = _JRSZeOJR;
        "bukkit-1.20.5" = _JRSZeOJR;
        "bukkit-1.20.6" = _JRSZeOJR;
        "bukkit-1.21" = _JRSZeOJR;
        "bukkit-1.21.1" = _JRSZeOJR;
        "bukkit-1.21.2" = _JRSZeOJR;
        "bukkit-1.21.3" = _JRSZeOJR;
        "bukkit-1.21.4" = _JRSZeOJR;
        "default" = _JRSZeOJR;
    });
    fn = lib.prismnix.pkgs.mkVersionedModrinthPkgFn {
        name = "craftflowers";
        id = "UMNFTVtr";
        type = "mod";
        versions = versions;
        meta = {
            license = lib.getLicenseFromSpdxIdOr "MIT" {
                free = false;
                deprecated = false;
                redistributable = false;
                fullName = "MIT License";
                shortName = "MIT";
                url = null;
            };
        };
    };
in callPackage fn {}