{lib, callPackage, ...}:
let
    versions = (let
        _sfdYbaxH = {
            "id" = "sfdYbaxH";
            "file" = "More-Kills-More-Damage-v1.0.zip";
            "hash" = "sha512-VT9oHi5Pi8O/hdgLVAjkpgVgDR/csm7Pm977nczgvOw3/5Pf8UPMWtLXTQGqgZr7AgHbJyNvyAbRoj8TSyKjCg==";
        };
        _ctDFIIwL = {
            "id" = "ctDFIIwL";
            "file" = "more-kills-more-damage-v1.0.jar";
            "hash" = "sha512-u4nw2breiXhO5ReJPmWxgHaqz/jb6yhbhRa/I5AMsjH5FUjy2xsTlfSTTd/88Krj6H7wfqeJYmaScSxP16A4Gg==";
        };
        _yrHLnfVp = {
            "id" = "yrHLnfVp";
            "file" = "More-Kills-More-Damage-1.0.1.zip";
            "hash" = "sha512-xhP+pvTxqMHB+IPhCyBr42VQOgNQejgVajvekKjYs6mZM4hyGRRBfEvRM7eNw/28DqT4P4ucB5NgtmqtDeIhNA==";
        };
        _HOGDRqwf = {
            "id" = "HOGDRqwf";
            "file" = "more-kills-more-damage-v1.0.1.jar";
            "hash" = "sha512-+0YGLhQjWa2nM3j81CKStKSxBN6C1dl0ChL6ihy0sXgIveNwv4PNWPbGhRwddlKq+41KL9gCUXLOO3j+WG9kxg==";
        };
    in {
        "sfdYbaxH" = _sfdYbaxH;
        "ctDFIIwL" = _ctDFIIwL;
        "yrHLnfVp" = _yrHLnfVp;
        "HOGDRqwf" = _HOGDRqwf;
        "datapack-1.20.2" = _yrHLnfVp;
        "datapack-1.20.3" = _yrHLnfVp;
        "datapack-1.20.4" = _yrHLnfVp;
        "datapack-1.20.5" = _yrHLnfVp;
        "datapack-1.20.6" = _yrHLnfVp;
        "datapack-1.21" = _yrHLnfVp;
        "datapack-1.21.1" = _yrHLnfVp;
        "datapack-1.21.2" = _yrHLnfVp;
        "datapack-1.21.3" = _yrHLnfVp;
        "datapack-1.21.4" = _yrHLnfVp;
        "datapack-1.21.5" = _yrHLnfVp;
        "datapack-1.21.6" = _yrHLnfVp;
        "datapack-1.21.7" = _yrHLnfVp;
        "datapack-1.21.8" = _yrHLnfVp;
        "datapack-1.21.9" = _yrHLnfVp;
        "datapack-1.21.10" = _yrHLnfVp;
        "datapack-1.21.11" = _yrHLnfVp;
        "datapack-26.1" = _yrHLnfVp;
        "datapack-26.1.1" = _yrHLnfVp;
        "datapack-26.1.2" = _yrHLnfVp;
        "datapack-26.2" = _yrHLnfVp;
        "fabric-1.20.2" = _HOGDRqwf;
        "fabric-1.20.3" = _HOGDRqwf;
        "fabric-1.20.4" = _HOGDRqwf;
        "fabric-1.20.5" = _HOGDRqwf;
        "fabric-1.20.6" = _HOGDRqwf;
        "fabric-1.21" = _HOGDRqwf;
        "fabric-1.21.1" = _HOGDRqwf;
        "fabric-1.21.2" = _HOGDRqwf;
        "fabric-1.21.3" = _HOGDRqwf;
        "fabric-1.21.4" = _HOGDRqwf;
        "fabric-1.21.5" = _HOGDRqwf;
        "fabric-1.21.6" = _HOGDRqwf;
        "fabric-1.21.7" = _HOGDRqwf;
        "fabric-1.21.8" = _HOGDRqwf;
        "fabric-1.21.9" = _HOGDRqwf;
        "fabric-1.21.10" = _HOGDRqwf;
        "fabric-1.21.11" = _HOGDRqwf;
        "fabric-26.1" = _HOGDRqwf;
        "fabric-26.1.1" = _HOGDRqwf;
        "fabric-26.1.2" = _HOGDRqwf;
        "fabric-26.2" = _HOGDRqwf;
        "forge-1.20.2" = _HOGDRqwf;
        "forge-1.20.3" = _HOGDRqwf;
        "forge-1.20.4" = _HOGDRqwf;
        "forge-1.20.5" = _HOGDRqwf;
        "forge-1.20.6" = _HOGDRqwf;
        "forge-1.21" = _HOGDRqwf;
        "forge-1.21.1" = _HOGDRqwf;
        "forge-1.21.2" = _HOGDRqwf;
        "forge-1.21.3" = _HOGDRqwf;
        "forge-1.21.4" = _HOGDRqwf;
        "forge-1.21.5" = _HOGDRqwf;
        "forge-1.21.6" = _HOGDRqwf;
        "forge-1.21.7" = _HOGDRqwf;
        "forge-1.21.8" = _HOGDRqwf;
        "forge-1.21.9" = _HOGDRqwf;
        "forge-1.21.10" = _HOGDRqwf;
        "forge-1.21.11" = _HOGDRqwf;
        "forge-26.1" = _HOGDRqwf;
        "forge-26.1.1" = _HOGDRqwf;
        "forge-26.1.2" = _HOGDRqwf;
        "forge-26.2" = _HOGDRqwf;
        "neoforge-1.20.2" = _HOGDRqwf;
        "neoforge-1.20.3" = _HOGDRqwf;
        "neoforge-1.20.4" = _HOGDRqwf;
        "neoforge-1.20.5" = _HOGDRqwf;
        "neoforge-1.20.6" = _HOGDRqwf;
        "neoforge-1.21" = _HOGDRqwf;
        "neoforge-1.21.1" = _HOGDRqwf;
        "neoforge-1.21.2" = _HOGDRqwf;
        "neoforge-1.21.3" = _HOGDRqwf;
        "neoforge-1.21.4" = _HOGDRqwf;
        "neoforge-1.21.5" = _HOGDRqwf;
        "neoforge-1.21.6" = _HOGDRqwf;
        "neoforge-1.21.7" = _HOGDRqwf;
        "neoforge-1.21.8" = _HOGDRqwf;
        "neoforge-1.21.9" = _HOGDRqwf;
        "neoforge-1.21.10" = _HOGDRqwf;
        "neoforge-1.21.11" = _HOGDRqwf;
        "neoforge-26.1" = _HOGDRqwf;
        "neoforge-26.1.1" = _HOGDRqwf;
        "neoforge-26.1.2" = _HOGDRqwf;
        "neoforge-26.2" = _HOGDRqwf;
        "quilt-1.20.2" = _HOGDRqwf;
        "quilt-1.20.3" = _HOGDRqwf;
        "quilt-1.20.4" = _HOGDRqwf;
        "quilt-1.20.5" = _HOGDRqwf;
        "quilt-1.20.6" = _HOGDRqwf;
        "quilt-1.21" = _HOGDRqwf;
        "quilt-1.21.1" = _HOGDRqwf;
        "quilt-1.21.2" = _HOGDRqwf;
        "quilt-1.21.3" = _HOGDRqwf;
        "quilt-1.21.4" = _HOGDRqwf;
        "quilt-1.21.5" = _HOGDRqwf;
        "quilt-1.21.6" = _HOGDRqwf;
        "quilt-1.21.7" = _HOGDRqwf;
        "quilt-1.21.8" = _HOGDRqwf;
        "quilt-1.21.9" = _HOGDRqwf;
        "quilt-1.21.10" = _HOGDRqwf;
        "quilt-1.21.11" = _HOGDRqwf;
        "quilt-26.1" = _HOGDRqwf;
        "quilt-26.1.1" = _HOGDRqwf;
        "quilt-26.1.2" = _HOGDRqwf;
        "quilt-26.2" = _HOGDRqwf;
        "default" = _HOGDRqwf;
    });
    fn = {stdenv, fetchurl, version, ...}:
        lib.prismnix.pkgs.mkVersionedModrinthPkg {
            inherit stdenv fetchurl;
            name = "more-kills-more-damage";
            id = "vzMutOip";
            type = "mod";
            version = version;
            versions = versions;
            meta = {
                license = lib.getLicenseFromSpdxIdOr "MIT" {
                    free = false;
                    deprecated = false;
                    redistributable = false;
                    fullName = "MIT License";
                    shortName = "MIT";
                    url = null;
                };
            };
        };
in callPackage fn {version="default";}