{lib, callPackage, ...}:
let
    versions = (let
        _Nz1njMYb = {
            "id" = "Nz1njMYb";
            "file" = "NWLDiscord-1.0.0.jar";
            "hash" = "sha512-7Hyb0E7VEp2jWStkO3TLB/IA3ofLsn24sfnIPxxWusrR/4DIrNTuAfSVM3X/WBnG+kbqoRx2+TnZSiOIli6/4w==";
        };
        _Vmwjzry2 = {
            "id" = "Vmwjzry2";
            "file" = "NWLDiscord-1.0.1.jar";
            "hash" = "sha512-RIoyky27iUL9Z0uD/zTVUA8gSf3O4/LwAEazaE93Dm7V8VXc/idKuKQmvUrERQRreTBJHQMfvYjD3wUt2jAjug==";
        };
        _DTFPxLxr = {
            "id" = "DTFPxLxr";
            "file" = "NWLDiscord-1.0.2.jar";
            "hash" = "sha512-8JVjoQ6IGRWLrYEeQZdxmP80wAC+9u7WyuPfsc4QaHdpUXiG2Qglj6QKN8CO4acfk7q0fc8YKAQy+d3lHutgbQ==";
        };
        _eppPiSJg = {
            "id" = "eppPiSJg";
            "file" = "NWLDiscord-1.1.0.jar";
            "hash" = "sha512-Tjo+SI6DZCMNA2jDqnuGYZDlXYBOy9uAyOF6Hv7x5jSluoBn3B6Y9XQE+l/Cy0Fjp26v9B4VUO/na38pC6qgWg==";
        };
        _DEg1IP9O = {
            "id" = "DEg1IP9O";
            "file" = "NWLDiscord-1.1.1.jar";
            "hash" = "sha512-V9kfOeGOXWNr48kc3PrPKW4JmxkSNvbKLJuCMLLg4yKhMFclCpEk8UaXgEzbAwYWSCDIltZ2oBWXyvwf4MQYvA==";
        };
        _4SdprhCl = {
            "id" = "4SdprhCl";
            "file" = "NWLDiscord-1.1.2.jar";
            "hash" = "sha512-OnxMjGX947rpADHYQQcdgyg5+LgBA3VtBM7zPf7DoT+W0shCgRLLrwH/Xqr0FaFCNsOjGzbb3M4Etp0lwVzKCA==";
        };
        _fTA6vWZ1 = {
            "id" = "fTA6vWZ1";
            "file" = "NWLDiscord-1.1.3.jar";
            "hash" = "sha512-tMugZGkdL2xMi93zRVbfaChSLtKgYC0zUum37qFg/GRYbzfjOxd+y+Jw9qtLSwhWa3RRUCGhSCQWyymxoPBImQ==";
        };
        _qEM0dRBJ = {
            "id" = "qEM0dRBJ";
            "file" = "NWLDiscord-1.1.4.jar";
            "hash" = "sha512-iuNzxWT9+XGlTMr3ozJnWd6gr/6T7UDYMQQO7LDk5jB7cp8jozwqoCq0hwj++f7OWIvNZheyG1v44WTe4aZrfA==";
        };
        _s7qj8PwL = {
            "id" = "s7qj8PwL";
            "file" = "NWLDiscord-1.1.5.jar";
            "hash" = "sha512-zN++t6aEJKe2vVcsRApzCf5Ho5gbihJPt7O0OFlVJ+qUiU+E2SLcF7O69CvZ6XmeqvBRCBRJaLGLXIWhzoB/Ew==";
        };
        _ph1PTM6r = {
            "id" = "ph1PTM6r";
            "file" = "NWLDiscord-1.1.6.jar";
            "hash" = "sha512-N1lWA1iv/eqhMzMMjarEKtrwe363RpF6Aa4cOYP0iskLCbRszidYM/zXbwLq3pq/vJLtITjp55ZAhQUVxYW9AA==";
        };
        _NSakQVR5 = {
            "id" = "NSakQVR5";
            "file" = "NWLDiscord-1.1.7.jar";
            "hash" = "sha512-tcs2O24SG/0qBaDE93qvKIWU1bh5XqrKfWEf3WUPae6qg2irf6RlbWs91c8KaaOZK+tiNAGAFFkWSylSHA92BQ==";
        };
        _QAehKdcy = {
            "id" = "QAehKdcy";
            "file" = "NWLDiscord-1.1.8.jar";
            "hash" = "sha512-ACS3IGHV+MTtJBiHhrBevlf6FWs7bL5HMItdwQ9RoK0nocSNPTPG10ygZaotqJW1tZNB4sPAEI3kfYsRMUDBLw==";
        };
        _6Dv2KPTC = {
            "id" = "6Dv2KPTC";
            "file" = "NWLDiscord-1.1.9.jar";
            "hash" = "sha512-3d8BHQqnMWo1oP/en7XpmF7icReRizUWP1UwWHsSmceDqrnY0gb+PRMsbG3fs2HCMwNeOgKCF1ngJPh6CuHU2g==";
        };
        _mIcwURRj = {
            "id" = "mIcwURRj";
            "file" = "NWLDiscord-1.1.10.jar";
            "hash" = "sha512-Sln59vd7VjUSUvDfm6HG6ecWeA2BLuuSBVQMaTcMpzNWMNJseGIq7yD6vzWdndhvYwQUbEMUDT7lTyej0qle7A==";
        };
        _2QQp72xa = {
            "id" = "2QQp72xa";
            "file" = "NWLDiscord-1.1.11.jar";
            "hash" = "sha512-vyW9AWGVHqKklmoMVOHt7k2V/NG3J781Fa4P+qxX9vfmarUo5h85XqL27cuyK+JakWwcA+YAuN6JK6D7ec8Wgw==";
        };
        _LgXvQMIp = {
            "id" = "LgXvQMIp";
            "file" = "NWLDiscord-1.1.12.jar";
            "hash" = "sha512-M4Y3L46aiB+yzcYABD1QWe8AB8OPxOwnnSvgEn8XhcuYgGbIlDROQ/CsN6C1Z94ccLwPSrCiwNRNUSlPCpsoYg==";
        };
    in {
        "Nz1njMYb" = _Nz1njMYb;
        "Vmwjzry2" = _Vmwjzry2;
        "DTFPxLxr" = _DTFPxLxr;
        "eppPiSJg" = _eppPiSJg;
        "DEg1IP9O" = _DEg1IP9O;
        "4SdprhCl" = _4SdprhCl;
        "fTA6vWZ1" = _fTA6vWZ1;
        "qEM0dRBJ" = _qEM0dRBJ;
        "s7qj8PwL" = _s7qj8PwL;
        "ph1PTM6r" = _ph1PTM6r;
        "NSakQVR5" = _NSakQVR5;
        "QAehKdcy" = _QAehKdcy;
        "6Dv2KPTC" = _6Dv2KPTC;
        "mIcwURRj" = _mIcwURRj;
        "2QQp72xa" = _2QQp72xa;
        "LgXvQMIp" = _LgXvQMIp;
        "paper-1.17" = _s7qj8PwL;
        "paper-1.17.1" = _s7qj8PwL;
        "paper-1.18" = _LgXvQMIp;
        "paper-1.18.1" = _LgXvQMIp;
        "paper-1.18.2" = _LgXvQMIp;
        "paper-1.19" = _LgXvQMIp;
        "paper-1.19.1" = _LgXvQMIp;
        "paper-1.19.2" = _LgXvQMIp;
        "paper-1.19.3" = _LgXvQMIp;
        "paper-1.19.4" = _LgXvQMIp;
        "paper-1.20" = _LgXvQMIp;
        "paper-1.20.1" = _LgXvQMIp;
        "paper-1.20.2" = _LgXvQMIp;
        "paper-1.20.3" = _LgXvQMIp;
        "paper-1.20.4" = _LgXvQMIp;
        "paper-1.20.5" = _LgXvQMIp;
        "paper-1.20.6" = _LgXvQMIp;
        "paper-1.21" = _LgXvQMIp;
        "paper-1.21.1" = _LgXvQMIp;
        "paper-1.21.2" = _LgXvQMIp;
        "paper-1.21.3" = _LgXvQMIp;
        "paper-1.21.4" = _LgXvQMIp;
        "paper-1.21.5" = _LgXvQMIp;
        "paper-1.21.6" = _LgXvQMIp;
        "paper-1.21.7" = _LgXvQMIp;
        "paper-1.21.8" = _LgXvQMIp;
        "paper-1.21.9" = _LgXvQMIp;
        "paper-1.21.10" = _LgXvQMIp;
        "paper-1.21.11" = _LgXvQMIp;
        "paper-26.1" = _LgXvQMIp;
        "paper-26.1.1" = _LgXvQMIp;
        "paper-26.1.2" = _LgXvQMIp;
        "purpur-1.17" = _s7qj8PwL;
        "purpur-1.17.1" = _s7qj8PwL;
        "purpur-1.18" = _LgXvQMIp;
        "purpur-1.18.1" = _LgXvQMIp;
        "purpur-1.18.2" = _LgXvQMIp;
        "purpur-1.19" = _LgXvQMIp;
        "purpur-1.19.1" = _LgXvQMIp;
        "purpur-1.19.2" = _LgXvQMIp;
        "purpur-1.19.3" = _LgXvQMIp;
        "purpur-1.19.4" = _LgXvQMIp;
        "purpur-1.20" = _LgXvQMIp;
        "purpur-1.20.1" = _LgXvQMIp;
        "purpur-1.20.2" = _LgXvQMIp;
        "purpur-1.20.3" = _LgXvQMIp;
        "purpur-1.20.4" = _LgXvQMIp;
        "purpur-1.20.5" = _LgXvQMIp;
        "purpur-1.20.6" = _LgXvQMIp;
        "purpur-1.21" = _LgXvQMIp;
        "purpur-1.21.1" = _LgXvQMIp;
        "purpur-1.21.2" = _LgXvQMIp;
        "purpur-1.21.3" = _LgXvQMIp;
        "purpur-1.21.4" = _LgXvQMIp;
        "purpur-1.21.5" = _LgXvQMIp;
        "purpur-1.21.6" = _LgXvQMIp;
        "purpur-1.21.7" = _LgXvQMIp;
        "purpur-1.21.8" = _LgXvQMIp;
        "purpur-1.21.9" = _LgXvQMIp;
        "purpur-1.21.10" = _LgXvQMIp;
        "purpur-1.21.11" = _LgXvQMIp;
        "purpur-26.1" = _LgXvQMIp;
        "purpur-26.1.1" = _LgXvQMIp;
        "purpur-26.1.2" = _LgXvQMIp;
        "spigot-1.17" = _s7qj8PwL;
        "spigot-1.17.1" = _s7qj8PwL;
        "spigot-1.18" = _LgXvQMIp;
        "spigot-1.18.1" = _LgXvQMIp;
        "spigot-1.18.2" = _LgXvQMIp;
        "spigot-1.19" = _LgXvQMIp;
        "spigot-1.19.1" = _LgXvQMIp;
        "spigot-1.19.2" = _LgXvQMIp;
        "spigot-1.19.3" = _LgXvQMIp;
        "spigot-1.19.4" = _LgXvQMIp;
        "spigot-1.20" = _LgXvQMIp;
        "spigot-1.20.1" = _LgXvQMIp;
        "spigot-1.20.2" = _LgXvQMIp;
        "spigot-1.20.3" = _LgXvQMIp;
        "spigot-1.20.4" = _LgXvQMIp;
        "spigot-1.20.5" = _LgXvQMIp;
        "spigot-1.20.6" = _LgXvQMIp;
        "spigot-1.21" = _LgXvQMIp;
        "spigot-1.21.1" = _LgXvQMIp;
        "spigot-1.21.2" = _LgXvQMIp;
        "spigot-1.21.3" = _LgXvQMIp;
        "spigot-1.21.4" = _LgXvQMIp;
        "spigot-1.21.5" = _LgXvQMIp;
        "spigot-1.21.6" = _LgXvQMIp;
        "spigot-1.21.7" = _LgXvQMIp;
        "spigot-1.21.8" = _LgXvQMIp;
        "spigot-1.21.9" = _LgXvQMIp;
        "spigot-1.21.10" = _LgXvQMIp;
        "spigot-1.21.11" = _LgXvQMIp;
        "spigot-26.1" = _LgXvQMIp;
        "spigot-26.1.1" = _LgXvQMIp;
        "spigot-26.1.2" = _LgXvQMIp;
        "bukkit-1.18" = _LgXvQMIp;
        "bukkit-1.18.1" = _LgXvQMIp;
        "bukkit-1.18.2" = _LgXvQMIp;
        "bukkit-1.19" = _LgXvQMIp;
        "bukkit-1.19.1" = _LgXvQMIp;
        "bukkit-1.19.2" = _LgXvQMIp;
        "bukkit-1.19.3" = _LgXvQMIp;
        "bukkit-1.19.4" = _LgXvQMIp;
        "bukkit-1.20" = _LgXvQMIp;
        "bukkit-1.20.1" = _LgXvQMIp;
        "bukkit-1.20.2" = _LgXvQMIp;
        "bukkit-1.20.3" = _LgXvQMIp;
        "bukkit-1.20.4" = _LgXvQMIp;
        "bukkit-1.20.5" = _LgXvQMIp;
        "bukkit-1.20.6" = _LgXvQMIp;
        "bukkit-1.21" = _LgXvQMIp;
        "bukkit-1.21.1" = _LgXvQMIp;
        "bukkit-1.21.2" = _LgXvQMIp;
        "bukkit-1.21.3" = _LgXvQMIp;
        "bukkit-1.21.4" = _LgXvQMIp;
        "bukkit-1.21.5" = _LgXvQMIp;
        "bukkit-1.21.6" = _LgXvQMIp;
        "bukkit-1.21.7" = _LgXvQMIp;
        "bukkit-1.21.8" = _LgXvQMIp;
        "bukkit-1.21.9" = _LgXvQMIp;
        "bukkit-1.21.10" = _LgXvQMIp;
        "bukkit-1.21.11" = _LgXvQMIp;
        "bukkit-26.1" = _LgXvQMIp;
        "bukkit-26.1.1" = _LgXvQMIp;
        "bukkit-26.1.2" = _LgXvQMIp;
        "folia-1.18" = _LgXvQMIp;
        "folia-1.18.1" = _LgXvQMIp;
        "folia-1.18.2" = _LgXvQMIp;
        "folia-1.19" = _LgXvQMIp;
        "folia-1.19.1" = _LgXvQMIp;
        "folia-1.19.2" = _LgXvQMIp;
        "folia-1.19.3" = _LgXvQMIp;
        "folia-1.19.4" = _LgXvQMIp;
        "folia-1.20" = _LgXvQMIp;
        "folia-1.20.1" = _LgXvQMIp;
        "folia-1.20.2" = _LgXvQMIp;
        "folia-1.20.3" = _LgXvQMIp;
        "folia-1.20.4" = _LgXvQMIp;
        "folia-1.20.5" = _LgXvQMIp;
        "folia-1.20.6" = _LgXvQMIp;
        "folia-1.21" = _LgXvQMIp;
        "folia-1.21.1" = _LgXvQMIp;
        "folia-1.21.2" = _LgXvQMIp;
        "folia-1.21.3" = _LgXvQMIp;
        "folia-1.21.4" = _LgXvQMIp;
        "folia-1.21.5" = _LgXvQMIp;
        "folia-1.21.6" = _LgXvQMIp;
        "folia-1.21.7" = _LgXvQMIp;
        "folia-1.21.8" = _LgXvQMIp;
        "folia-1.21.9" = _LgXvQMIp;
        "folia-1.21.10" = _LgXvQMIp;
        "folia-1.21.11" = _LgXvQMIp;
        "folia-26.1" = _LgXvQMIp;
        "folia-26.1.1" = _LgXvQMIp;
        "folia-26.1.2" = _LgXvQMIp;
        "default" = _LgXvQMIp;
    });
    fn = {stdenv, fetchurl, version, ...}:
        lib.prismnix.pkgs.mkVersionedModrinthPkg {
            inherit stdenv fetchurl;
            name = "noble-whitelist-discord-integration";
            id = "WWbtvBwl";
            type = "mod";
            version = version;
            versions = versions;
            meta = {
                license = lib.getLicenseFromSpdxIdOr "MIT" {
                    free = false;
                    deprecated = false;
                    redistributable = false;
                    fullName = "MIT License";
                    shortName = "MIT";
                    url = "https://github.com/NobelD/NobleWhitelist/blob/master/LICENSE";
                };
            };
        };
in callPackage fn {version="default";}