{lib, callPackage, ...}:
let
    versions = (let
        _3zYISuFK = {
            "id" = "3zYISuFK";
            "file" = "yosbr-0.1.0.jar";
            "hash" = "sha512-9GSlpiyBtXHTPIQcJpsfnAMskuxwAZTtAXaiNXBhia2DCm0zVmuJBCk7Cd7nhrQA6RI5aKgOl1r+IuVtEgsDFQ==";
        };
        _dStXfyg3 = {
            "id" = "dStXfyg3";
            "file" = "yosbr-0.1.1.jar";
            "hash" = "sha512-jt1H/No3Zli1+4v7MzxEHsqh/oNNPeqmuYlbucffwATS6MzBKkHkt58Q5mNIJIN7VTbDu4EonhN6vGB50chxww==";
        };
        _KMOzdYko = {
            "id" = "KMOzdYko";
            "file" = "yosbr-0.1.2.jar";
            "hash" = "sha512-JU8iJfZEZSOqjIJ06Dsx4n87KvyP5PSQ+xsWndUY4Qx5k6zaXbCrWXR03fnWlQa155QkL62h4vie17+dQSqPeA==";
        };
    in {
        "3zYISuFK" = _3zYISuFK;
        "dStXfyg3" = _dStXfyg3;
        "KMOzdYko" = _KMOzdYko;
        "fabric-1.14" = _KMOzdYko;
        "fabric-1.14.1" = _KMOzdYko;
        "fabric-1.14.2" = _KMOzdYko;
        "fabric-1.14.3" = _KMOzdYko;
        "fabric-1.14.4" = _KMOzdYko;
        "fabric-1.15" = _KMOzdYko;
        "fabric-1.15.1" = _KMOzdYko;
        "fabric-1.15.2" = _KMOzdYko;
        "fabric-1.8.9" = _dStXfyg3;
        "fabric-1.16" = _KMOzdYko;
        "fabric-1.16.1" = _KMOzdYko;
        "fabric-1.16.2" = _KMOzdYko;
        "fabric-1.16.3" = _KMOzdYko;
        "fabric-1.16.4" = _KMOzdYko;
        "fabric-1.16.5" = _KMOzdYko;
        "fabric-1.17" = _KMOzdYko;
        "fabric-1.17.1" = _KMOzdYko;
        "fabric-1.18" = _KMOzdYko;
        "fabric-1.18.1" = _KMOzdYko;
        "fabric-1.18.2" = _KMOzdYko;
        "fabric-1.19" = _KMOzdYko;
        "fabric-1.19.1" = _KMOzdYko;
        "fabric-1.19.2" = _KMOzdYko;
        "fabric-1.19.3" = _KMOzdYko;
        "fabric-1.19.4" = _KMOzdYko;
        "fabric-1.20" = _KMOzdYko;
        "fabric-1.20.1" = _KMOzdYko;
        "fabric-1.20.2" = _KMOzdYko;
        "fabric-1.20.3" = _KMOzdYko;
        "fabric-1.20.4" = _KMOzdYko;
        "fabric-1.20.5" = _KMOzdYko;
        "fabric-1.20.6" = _KMOzdYko;
        "fabric-1.21" = _KMOzdYko;
        "fabric-1.21.1" = _KMOzdYko;
        "fabric-1.21.2" = _KMOzdYko;
        "fabric-1.21.3" = _KMOzdYko;
        "fabric-1.21.4" = _KMOzdYko;
        "fabric-1.21.5" = _KMOzdYko;
        "fabric-1.21.6" = _KMOzdYko;
        "fabric-1.21.7" = _KMOzdYko;
        "fabric-1.21.8" = _KMOzdYko;
        "fabric-1.21.9" = _KMOzdYko;
        "fabric-1.21.10" = _KMOzdYko;
        "fabric-1.21.11" = _KMOzdYko;
        "fabric-26.1" = _KMOzdYko;
        "fabric-26.1.1" = _KMOzdYko;
        "fabric-26.1.2" = _KMOzdYko;
        "fabric-26.2-rc-2" = _KMOzdYko;
        "quilt-1.8.9" = _dStXfyg3;
        "quilt-1.14" = _KMOzdYko;
        "quilt-1.14.1" = _KMOzdYko;
        "quilt-1.14.2" = _KMOzdYko;
        "quilt-1.14.3" = _KMOzdYko;
        "quilt-1.14.4" = _KMOzdYko;
        "quilt-1.15" = _KMOzdYko;
        "quilt-1.15.1" = _KMOzdYko;
        "quilt-1.15.2" = _KMOzdYko;
        "quilt-1.16" = _KMOzdYko;
        "quilt-1.16.1" = _KMOzdYko;
        "quilt-1.16.2" = _KMOzdYko;
        "quilt-1.16.3" = _KMOzdYko;
        "quilt-1.16.4" = _KMOzdYko;
        "quilt-1.16.5" = _KMOzdYko;
        "quilt-1.17" = _KMOzdYko;
        "quilt-1.17.1" = _KMOzdYko;
        "quilt-1.18" = _KMOzdYko;
        "quilt-1.18.1" = _KMOzdYko;
        "quilt-1.18.2" = _KMOzdYko;
        "quilt-1.19" = _KMOzdYko;
        "quilt-1.19.1" = _KMOzdYko;
        "quilt-1.19.2" = _KMOzdYko;
        "quilt-1.19.3" = _KMOzdYko;
        "quilt-1.19.4" = _KMOzdYko;
        "quilt-1.20" = _KMOzdYko;
        "quilt-1.20.1" = _KMOzdYko;
        "quilt-1.20.2" = _KMOzdYko;
        "quilt-1.20.3" = _KMOzdYko;
        "quilt-1.20.4" = _KMOzdYko;
        "quilt-1.20.5" = _KMOzdYko;
        "quilt-1.20.6" = _KMOzdYko;
        "quilt-1.21" = _KMOzdYko;
        "quilt-1.21.1" = _KMOzdYko;
        "quilt-1.21.2" = _KMOzdYko;
        "quilt-1.21.3" = _KMOzdYko;
        "quilt-1.21.4" = _KMOzdYko;
        "quilt-1.21.5" = _KMOzdYko;
        "quilt-1.21.6" = _KMOzdYko;
        "quilt-1.21.7" = _KMOzdYko;
        "quilt-1.21.8" = _KMOzdYko;
        "quilt-1.21.9" = _KMOzdYko;
        "quilt-1.21.10" = _KMOzdYko;
        "quilt-1.21.11" = _KMOzdYko;
        "quilt-26.1" = _KMOzdYko;
        "quilt-26.1.1" = _KMOzdYko;
        "quilt-26.1.2" = _KMOzdYko;
        "quilt-26.2-rc-2" = _KMOzdYko;
        "default" = _KMOzdYko;
    });
    fn = {stdenv, fetchurl, version, ...}:
        lib.prismnix.pkgs.mkVersionedModrinthPkg {
            inherit stdenv fetchurl;
            name = "yosbr";
            id = "WwbubTsV";
            type = "mod";
            version = version;
            versions = versions;
            meta = {
                license = lib.getLicenseFromSpdxIdOr "LGPL-3.0-only" {
                    free = false;
                    deprecated = false;
                    redistributable = false;
                    fullName = "GNU Lesser General Public License v3.0 only";
                    shortName = "LGPL-3.0-only";
                    url = null;
                };
            };
        };
in callPackage fn {version="default";}