{lib, callPackage, ...}:
let
    versions = (let
        _H78kMJ9t = {
            "id" = "H78kMJ9t";
            "file" = "Roblox sounds.zip";
            "hash" = "sha512-a69WY/gGpMdupU6bYCYPWdSynKdmAOUAyNRDii8l6bdjKMZb4kS9jKkKroKbhhwNFry+FpEt5ZpcJ2EJp08GMQ==";
        };
        _FCG5mVKT = {
            "id" = "FCG5mVKT";
            "file" = "Roblox Sounds and Music.zip";
            "hash" = "sha512-zkncQ3XNb5XYWdrxn+qTMqe+xid1j1MsFQ7koT3+qbZPyqzA9hR2ADHlMOpFD2lRw+944btS3oTmBSv8rhHdNw==";
        };
    in {
        "H78kMJ9t" = _H78kMJ9t;
        "FCG5mVKT" = _FCG5mVKT;
        "minecraft-1.20" = _FCG5mVKT;
        "minecraft-1.20.1" = _FCG5mVKT;
        "minecraft-1.20.2" = _FCG5mVKT;
        "minecraft-1.20.3" = _FCG5mVKT;
        "minecraft-1.20.4" = _FCG5mVKT;
        "minecraft-1.2.4" = _FCG5mVKT;
        "minecraft-1.2.5" = _FCG5mVKT;
        "minecraft-1.3.1" = _FCG5mVKT;
        "minecraft-1.3.2" = _FCG5mVKT;
        "minecraft-1.4.2" = _FCG5mVKT;
        "minecraft-1.4.4" = _FCG5mVKT;
        "minecraft-1.4.5" = _FCG5mVKT;
        "minecraft-1.4.6" = _FCG5mVKT;
        "minecraft-1.4.7" = _FCG5mVKT;
        "minecraft-1.5.1" = _FCG5mVKT;
        "minecraft-1.5.2" = _FCG5mVKT;
        "minecraft-1.6.1" = _FCG5mVKT;
        "minecraft-1.6.2" = _FCG5mVKT;
        "minecraft-1.6.4" = _FCG5mVKT;
        "minecraft-1.7.2" = _FCG5mVKT;
        "minecraft-1.7.3" = _FCG5mVKT;
        "minecraft-1.7.4" = _FCG5mVKT;
        "minecraft-1.7.5" = _FCG5mVKT;
        "minecraft-1.7.6" = _FCG5mVKT;
        "minecraft-1.7.7" = _FCG5mVKT;
        "minecraft-1.7.8" = _FCG5mVKT;
        "minecraft-1.7.9" = _FCG5mVKT;
        "minecraft-1.7.10" = _FCG5mVKT;
        "minecraft-1.8" = _FCG5mVKT;
        "minecraft-1.8.1" = _FCG5mVKT;
        "minecraft-1.8.2" = _FCG5mVKT;
        "minecraft-1.8.3" = _FCG5mVKT;
        "minecraft-1.8.4" = _FCG5mVKT;
        "minecraft-1.8.5" = _FCG5mVKT;
        "minecraft-1.8.6" = _FCG5mVKT;
        "minecraft-1.8.7" = _FCG5mVKT;
        "minecraft-1.8.8" = _FCG5mVKT;
        "minecraft-1.8.9" = _FCG5mVKT;
        "minecraft-1.9" = _FCG5mVKT;
        "minecraft-1.9.1" = _FCG5mVKT;
        "minecraft-1.9.2" = _FCG5mVKT;
        "minecraft-1.9.3" = _FCG5mVKT;
        "minecraft-1.9.4" = _FCG5mVKT;
        "minecraft-1.10" = _FCG5mVKT;
        "minecraft-1.10.1" = _FCG5mVKT;
        "minecraft-1.10.2" = _FCG5mVKT;
        "minecraft-1.11" = _FCG5mVKT;
        "minecraft-1.11.1" = _FCG5mVKT;
        "minecraft-1.11.2" = _FCG5mVKT;
        "minecraft-1.12" = _FCG5mVKT;
        "minecraft-1.12.1" = _FCG5mVKT;
        "minecraft-1.12.2" = _FCG5mVKT;
        "minecraft-1.13" = _FCG5mVKT;
        "minecraft-1.13.1" = _FCG5mVKT;
        "minecraft-1.13.2" = _FCG5mVKT;
        "minecraft-1.14" = _FCG5mVKT;
        "minecraft-1.14.1" = _FCG5mVKT;
        "minecraft-1.14.2" = _FCG5mVKT;
        "minecraft-1.14.3" = _FCG5mVKT;
        "minecraft-1.14.4" = _FCG5mVKT;
        "minecraft-1.15" = _FCG5mVKT;
        "minecraft-1.15.1" = _FCG5mVKT;
        "minecraft-1.15.2" = _FCG5mVKT;
        "minecraft-1.16" = _FCG5mVKT;
        "minecraft-1.16.1" = _FCG5mVKT;
        "minecraft-1.16.2" = _FCG5mVKT;
        "minecraft-1.16.3" = _FCG5mVKT;
        "minecraft-1.16.4" = _FCG5mVKT;
        "minecraft-1.16.5" = _FCG5mVKT;
        "minecraft-1.17" = _FCG5mVKT;
        "minecraft-1.17.1" = _FCG5mVKT;
        "minecraft-1.18" = _FCG5mVKT;
        "minecraft-1.18.1" = _FCG5mVKT;
        "minecraft-1.18.2" = _FCG5mVKT;
        "minecraft-1.19" = _FCG5mVKT;
        "minecraft-1.19.1" = _FCG5mVKT;
        "minecraft-1.19.2" = _FCG5mVKT;
        "minecraft-1.19.3" = _FCG5mVKT;
        "minecraft-1.19.4" = _FCG5mVKT;
        "pkg-1.0" = _H78kMJ9t;
        "pkg-1.1" = _FCG5mVKT;
        "default" = _FCG5mVKT;
    });
    fn = lib.prismnix.pkgs.mkVersionedModrinthPkgFn {
        name = "roblox-sounds-and-music";
        id = "YprNrDH7";
        type = "resourcepack";
        versions = versions;
        meta = {
            license = lib.getLicenseFromSpdxIdOr "LicenseRef-All-Rights-Reserved" {
                free = false;
                deprecated = false;
                redistributable = false;
                fullName = "LicenseRef-All-Rights-Reserved";
                shortName = "LicenseRef-All-Rights-Reserved";
                url = null;
            };
        };
    };
in callPackage fn {}