{lib, callPackage, ...}:
let
    versions = (let
        _MJbcCHzK = {
            "id" = "MJbcCHzK";
            "file" = "Backrooms Retextured.zip";
            "hash" = "sha512-asreuiTdFf00mCoeYGdIeOmKm0Jk0kbIYYvKMI68SpPEqfNNPjDr4X0fw1lbcV/cUUKdbvUWv+yh5XsatV9nHQ==";
        };
        _uT436w1f = {
            "id" = "uT436w1f";
            "file" = "backrooms retextured.zip";
            "hash" = "sha512-cE0/0KU4C3av213V0OcKeFLOxMwih8mY87UlKqe7iA4Cy5FrDsL5aZwjaT5a61ehIm17CTijIZOT48ElH6EHpQ==";
        };
        _nvS4KYZE = {
            "id" = "nvS4KYZE";
            "file" = "Backrooms Retextured 2.1.zip";
            "hash" = "sha512-sn3gm9XXQNAonhjBuqXRfm9VFE9raM1d1mrcT65GqJCzbm9GwW6GBtY3OQGIWHKijm0C1EKGsQNA9+YzvDPzlg==";
        };
        _L7u84NjE = {
            "id" = "L7u84NjE";
            "file" = "Backrooms Retextured 3.0.zip";
            "hash" = "sha512-dTT5SYsvLXEmji107pNyECPxH3QoaHyb2xFq0rYT/1VJXiQpKKn7vqlqwRqRxO61OlTfcCjfFyayWoG+iW/LLw==";
        };
        _chQXpDuc = {
            "id" = "chQXpDuc";
            "file" = "Backrooms Retextured 4.0.zip";
            "hash" = "sha512-349KnlMOLDHFRqtqNqn9pk6MEC/sqeerbO/lf06PiVzSHL9xTbP+fFGjfBgWoRLMy8v3kjqVH0aufGpPapAG4g==";
        };
        _7EJfSleK = {
            "id" = "7EJfSleK";
            "file" = "Backrooms Retextured 4.1.zip";
            "hash" = "sha512-Gjy9r+YGJpPNW5+FC1CwrC53Df4j/FDdi3ilM28nsWVz8lisBzHVQPvKRhR813NCazybFtUGa3Jo7j+H49fNRg==";
        };
        _n9gm1DYJ = {
            "id" = "n9gm1DYJ";
            "file" = "Backrooms Retextured 5.0.zip";
            "hash" = "sha512-jarJcF5+i2ZeGx4nDJY47QLDx1I0cEvwwsUYqai1Ox/gWuQdt3zskcxIFNEqkbgebwMajUPttagtDwFWOn+IVw==";
        };
        _X6hFrFdv = {
            "id" = "X6hFrFdv";
            "file" = "Backrooms Retextured 5.1.zip";
            "hash" = "sha512-cAQUYOA+KjuT2ldsBYVF/+xYAbDSCpVYrejkbPPBK47QEDp/5pQ1v/AbMkhkYs5tJEawSLxBvXW+6Q39u0FxgA==";
        };
        _dKCulTaq = {
            "id" = "dKCulTaq";
            "file" = "Backrooms Retextured 5.1.2.zip";
            "hash" = "sha512-PbP6OJxbpLCr+0K6ZlBFjcOVqaNtbTzFPH5j+IVyALfspNd6z+wW69/K+gnuJIzu2KjdN/HKLmxMla3G1pmdsA==";
        };
    in {
        "MJbcCHzK" = _MJbcCHzK;
        "uT436w1f" = _uT436w1f;
        "nvS4KYZE" = _nvS4KYZE;
        "L7u84NjE" = _L7u84NjE;
        "chQXpDuc" = _chQXpDuc;
        "7EJfSleK" = _7EJfSleK;
        "n9gm1DYJ" = _n9gm1DYJ;
        "X6hFrFdv" = _X6hFrFdv;
        "dKCulTaq" = _dKCulTaq;
        "minecraft-1.12" = _dKCulTaq;
        "minecraft-1.12.1" = _dKCulTaq;
        "minecraft-1.12.2" = _dKCulTaq;
        "minecraft-1.15" = _dKCulTaq;
        "minecraft-1.15.1" = _dKCulTaq;
        "minecraft-1.15.2" = _dKCulTaq;
        "minecraft-1.16" = _dKCulTaq;
        "minecraft-1.16.1" = _dKCulTaq;
        "minecraft-1.16.2" = _dKCulTaq;
        "minecraft-1.16.3" = _dKCulTaq;
        "minecraft-1.16.4" = _dKCulTaq;
        "minecraft-1.16.5" = _dKCulTaq;
        "minecraft-1.17" = _dKCulTaq;
        "minecraft-1.17.1" = _dKCulTaq;
        "minecraft-1.18" = _dKCulTaq;
        "minecraft-1.18.1" = _dKCulTaq;
        "minecraft-1.18.2" = _dKCulTaq;
        "minecraft-1.19" = _dKCulTaq;
        "minecraft-1.19.1" = _dKCulTaq;
        "minecraft-1.19.2" = _dKCulTaq;
        "minecraft-1.19.3" = _dKCulTaq;
        "minecraft-1.19.4" = _dKCulTaq;
        "minecraft-1.20" = _dKCulTaq;
        "minecraft-1.20.1" = _dKCulTaq;
        "minecraft-1.20.2" = _dKCulTaq;
        "minecraft-1.20.3" = _dKCulTaq;
        "minecraft-1.20.4" = _dKCulTaq;
        "minecraft-1.20.5" = _dKCulTaq;
        "minecraft-1.20.6" = _dKCulTaq;
        "minecraft-1.21" = _dKCulTaq;
        "minecraft-1.21.1" = _dKCulTaq;
        "minecraft-1.21.2" = _dKCulTaq;
        "minecraft-1.21.3" = _dKCulTaq;
        "minecraft-1.21.4" = _dKCulTaq;
        "minecraft-1.21.5" = _dKCulTaq;
        "minecraft-1.21.6" = _dKCulTaq;
        "minecraft-1.21.7" = _dKCulTaq;
        "minecraft-1.21.8" = _dKCulTaq;
        "minecraft-1.21.9" = _dKCulTaq;
        "minecraft-1.21.10" = _dKCulTaq;
        "minecraft-1.21.11" = _dKCulTaq;
        "minecraft-26.1" = _dKCulTaq;
        "minecraft-26.1.1" = _dKCulTaq;
        "minecraft-26.1.2" = _dKCulTaq;
        "minecraft-22w42a" = _7EJfSleK;
        "minecraft-22w43a" = _7EJfSleK;
        "minecraft-22w44a" = _7EJfSleK;
        "minecraft-23w14a" = _7EJfSleK;
        "minecraft-23w16a" = _7EJfSleK;
        "minecraft-23w31a" = _7EJfSleK;
        "minecraft-23w32a" = _7EJfSleK;
        "minecraft-23w33a" = _7EJfSleK;
        "minecraft-23w35a" = _7EJfSleK;
        "minecraft-1.20.2-pre1" = _7EJfSleK;
        "minecraft-23w42a" = _7EJfSleK;
        "minecraft-23w43a" = _7EJfSleK;
        "minecraft-23w43b" = _7EJfSleK;
        "minecraft-23w44a" = _7EJfSleK;
        "minecraft-23w45a" = _7EJfSleK;
        "minecraft-23w46a" = _7EJfSleK;
        "minecraft-24w03a" = _7EJfSleK;
        "minecraft-24w03b" = _7EJfSleK;
        "minecraft-24w04a" = _7EJfSleK;
        "minecraft-24w05a" = _7EJfSleK;
        "minecraft-24w05b" = _7EJfSleK;
        "minecraft-24w06a" = _7EJfSleK;
        "minecraft-24w07a" = _7EJfSleK;
        "minecraft-24w09a" = _7EJfSleK;
        "minecraft-24w10a" = _7EJfSleK;
        "minecraft-24w11a" = _7EJfSleK;
        "minecraft-24w12a" = _7EJfSleK;
        "minecraft-24w13a" = _7EJfSleK;
        "minecraft-24w14potato" = _7EJfSleK;
        "minecraft-24w14a" = _7EJfSleK;
        "minecraft-1.20.5-pre1" = _7EJfSleK;
        "minecraft-1.20.5-pre2" = _7EJfSleK;
        "minecraft-1.20.5-pre3" = _7EJfSleK;
        "minecraft-1.20.6-rc1" = _L7u84NjE;
        "minecraft-24w18a" = _7EJfSleK;
        "minecraft-24w19a" = _7EJfSleK;
        "minecraft-24w19b" = _7EJfSleK;
        "minecraft-24w20a" = _7EJfSleK;
        "minecraft-24w33a" = _7EJfSleK;
        "minecraft-24w34a" = _7EJfSleK;
        "minecraft-24w35a" = _7EJfSleK;
        "minecraft-24w36a" = _7EJfSleK;
        "minecraft-24w37a" = _7EJfSleK;
        "minecraft-24w38a" = _7EJfSleK;
        "minecraft-24w39a" = _7EJfSleK;
        "minecraft-24w40a" = _7EJfSleK;
        "minecraft-1.21.2-pre1" = _7EJfSleK;
        "minecraft-1.21.2-pre2" = _7EJfSleK;
        "minecraft-24w44a" = _7EJfSleK;
        "minecraft-24w45a" = _7EJfSleK;
        "minecraft-24w46a" = _7EJfSleK;
        "minecraft-26.1-snapshot-9" = _L7u84NjE;
        "minecraft-26.1-snapshot-10" = _L7u84NjE;
        "minecraft-26.1-snapshot-11" = _L7u84NjE;
        "minecraft-26.1-pre-1" = _L7u84NjE;
        "minecraft-26.1-pre-2" = _L7u84NjE;
        "minecraft-26.1-pre-3" = _chQXpDuc;
        "minecraft-26.1-rc-1" = _chQXpDuc;
        "minecraft-26.1-rc-2" = _chQXpDuc;
        "minecraft-26.1-rc-3" = _chQXpDuc;
        "minecraft-26.1.1-rc-1" = _chQXpDuc;
        "minecraft-26.2-snapshot-1" = _chQXpDuc;
        "minecraft-26.1.2-rc-1" = _chQXpDuc;
        "minecraft-26.2-snapshot-2" = _chQXpDuc;
        "minecraft-26.2-snapshot-3" = _chQXpDuc;
        "minecraft-26.2-snapshot-4" = _chQXpDuc;
        "minecraft-26.2-snapshot-5" = _chQXpDuc;
        "minecraft-26.2-snapshot-6" = _chQXpDuc;
        "minecraft-26.2-snapshot-7" = _chQXpDuc;
        "minecraft-26.2-snapshot-8" = _chQXpDuc;
        "minecraft-26.2-pre-1" = _chQXpDuc;
        "minecraft-26.2-pre-2" = _chQXpDuc;
        "minecraft-26.2-pre-3" = _chQXpDuc;
        "minecraft-1.14" = _dKCulTaq;
        "minecraft-1.14.1" = _dKCulTaq;
        "minecraft-1.14.2" = _dKCulTaq;
        "minecraft-1.14.3" = _dKCulTaq;
        "minecraft-1.14.4" = _dKCulTaq;
        "minecraft-26.2-pre-4" = _chQXpDuc;
        "minecraft-26.2-pre-5" = _chQXpDuc;
        "minecraft-26.2" = _dKCulTaq;
        "minecraft-1.11" = _dKCulTaq;
        "minecraft-1.11.1" = _dKCulTaq;
        "minecraft-1.11.2" = _dKCulTaq;
        "minecraft-1.13" = _dKCulTaq;
        "minecraft-1.13.1" = _dKCulTaq;
        "minecraft-1.13.2" = _dKCulTaq;
        "minecraft-1.9" = _dKCulTaq;
        "minecraft-1.9.1" = _dKCulTaq;
        "minecraft-1.9.2" = _dKCulTaq;
        "minecraft-1.9.3" = _dKCulTaq;
        "minecraft-1.9.4" = _dKCulTaq;
        "minecraft-1.10" = _dKCulTaq;
        "minecraft-1.10.1" = _dKCulTaq;
        "minecraft-1.10.2" = _dKCulTaq;
    });
    fn = {stdenv, fetchurl, version, ...}:
        lib.prismnix.pkgs.mkVersionedModrinthPkg {
            inherit stdenv fetchurl;
            name = "backrooms-retextured";
            id = "YYuNNPku";
            type = "resourcepack";
            version = version;
            versions = versions;
            meta = {
                license = lib.getLicenseFromSpdxIdOr "LicenseRef-All-Rights-Reserved" {
                    free = false;
                    deprecated = false;
                    redistributable = false;
                    fullName = "LicenseRef-All-Rights-Reserved";
                    shortName = "LicenseRef-All-Rights-Reserved";
                    url = null;
                };
            };
        };
in callPackage fn {version="dKCulTaq";}