{lib, callPackage, ...}:
let
    versions = (let
        _eN0Vg0XA = {
            "id" = "eN0Vg0XA";
            "file" = "3D TOTEM.zip";
            "hash" = "sha512-/vCSHpSNQyyJEoNDDfLYHGxgV+BtVwsiCa7Qb5WzZjfzE86Ml3+vdDHFOZFn1dLPBjCcOcjAaIbqN6sHpmgJGA==";
        };
        _dXliNrdz = {
            "id" = "dXliNrdz";
            "file" = "3D TOTEM.zip";
            "hash" = "sha512-ouOetbCz4K+TFodiiBVylV9mow+L3k/BsbAmsxegVN6ZWfvt6zNrC1soghLtcmLNpaAmsz/jQ0pPEFHuuYo/RQ==";
        };
        _okzHTKw2 = {
            "id" = "okzHTKw2";
            "file" = "3D PLAYER TOTEM.zip";
            "hash" = "sha512-rnPQVXrB7H8qPoaW7W3cvkKamwvYuvEDDNHNJljQgbG+Ba2bsEnnkBxCSmttSOD29KcH5stzoWVzjiwNx802Ig==";
        };
    in {
        "eN0Vg0XA" = _eN0Vg0XA;
        "dXliNrdz" = _dXliNrdz;
        "okzHTKw2" = _okzHTKw2;
        "minecraft-1.10" = _dXliNrdz;
        "minecraft-1.10.1" = _dXliNrdz;
        "minecraft-1.10.2" = _dXliNrdz;
        "minecraft-1.11" = _dXliNrdz;
        "minecraft-1.11.1" = _dXliNrdz;
        "minecraft-1.11.2" = _dXliNrdz;
        "minecraft-1.12" = _dXliNrdz;
        "minecraft-1.12.1" = _dXliNrdz;
        "minecraft-1.12.2" = _dXliNrdz;
        "minecraft-1.13" = _dXliNrdz;
        "minecraft-1.13.1" = _dXliNrdz;
        "minecraft-1.13.2" = _dXliNrdz;
        "minecraft-1.14" = _okzHTKw2;
        "minecraft-1.14.1" = _okzHTKw2;
        "minecraft-1.14.2" = _okzHTKw2;
        "minecraft-1.14.3" = _okzHTKw2;
        "minecraft-1.14.4" = _okzHTKw2;
        "minecraft-1.15" = _okzHTKw2;
        "minecraft-1.15.1" = _okzHTKw2;
        "minecraft-1.15.2" = _okzHTKw2;
        "minecraft-1.16" = _okzHTKw2;
        "minecraft-1.16.1" = _okzHTKw2;
        "minecraft-1.16.2" = _okzHTKw2;
        "minecraft-1.16.3" = _okzHTKw2;
        "minecraft-1.16.4" = _okzHTKw2;
        "minecraft-1.16.5" = _okzHTKw2;
        "minecraft-1.17" = _okzHTKw2;
        "minecraft-1.17.1" = _okzHTKw2;
        "minecraft-1.18" = _okzHTKw2;
        "minecraft-1.18.1" = _okzHTKw2;
        "minecraft-1.18.2" = _okzHTKw2;
        "minecraft-1.19" = _okzHTKw2;
        "minecraft-1.19.1" = _okzHTKw2;
        "minecraft-1.19.2" = _okzHTKw2;
        "minecraft-1.19.3" = _okzHTKw2;
        "minecraft-1.19.4" = _okzHTKw2;
        "minecraft-1.20" = _okzHTKw2;
        "minecraft-1.20.1" = _okzHTKw2;
        "minecraft-1.20.2" = _okzHTKw2;
        "minecraft-1.20.3" = _okzHTKw2;
        "minecraft-1.20.4" = _okzHTKw2;
        "minecraft-1.20.5" = _okzHTKw2;
        "minecraft-1.20.6" = _okzHTKw2;
        "minecraft-1.21" = _okzHTKw2;
        "minecraft-1.21.1" = _okzHTKw2;
        "minecraft-1.21.2" = _okzHTKw2;
        "minecraft-1.21.3" = _okzHTKw2;
        "minecraft-1.21.4" = _okzHTKw2;
        "minecraft-1.21.5" = _okzHTKw2;
        "minecraft-1.21.6" = _okzHTKw2;
        "minecraft-1.21.7" = _okzHTKw2;
        "minecraft-1.21.8" = _okzHTKw2;
        "minecraft-22w42a" = _okzHTKw2;
        "minecraft-22w43a" = _okzHTKw2;
        "minecraft-22w44a" = _okzHTKw2;
        "minecraft-23w14a" = _okzHTKw2;
        "minecraft-23w16a" = _okzHTKw2;
        "minecraft-23w31a" = _okzHTKw2;
        "minecraft-23w32a" = _okzHTKw2;
        "minecraft-23w33a" = _okzHTKw2;
        "minecraft-23w35a" = _okzHTKw2;
        "minecraft-1.20.2-pre1" = _okzHTKw2;
        "minecraft-23w42a" = _okzHTKw2;
        "minecraft-23w43a" = _okzHTKw2;
        "minecraft-23w43b" = _okzHTKw2;
        "minecraft-23w44a" = _okzHTKw2;
        "minecraft-23w45a" = _okzHTKw2;
        "minecraft-23w46a" = _okzHTKw2;
        "minecraft-24w03a" = _okzHTKw2;
        "minecraft-24w03b" = _okzHTKw2;
        "minecraft-24w04a" = _okzHTKw2;
        "minecraft-24w05a" = _okzHTKw2;
        "minecraft-24w05b" = _okzHTKw2;
        "minecraft-24w06a" = _okzHTKw2;
        "minecraft-24w07a" = _okzHTKw2;
        "minecraft-24w09a" = _okzHTKw2;
        "minecraft-24w10a" = _okzHTKw2;
        "minecraft-24w11a" = _okzHTKw2;
        "minecraft-24w12a" = _okzHTKw2;
        "minecraft-24w13a" = _okzHTKw2;
        "minecraft-24w14potato" = _okzHTKw2;
        "minecraft-24w14a" = _okzHTKw2;
        "minecraft-1.20.5-pre1" = _okzHTKw2;
        "minecraft-1.20.5-pre2" = _okzHTKw2;
        "minecraft-1.20.5-pre3" = _okzHTKw2;
        "minecraft-24w18a" = _okzHTKw2;
        "minecraft-24w19a" = _okzHTKw2;
        "minecraft-24w19b" = _okzHTKw2;
        "minecraft-24w20a" = _okzHTKw2;
        "minecraft-24w33a" = _okzHTKw2;
        "minecraft-24w34a" = _okzHTKw2;
        "minecraft-24w35a" = _okzHTKw2;
        "minecraft-24w36a" = _okzHTKw2;
        "minecraft-24w37a" = _okzHTKw2;
        "minecraft-24w38a" = _okzHTKw2;
        "minecraft-24w39a" = _okzHTKw2;
        "minecraft-24w40a" = _okzHTKw2;
        "minecraft-1.21.2-pre1" = _okzHTKw2;
        "minecraft-1.21.2-pre2" = _okzHTKw2;
        "minecraft-24w44a" = _okzHTKw2;
        "minecraft-24w45a" = _okzHTKw2;
        "minecraft-24w46a" = _okzHTKw2;
        "minecraft-1.21.9" = _okzHTKw2;
        "minecraft-1.21.10" = _okzHTKw2;
        "minecraft-1.21.11" = _okzHTKw2;
        "default" = _okzHTKw2;
    });
    fn = {stdenv, fetchurl, version, ...}:
        lib.prismnix.pkgs.mkVersionedModrinthPkg {
            inherit stdenv fetchurl;
            name = "3d-totem-of-undying";
            id = "ZbtJfj6n";
            type = "resourcepack";
            version = version;
            versions = versions;
            meta = {
                license = lib.getLicenseFromSpdxIdOr "LicenseRef-All-Rights-Reserved" {
                    free = false;
                    deprecated = false;
                    redistributable = false;
                    fullName = "LicenseRef-All-Rights-Reserved";
                    shortName = "LicenseRef-All-Rights-Reserved";
                    url = null;
                };
            };
        };
in callPackage fn {version="default";}